/* Generado por tools/generate_sdf_shader.py. No editar. */
#define P_STRIDE 6
static void PackP(float (*out)[4], const MonsterSDFBodyPart* in) {
    PackVector(out[0], in->center);
    PackVector(out[1], in->radii);
    PackVector(out[2], in->invRadii);
    PackVector(out[3], in->invRadiiSquared);
    out[4][0]=(float)in->minRadius;
    PackColor(out[5], in->color);
}
#define C_STRIDE 29
static void PackC(float (*out)[4], const MonsterSDFConnector* in) {
    PackVector(out[0], in->a);
    PackVector(out[1], in->b);
    PackVector(out[2], in->ba);
    PackVector(out[3], in->forward);
    PackVector(out[4], in->side);
    PackVector(out[5], in->up);
    out[6][0]=(float)in->length;
    out[7][0]=(float)in->invBaLengthSquared;
    out[8][0]=(float)in->r1;
    out[9][0]=(float)in->r2;
    out[10][0]=(float)in->radiusDelta;
    out[11][0]=(float)in->widthA;
    out[12][0]=(float)in->heightA;
    out[13][0]=(float)in->widthB;
    out[14][0]=(float)in->heightB;
    out[15][0]=(float)in->fromId;
    out[16][0]=(float)in->toId;
    out[17][0]=(float)in->kind;
    PackColor(out[18], in->color);
    PackVector(out[19], in->bounds.start);
    PackVector(out[20], in->bounds.end);
    out[21][0]=(float)in->distanceLowerBoundScale;
    out[22][0]=(float)in->groupCount;
    PackVector(out[23], in->groupBounds.start);
    PackVector(out[24], in->groupBounds.end);
    out[25][0]=(float)in->groupLowerBoundScale;
    out[26][0]=(float)in->groupSmoothness;
    out[27][0]=(float)in->maxRadius;
    out[28][0]=(float)in->localSmoothness;
}
#define M_STRIDE 112
static void PackM(float (*out)[4], const MonsterSDFMouth* in) {
    PackVector(out[0], in->center);
    PackVector(out[1], in->visualBounds.start);
    PackVector(out[2], in->visualBounds.end);
    PackVector(out[3], in->visualJawPivot);
    out[4][0]=(float)in->visualJawAngle;
    out[5][0]=(float)in->visualJawScale;
    out[6][0]=(float)in->visualJawBoundRadius;
    PackVector(out[7], in->inverseRotation.row0);
    PackVector(out[8], in->inverseRotation.row1);
    PackVector(out[9], in->inverseRotation.row2);
    PackVector(out[10], in->muzzleCenterLocal);
    PackVector(out[11], in->muzzleHalfExtents);
    out[12][0]=(float)in->muzzleSmoothness;
    out[13][0]=(float)in->cephalicDevelopment;
    PackColor(out[14], in->skinColor);
    PackVector(out[15], in->entranceCenterLocal);
    PackVector(out[16], in->entranceHalfExtents);
    PackVector(out[17], in->cavityCenterLocal);
    PackVector(out[18], in->cavityRadii);
    PackColor(out[19], in->insideColor);
    out[20][0]=(float)in->entranceToCavitySmoothness;
    out[21][0]=(float)in->rimBevel;
    PackVector(out[22], in->jawCenterLocal);
    PackVector(out[23], in->jawRadii);
    PackVector(out[24], in->hingeCenterLocal);
    out[25][0]=(float)in->hingeRadius;
    out[26][0]=(float)in->throatRadius;
    out[27][0]=(float)in->jawRearMass;
    out[28][0]=(float)in->jawMuscle;
    out[29][0]=(float)in->lowerBeak;
    PackVector(out[30], in->hostCenterLocal);
    PackVector(out[31], in->hostRadii);
    PackVector(out[32], in->craniumCenterLocal);
    PackVector(out[33], in->craniumRadii);
    PackVector(out[34], in->snoutCenterLocal);
    PackVector(out[35], in->snoutRadii);
    PackVector(out[36], in->cheekCenterLocal);
    PackVector(out[37], in->cheekRadii);
    PackVector(out[38], in->leftTemporalCenterLocal);
    PackVector(out[39], in->rightTemporalCenterLocal);
    PackVector(out[40], in->temporalRadii);
    PackVector(out[41], in->leftMaxillaryCenterLocal);
    PackVector(out[42], in->rightMaxillaryCenterLocal);
    PackVector(out[43], in->maxillaryRadii);
    PackVector(out[44], in->leftBrowCenterLocal);
    PackVector(out[45], in->rightBrowCenterLocal);
    PackVector(out[46], in->browRadii);
    out[47][0]=(float)in->sweptSkull;
    PackStation(out+48, &in->headStations[0]);
    PackStation(out+50, &in->headStations[1]);
    PackStation(out+52, &in->headStations[2]);
    PackStation(out+54, &in->headStations[3]);
    PackStation(out+56, &in->headStations[4]);
    PackStation(out+58, &in->headStations[5]);
    out[60][0]=(float)in->anatomicalHead;
    PackVector(out[61], in->faceRootLocal);
    PackVector(out[62], in->faceMidLocal);
    PackVector(out[63], in->faceTipLocal);
    PackVector(out[64], in->faceRootRadii);
    PackVector(out[65], in->faceMidRadii);
    PackVector(out[66], in->faceTipRadii);
    PackVector(out[67], in->leftOrbitCenterLocal);
    PackVector(out[68], in->rightOrbitCenterLocal);
    PackVector(out[69], in->orbitRadii);
    PackVector(out[70], in->leftOrbitRimCenterLocal);
    PackVector(out[71], in->rightOrbitRimCenterLocal);
    PackVector(out[72], in->orbitRimRadii);
    PackVector(out[73], in->leftOrbitNormal);
    PackVector(out[74], in->rightOrbitNormal);
    out[75][0]=(float)in->orbitSocketDepth;
    PackVector(out[76], in->noseCenterLocal);
    PackVector(out[77], in->noseRadii);
    PackVector(out[78], in->leftNostrilCenterLocal);
    PackVector(out[79], in->rightNostrilCenterLocal);
    PackVector(out[80], in->nostrilRadii);
    PackVector(out[81], in->leftTympanumCenterLocal);
    PackVector(out[82], in->rightTympanumCenterLocal);
    PackVector(out[83], in->tympanumRadii);
    out[84][0]=(float)in->tympanumDepth;
    PackVector(out[85], in->leftEarCenterLocal);
    PackVector(out[86], in->rightEarCenterLocal);
    PackVector(out[87], in->earRadii);
    out[88][0]=(float)in->headUnionSmoothness;
    out[89][0]=(float)in->headBodySmoothness;
    PackVector(out[90], in->neckCollarRootLocal);
    PackVector(out[91], in->neckCollarTipLocal);
    PackVector(out[92], in->neckCollarRootRadii);
    PackVector(out[93], in->neckCollarTipRadii);
    out[94][0]=(float)in->hasNasalPad;
    out[95][0]=(float)in->hasEars;
    out[96][0]=(float)in->hasTympana;
    out[97][0]=(float)in->taperedMandible;
    out[98][0]=(float)in->faceRounding;
    PackVector(out[99], in->influenceBounds.start);
    PackVector(out[100], in->influenceBounds.end);
    PackVector(out[101], in->headBounds.start);
    PackVector(out[102], in->headBounds.end);
    PackVector(out[103], in->seamSkullLeftLocal);
    PackVector(out[104], in->seamSkullRightLocal);
    PackVector(out[105], in->seamJawLeftClosedLocal);
    PackVector(out[106], in->seamJawRightClosedLocal);
    PackVector(out[107], in->seamGularLocal);
    PackVector(out[108], in->seamJawAnchorLocal);
    out[109][0]=(float)in->seamScale;
    PackVector(out[110], in->seamBounds.start);
    PackVector(out[111], in->seamBounds.end);
}
static const char* const sdfFragmentSource[] = {
"#version 330 compatibility\n",
"uniform samplerBuffer sceneData;\nuniform int partBase, partCount, connectorBase, connectorCount, mouthBase, mouthCount, axialBase, axialCount;\nuniform float bodySmoothness;\n#define Vector3 vec3\n#define Vec3_Create vec3\n#define Vec3_Sub(a,b) ((a)-(b))\n#define Vec3_Add(a,b) ((a)+(b))\n#define Vec3_Scale(a,b) ((a)*(b))\n#define Vec3_Lerp mix\n#define Vec3_Dot dot\n#define Vec3_Cross cross\n#define Vec3_Normalize normalize\n#define Vec3_Distance distance\n#define cosf cos\n#define sinf sin\n#define Vec3_Length length\n#define Vec3_LengthSq(a) dot(a,a)\n#define Math_Max max\n#define Math_Min min\n#define Math_Lerp mix\n#define Math_Clamp clamp\n#define Math_Clamp01(a) clamp(a,0.0,1.0)\n#define fabsf abs\n#define sqrtf sqrt\nvec4 dataAt(int index) { return texelFetch(sceneData,index); }\nvec3 P_center(int i) { return dataAt(i+0).xyz; }\nvec3 P_radii(int i) { return dataAt(i+1).xyz; }\nvec3 P_invRadii(int i) { return dataAt(i+2).xyz; }\nvec3 P_invRadiiSquared(int i) { return dataAt(i+3).xyz; }\nfloat P_minRadius(int i) { return float(dataAt(i+4).x); }\nvec3 P_color(int i) { return dataAt(i+5).xyz; }\n#define P_STRIDE 6\nvec3 C_a(int i) { return dataAt(i+0).xyz; }\nvec3 C_b(int i) { return dataAt(i+1).xyz; }\nvec3 C_ba(int i) { return dataAt(i+2).xyz; }\nvec3 C_forward(int i) { return dataAt(i+3).xyz; }\nvec3 C_side(int i) { return dataAt(i+4).xyz; }\nvec3 C_up(int i) { return dataAt(i+5).xyz; }\nfloat C_length(int i) { return float(dataAt(i+6).x); }\nfloat C_invBaLengthSquared(int i) { return float(dataAt(i+7).x); }\nfloat C_r1(int i) { return float(dataAt(i+8).x); }\nfloat C_r2(int i) { return float(dataAt(i+9).x); }\nfloat C_radiusDelta(int i) { return float(dataAt(i+10).x); }\nfloat C_widthA(int i) { return float(dataAt(i+11).x); }\nfloat C_heightA(int i) { return float(dataAt(i+12).x); }\nfloat C_widthB(int i) { return float(dataAt(i+13).x); }\nfloat C_heightB(int i) { return float(dataAt(i+14).x); }\nint C_fromId(int i) { return int(dataAt(i+15).x); }\nint C_toId(int i) { return int(dataAt(i+16).x); }\nint C_k",
"ind(int i) { return int(dataAt(i+17).x); }\nvec3 C_color(int i) { return dataAt(i+18).xyz; }\nvec3 C_bounds_start(int i) { return dataAt(i+19).xyz; }\nvec3 C_bounds_end(int i) { return dataAt(i+20).xyz; }\nfloat C_distanceLowerBoundScale(int i) { return float(dataAt(i+21).x); }\nint C_groupCount(int i) { return int(dataAt(i+22).x); }\nvec3 C_groupBounds_start(int i) { return dataAt(i+23).xyz; }\nvec3 C_groupBounds_end(int i) { return dataAt(i+24).xyz; }\nfloat C_groupLowerBoundScale(int i) { return float(dataAt(i+25).x); }\nfloat C_groupSmoothness(int i) { return float(dataAt(i+26).x); }\nfloat C_maxRadius(int i) { return float(dataAt(i+27).x); }\nfloat C_localSmoothness(int i) { return float(dataAt(i+28).x); }\n#define C_STRIDE 29\nvec3 M_center(int i) { return dataAt(i+0).xyz; }\nvec3 M_visualBounds_start(int i) { return dataAt(i+1).xyz; }\nvec3 M_visualBounds_end(int i) { return dataAt(i+2).xyz; }\nvec3 M_visualJawPivot(int i) { return dataAt(i+3).xyz; }\nfloat M_visualJawAngle(int i) { return float(dataAt(i+4).x); }\nfloat M_visualJawScale(int i) { return float(dataAt(i+5).x); }\nfloat M_visualJawBoundRadius(int i) { return float(dataAt(i+6).x); }\nmat3 M_inverseRotation(int i) { return transpose(mat3(dataAt(i+7).xyz,dataAt(i+8).xyz,dataAt(i+9).xyz)); }\nvec3 M_muzzleCenterLocal(int i) { return dataAt(i+10).xyz; }\nvec3 M_muzzleHalfExtents(int i) { return dataAt(i+11).xyz; }\nfloat M_muzzleSmoothness(int i) { return float(dataAt(i+12).x); }\nfloat M_cephalicDevelopment(int i) { return float(dataAt(i+13).x); }\nvec3 M_skinColor(int i) { return dataAt(i+14).xyz; }\nvec3 M_entranceCenterLocal(int i) { return dataAt(i+15).xyz; }\nvec3 M_entranceHalfExtents(int i) { return dataAt(i+16).xyz; }\nvec3 M_cavityCenterLocal(int i) { return dataAt(i+17).xyz; }\nvec3 M_cavityRadii(int i) { return dataAt(i+18).xyz; }\nvec3 M_insideColor(int i) { return dataAt(i+19).xyz; }\nfloat M_entranceToCavitySmoothness(int i) { return float(dataAt(i+20).x); }\nfloat M_rimBevel(int i) { return float(dataAt(i+21).x); }\nv",
"ec3 M_jawCenterLocal(int i) { return dataAt(i+22).xyz; }\nvec3 M_jawRadii(int i) { return dataAt(i+23).xyz; }\nvec3 M_hingeCenterLocal(int i) { return dataAt(i+24).xyz; }\nfloat M_hingeRadius(int i) { return float(dataAt(i+25).x); }\nfloat M_throatRadius(int i) { return float(dataAt(i+26).x); }\nfloat M_jawRearMass(int i) { return float(dataAt(i+27).x); }\nfloat M_jawMuscle(int i) { return float(dataAt(i+28).x); }\nbool M_lowerBeak(int i) { return bool(dataAt(i+29).x); }\nvec3 M_hostCenterLocal(int i) { return dataAt(i+30).xyz; }\nvec3 M_hostRadii(int i) { return dataAt(i+31).xyz; }\nvec3 M_craniumCenterLocal(int i) { return dataAt(i+32).xyz; }\nvec3 M_craniumRadii(int i) { return dataAt(i+33).xyz; }\nvec3 M_snoutCenterLocal(int i) { return dataAt(i+34).xyz; }\nvec3 M_snoutRadii(int i) { return dataAt(i+35).xyz; }\nvec3 M_cheekCenterLocal(int i) { return dataAt(i+36).xyz; }\nvec3 M_cheekRadii(int i) { return dataAt(i+37).xyz; }\nvec3 M_leftTemporalCenterLocal(int i) { return dataAt(i+38).xyz; }\nvec3 M_rightTemporalCenterLocal(int i) { return dataAt(i+39).xyz; }\nvec3 M_temporalRadii(int i) { return dataAt(i+40).xyz; }\nvec3 M_leftMaxillaryCenterLocal(int i) { return dataAt(i+41).xyz; }\nvec3 M_rightMaxillaryCenterLocal(int i) { return dataAt(i+42).xyz; }\nvec3 M_maxillaryRadii(int i) { return dataAt(i+43).xyz; }\nvec3 M_leftBrowCenterLocal(int i) { return dataAt(i+44).xyz; }\nvec3 M_rightBrowCenterLocal(int i) { return dataAt(i+45).xyz; }\nvec3 M_browRadii(int i) { return dataAt(i+46).xyz; }\nbool M_sweptSkull(int i) { return bool(dataAt(i+47).x); }\nint M_headStations(int i) { return i+48; }\nbool M_anatomicalHead(int i) { return bool(dataAt(i+60).x); }\nvec3 M_faceRootLocal(int i) { return dataAt(i+61).xyz; }\nvec3 M_faceMidLocal(int i) { return dataAt(i+62).xyz; }\nvec3 M_faceTipLocal(int i) { return dataAt(i+63).xyz; }\nvec3 M_faceRootRadii(int i) { return dataAt(i+64).xyz; }\nvec3 M_faceMidRadii(int i) { return dataAt(i+65).xyz; }\nvec3 M_faceTipRadii(int i) { return dataAt(i+66).xyz; }\nvec3 ",
"M_leftOrbitCenterLocal(int i) { return dataAt(i+67).xyz; }\nvec3 M_rightOrbitCenterLocal(int i) { return dataAt(i+68).xyz; }\nvec3 M_orbitRadii(int i) { return dataAt(i+69).xyz; }\nvec3 M_leftOrbitRimCenterLocal(int i) { return dataAt(i+70).xyz; }\nvec3 M_rightOrbitRimCenterLocal(int i) { return dataAt(i+71).xyz; }\nvec3 M_orbitRimRadii(int i) { return dataAt(i+72).xyz; }\nvec3 M_leftOrbitNormal(int i) { return dataAt(i+73).xyz; }\nvec3 M_rightOrbitNormal(int i) { return dataAt(i+74).xyz; }\nfloat M_orbitSocketDepth(int i) { return float(dataAt(i+75).x); }\nvec3 M_noseCenterLocal(int i) { return dataAt(i+76).xyz; }\nvec3 M_noseRadii(int i) { return dataAt(i+77).xyz; }\nvec3 M_leftNostrilCenterLocal(int i) { return dataAt(i+78).xyz; }\nvec3 M_rightNostrilCenterLocal(int i) { return dataAt(i+79).xyz; }\nvec3 M_nostrilRadii(int i) { return dataAt(i+80).xyz; }\nvec3 M_leftTympanumCenterLocal(int i) { return dataAt(i+81).xyz; }\nvec3 M_rightTympanumCenterLocal(int i) { return dataAt(i+82).xyz; }\nvec3 M_tympanumRadii(int i) { return dataAt(i+83).xyz; }\nfloat M_tympanumDepth(int i) { return float(dataAt(i+84).x); }\nvec3 M_leftEarCenterLocal(int i) { return dataAt(i+85).xyz; }\nvec3 M_rightEarCenterLocal(int i) { return dataAt(i+86).xyz; }\nvec3 M_earRadii(int i) { return dataAt(i+87).xyz; }\nfloat M_headUnionSmoothness(int i) { return float(dataAt(i+88).x); }\nfloat M_headBodySmoothness(int i) { return float(dataAt(i+89).x); }\nvec3 M_neckCollarRootLocal(int i) { return dataAt(i+90).xyz; }\nvec3 M_neckCollarTipLocal(int i) { return dataAt(i+91).xyz; }\nvec3 M_neckCollarRootRadii(int i) { return dataAt(i+92).xyz; }\nvec3 M_neckCollarTipRadii(int i) { return dataAt(i+93).xyz; }\nbool M_hasNasalPad(int i) { return bool(dataAt(i+94).x); }\nbool M_hasEars(int i) { return bool(dataAt(i+95).x); }\nbool M_hasTympana(int i) { return bool(dataAt(i+96).x); }\nbool M_taperedMandible(int i) { return bool(dataAt(i+97).x); }\nfloat M_faceRounding(int i) { return float(dataAt(i+98).x); }\nvec3 M_influenceBounds_start",
"(int i) { return dataAt(i+99).xyz; }\nvec3 M_influenceBounds_end(int i) { return dataAt(i+100).xyz; }\nvec3 M_headBounds_start(int i) { return dataAt(i+101).xyz; }\nvec3 M_headBounds_end(int i) { return dataAt(i+102).xyz; }\nvec3 M_seamSkullLeftLocal(int i) { return dataAt(i+103).xyz; }\nvec3 M_seamSkullRightLocal(int i) { return dataAt(i+104).xyz; }\nvec3 M_seamJawLeftClosedLocal(int i) { return dataAt(i+105).xyz; }\nvec3 M_seamJawRightClosedLocal(int i) { return dataAt(i+106).xyz; }\nvec3 M_seamGularLocal(int i) { return dataAt(i+107).xyz; }\nvec3 M_seamJawAnchorLocal(int i) { return dataAt(i+108).xyz; }\nfloat M_seamScale(int i) { return float(dataAt(i+109).x); }\nvec3 M_seamBounds_start(int i) { return dataAt(i+110).xyz; }\nvec3 M_seamBounds_end(int i) { return dataAt(i+111).xyz; }\n#define M_STRIDE 112\nfloat SDF_SmoothUnion(float a,float b,float k);\nfloat SDF_Sphere(Vector3 point, float radius) {\n    if (radius <= 0.0001) return Vec3_Length(point);\n    return Vec3_Length(point) - radius;\n}\nfloat SDF_Ellipsoid(Vector3 p, Vector3 r) {\n    \n    float rx = Math_Max(r.x, 0.0001);\n    float ry = Math_Max(r.y, 0.0001);\n    float rz = Math_Max(r.z, 0.0001);\n\n    Vector3 invR = Vec3_Create(1.0 / rx, 1.0 / ry, 1.0 / rz);\n    Vector3 invR2 = Vec3_Create(invR.x * invR.x, invR.y * invR.y, invR.z * invR.z);\n\n    Vector3 scaledP = Vec3_Create(p.x * invR.x, p.y * invR.y, p.z * invR.z);\n    float k0 = Vec3_Length(scaledP);\n\n    Vector3 scaledP2 = Vec3_Create(p.x * invR2.x, p.y * invR2.y, p.z * invR2.z);\n    float k1 = Vec3_Length(scaledP2);\n\n    if (k0 < 1e-6 || k1 < 1e-6) {\n        float minR = Math_Min(rx, Math_Min(ry, rz));\n        return -minR;\n    }\n    return k0 * (k0 - 1.0) / k1;\n}\nfloat SDF_Capsule(Vector3 p, Vector3 a, Vector3 b, float radius) {\n    float r = Math_Max(radius, 0.0001);\n    Vector3 pa = Vec3_Sub(p, a);\n    Vector3 ba = Vec3_Sub(b, a);\n\n    float baLengthSq = Vec3_Dot(ba, ba);\n    if (baLengthSq < 1e-8) {\n        return Vec3_Length(pa) - r;\n    }\n\n    float h = Math_C",
"lamp01(Vec3_Dot(pa, ba) / baLengthSq);\n    Vector3 projection = Vec3_Sub(pa, Vec3_Scale(ba, h));\n    return Vec3_Length(projection) - r;\n}\nfloat SDF_TaperedCapsuleApprox(Vector3 p, Vector3 a, Vector3 b, float r1, float r2) {\n    r1 = Math_Max(r1, 0.0001);\n    r2 = Math_Max(r2, 0.0001);\n\n    Vector3 pa = Vec3_Sub(p, a);\n    Vector3 ba = Vec3_Sub(b, a);\n\n    float baLengthSq = Vec3_Dot(ba, ba);\n    if (baLengthSq < 1e-8) {\n        return Vec3_Length(pa) - r1;\n    }\n\n    float h = Math_Clamp01(Vec3_Dot(pa, ba) / baLengthSq);\n    float r = Math_Lerp(r1, r2, h);\n    Vector3 projection = Vec3_Sub(pa, Vec3_Scale(ba, h));\n    return Vec3_Length(projection) - r;\n}\nfloat SDF_TaperedEllipticalCapsuleApprox(Vector3 p, Vector3 a, Vector3 b, Vector3 ra, Vector3 rb) {\n    Vector3 ba=Vec3_Sub(b,a); float lengthSquared=Vec3_Dot(ba,ba);\n    float t=lengthSquared>1e-8?Math_Clamp01(Vec3_Dot(Vec3_Sub(p,a),ba)/lengthSquared):0.0;\n    Vector3 center=Vec3_Lerp(a,b,t);\n    Vector3 radii=Vec3_Lerp(ra,rb,t);\n    float body=SDF_Ellipsoid(Vec3_Sub(p,center),radii);\n    float capA=SDF_Ellipsoid(Vec3_Sub(p,a),ra);\n    float capB=SDF_Ellipsoid(Vec3_Sub(p,b),rb);\n    return Math_Min(body,Math_Min(capA,capB));\n}\nfloat SDF_ThreeSectionEllipticalLoftApprox(Vector3 p,\n                                           Vector3 root, Vector3 mid, Vector3 tip,\n                                           Vector3 rootRadii, Vector3 midRadii,\n                                           Vector3 tipRadii, float blend) {\n    float rear = SDF_TaperedEllipticalCapsuleApprox(p, root, mid, rootRadii, midRadii);\n    float front = SDF_TaperedEllipticalCapsuleApprox(p, mid, tip, midRadii, tipRadii);\n    float k = Math_Max(blend, 0.0);\n    if (k <= 0.0001) return Math_Min(rear, front);\n    float h = Math_Clamp01(0.5 + 0.5 * (front - rear) / k);\n    return Math_Lerp(front, rear, h) - k * h * (1.0 - h);\n}\nfloat SDF_TaperedEllipticalSegmentApprox(Vector3 p, Vector3 a, Vector3 b,\n                                         float widthA",
", float heightA,\n                                         float widthB, float heightB) {\n    Vector3 axis = Vec3_Sub(b, a);\n    float length = Vec3_Length(axis);\n    if (length < 1e-6) return SDF_Ellipsoid(Vec3_Sub(p, a),\n        Vec3_Create(Math_Max(widthA, .0001), Math_Max(heightA, .0001), Math_Max(widthA, .0001)));\n    Vector3 forward = Vec3_Scale(axis, 1.0 / length);\n    Vector3 referenceUp = fabsf(forward.y) > .94 ? Vec3_Create(1,0,0) : Vec3_Create(0,1,0);\n    Vector3 side = Vec3_Normalize(Vec3_Cross(referenceUp, forward));\n    Vector3 up = Vec3_Normalize(Vec3_Cross(forward, side));\n    Vector3 pa = Vec3_Sub(p, a);\n    float along = Vec3_Dot(pa, forward);\n    float t = Math_Clamp01(along / length);\n    float width = Math_Max(Math_Lerp(widthA, widthB, t), .0001);\n    float height = Math_Max(Math_Lerp(heightA, heightB, t), .0001);\n    float cap = Math_Min(width, height);\n    float outsideAxis = along < 0.0 ? along : (along > length ? along - length : 0.0);\n    Vector3 center = Vec3_Add(a, Vec3_Scale(forward, Math_Clamp(along, 0.0, length)));\n    Vector3 radial = Vec3_Sub(p, center);\n    float sx = Vec3_Dot(radial, side) / width;\n    float sy = Vec3_Dot(radial, up) / height;\n    float sz = outsideAxis / cap;\n    return (sqrtf(sx*sx + sy*sy + sz*sz) - 1.0) * Math_Min(width, height);\n}\nfloat SDF_RoundedSlotExtruded(Vector3 p, float halfWidth, float halfHeight, float halfDepth) {\n    float hw = Math_Max(halfWidth, 0.0001);\n    float hh = Math_Max(halfHeight, 0.0001);\n    float hd = Math_Max(halfDepth, 0.0001);\n\n    float radius = hh;\n    float straightHalf = Math_Max(hw - radius, 0.0);\n\n    float qx = Math_Max(fabsf(p.x) - straightHalf, 0.0);\n    float profileDist = sqrtf(qx * qx + p.y * p.y) - radius;\n    float depthDist = fabsf(p.z) - hd;\n\n    float maxP = Math_Max(profileDist, 0.0);\n    float maxD = Math_Max(depthDist, 0.0);\n    float outside = sqrtf(maxP * maxP + maxD * maxD);\n    float inside = Math_Min(Math_Max(profileDist, depthDist), 0.0);\n\n    return outside",
" + inside;\n}\nfloat SDF_Hermite(float a,float b,float da,float db,float h,float t) {\n    float t2=t*t,t3=t2*t;\n    return (2*t3-3*t2+1)*a+(t3-2*t2+t)*h*da+(-2*t3+3*t2)*b+(t3-t2)*h*db;\n}\nfloat SDF_SmoothUnion(float a, float b, float k) {\n    if (k <= 0.0001) return Math_Min(a, b);\n    float h = Math_Clamp01(0.5 + 0.5 * (b - a) / k);\n    return Math_Lerp(b, a, h) - k * h * (1.0 - h);\n}\nfloat SDF_SmoothSubtract(float body, float cutter, float k) {\n    if (k <= 0.0001) return Math_Max(body, -cutter);\n    float h = Math_Clamp01(0.5 - 0.5 * (body + cutter) / k);\n    return Math_Lerp(body, -cutter, h) + k * h * (1.0 - h);\n}float SDF_EllipticalSweepZ(vec3 p,int base,int count) {\n    int i=0;\n    while(i<count-2 && p.z<dataAt(base+2*(i+1)).z) ++i;\n    vec4 a=dataAt(base+2*i), b=dataAt(base+2*(i+1));\n    vec4 ar=dataAt(base+2*i+1), br=dataAt(base+2*(i+1)+1);\n    float h=b.z-a.z,t=clamp((p.z-a.z)/h,0.0,1.0);\n    float w=max(SDF_Hermite(a.w,b.w,ar.y,br.y,h,t),.0001);\n    float v=max(SDF_Hermite(ar.x,br.x,ar.z,br.z,h,t),.0001);\n    float y=SDF_Hermite(a.y,b.y,ar.w,br.w,h,t),x=mix(a.x,b.x,t);\n    float first=dataAt(base).z,last=dataAt(base+2*(count-1)).z;\n    float z=p.z>first?p.z-first:p.z<last?p.z-last:0.0;\n    float r=min(w,v);\n    return (length(vec3((p.x-x)/w,(p.y-y)/v,z/r))-1.0)*r;\n}\nvoid MonsterSDF_GetBasinParams(int mouth, out Vector3 outCenter, out Vector3 outRadii, out float outK) {\n    float h = M_seamScale(mouth);\n    if (h < 1e-4) h = Math_Max(M_hingeRadius(mouth), Math_Max(M_throatRadius(mouth), M_entranceHalfExtents(mouth).y * 2.0));\n    float rx = M_jawRadii(mouth).x;\n    float ry = M_jawRadii(mouth).y;\n    float rz = M_jawRadii(mouth).z;\n    float basinHalfY = h * 0.28;\n    float jawTop = M_jawCenterLocal(mouth).y + ry;\n    float basinTop = jawTop + h * 0.30;\n    float cy = basinTop - basinHalfY;\n    Vector3 center = Vec3_Create(M_jawCenterLocal(mouth).x, cy, M_jawCenterLocal(mouth).z + rz * 0.05);\n    Vector3 radii = Vec3_Create(rx * 0.60, basinHalfY, rz * 0.68);",
"\n    float minWallX = h * 0.22;\n    if (rx - radii.x < minWallX) radii.x = Math_Max(rx - minWallX, rx * 0.45);\n    float minWallZ = h * 0.18;\n    if (rz - radii.z < minWallZ) radii.z = Math_Max(rz - minWallZ, rz * 0.50);\n    float k = h * 0.18;\n    if (k < 0.010) k = 0.010;\n    if (k > h * 0.28) k = h * 0.28;\n    outCenter = center;\n    outRadii = radii;\n    outK = k;\n}\nfloat MonsterSDF_EvalJawBase(int mouth, Vector3 localP) {\n    if(M_lowerBeak(mouth)) {\n        Vector3 root=Vec3_Add(M_hingeCenterLocal(mouth),Vec3_Create(0,-M_jawRadii(mouth).y*.12,M_jawRadii(mouth).z*.08));\n        Vector3 tip=Vec3_Create(M_jawCenterLocal(mouth).x,M_jawCenterLocal(mouth).y,M_jawCenterLocal(mouth).z+M_jawRadii(mouth).z);\n        Vector3 rootRadii=Vec3_Create(M_jawRadii(mouth).x,M_jawRadii(mouth).y,M_jawRadii(mouth).x*.42);\n        Vector3 tipRadii=Vec3_Create(M_jawRadii(mouth).x*.20,M_jawRadii(mouth).y*.28,M_jawRadii(mouth).x*.18);\n        return SDF_TaperedEllipticalCapsuleApprox(localP,root,tip,rootRadii,tipRadii);\n    }\n    if(M_taperedMandible(mouth)) {\n        float rx=M_jawRadii(mouth).x,ry=M_jawRadii(mouth).y,rz=M_jawRadii(mouth).z;\n        Vector3 leftRear=Vec3_Add(M_hingeCenterLocal(mouth),Vec3_Create(rx*.76,-ry*.18,0));\n        Vector3 rightRear=leftRear;rightRear.x*=-1;\n        Vector3 leftTip=Vec3_Create(rx*.08,M_jawCenterLocal(mouth).y+ry*.64,M_jawCenterLocal(mouth).z+rz*.96);\n        Vector3 rightTip=leftTip;rightTip.x*=-1;\n        float rearW=Math_Max(M_jawRearMass(mouth)*.62,rx*.15),tipW=Math_Max(rearW*.58,rx*.055);\n        float left=SDF_TaperedEllipticalSegmentApprox(localP,leftRear,leftTip,rearW,ry*.72,tipW,ry*.34);\n        float right=SDF_TaperedEllipticalSegmentApprox(localP,rightRear,rightTip,rearW,ry*.72,tipW,ry*.34);\n        float bridge=SDF_TaperedEllipticalSegmentApprox(localP,leftTip,rightTip,tipW,ry*.46,tipW,ry*.46);\n        Vector3 rearRadii=Vec3_Create(rearW*1.25,ry*.82,rearW*1.10);\n        float rearLeft=SDF_Ellipsoid(Vec3_Sub(localP,leftRear),rearRadi",
"i);\n        float rearRight=SDF_Ellipsoid(Vec3_Sub(localP,rightRear),rearRadii);\n        float k=Math_Max(M_seamScale(mouth)*.10,.006);\n        float result=SDF_SmoothUnion(left,right,k);result=SDF_SmoothUnion(result,bridge,k);\n        result=SDF_SmoothUnion(result,rearLeft,k);result=SDF_SmoothUnion(result,rearRight,k);\n        \n        Vector3 floorRear=Vec3_Create(0,leftRear.y-ry*.18,leftRear.z);\n        Vector3 floorTip=Vec3_Create(0,leftTip.y-ry*.10,leftTip.z);\n        float floor=SDF_TaperedEllipticalSegmentApprox(localP,floorRear,floorTip,\n            rx*.70,ry*.40,tipW,ry*.32);\n        return SDF_SmoothUnion(result,floor,k);\n    }\n    \n    Vector3 dMain = Vec3_Sub(localP, M_jawCenterLocal(mouth));\n    Vector3 radiiMain = Vec3_Create(M_jawRadii(mouth).x, M_jawRadii(mouth).y, M_jawRadii(mouth).z * 0.96);\n    float main = SDF_Ellipsoid(dMain, radiiMain);\n    Vector3 rearCenter = Vec3_Add(M_hingeCenterLocal(mouth), Vec3_Create(0.0, -M_jawRadii(mouth).y * 0.14, M_jawRadii(mouth).z * 0.22));\n    float rearR = M_jawRearMass(mouth);\n    // elipsoide posterior scale-relative\n    Vector3 rearRadii = Vec3_Create(rearR * 0.95, rearR * 0.85, rearR * 0.92);\n    float rear = SDF_Ellipsoid(Vec3_Sub(localP, rearCenter), rearRadii);\n    Vector3 muscleCenter = Vec3_Add(M_jawCenterLocal(mouth), Vec3_Create(0.0, -M_jawMuscle(mouth) * 0.38, -M_jawRadii(mouth).z * 0.10));\n    Vector3 muscleRadii = Vec3_Create(M_jawRadii(mouth).x * 0.84 + M_jawMuscle(mouth) * 0.12, M_jawMuscle(mouth) * 0.52, M_jawRadii(mouth).z * 0.42);\n    float muscle = SDF_Ellipsoid(Vec3_Sub(localP, muscleCenter), muscleRadii);\n    float h = M_seamScale(mouth); if (h < 1e-4) h = M_hingeRadius(mouth);\n    float k = h * 0.18; if (k < 0.012) k = 0.012; if (k > h * 0.32) k = h * 0.32;\n    float result = SDF_SmoothUnion(main, rear, k);\n    result = SDF_SmoothUnion(result, muscle, k);\n    return result;\n}\nfloat MonsterSDF_EvalSeamDistance(int mouth, Vector3 localP) {\n    float h = M_seamScale(mouth);\n    if (h < 1e-4) ",
"h = Math_Max(M_hingeRadius(mouth), Math_Max(M_throatRadius(mouth), M_entranceHalfExtents(mouth).y * 2.0));\n    float k = h * 0.26; if (k < 0.012) k = 0.012; if (k > h*0.38) k = h*0.38;\n    float rHinge = h * 0.26;\n    float rGular = h * 0.30;\n    float rPivotGular = h * 0.28;\n    float left = SDF_Capsule(localP, M_seamSkullLeftLocal(mouth), M_seamJawLeftClosedLocal(mouth), rHinge);\n    float right = SDF_Capsule(localP, M_seamSkullRightLocal(mouth), M_seamJawRightClosedLocal(mouth), rHinge);\n    if(M_taperedMandible(mouth)) {\n        \n        Vector3 gHalf=Vec3_Create(h*1.58,h*.62,h*.88);\n        float gular=SDF_Ellipsoid(Vec3_Sub(localP,M_seamGularLocal(mouth)),gHalf);\n        float pivotPad=SDF_Sphere(Vec3_Sub(localP,M_hingeCenterLocal(mouth)),h*.38);\n        float res=SDF_SmoothUnion(left,right,k);\n        res=SDF_SmoothUnion(res,gular,k);\n        return SDF_SmoothUnion(res,pivotPad,k);\n    }\n    float jlG = SDF_Capsule(localP, M_seamJawLeftClosedLocal(mouth), M_seamGularLocal(mouth), rGular);\n    float jrG = SDF_Capsule(localP, M_seamJawRightClosedLocal(mouth), M_seamGularLocal(mouth), rGular);\n    float midG = SDF_Capsule(localP, M_seamJawAnchorLocal(mouth), M_seamGularLocal(mouth), rGular);\n    float pivotG = SDF_Capsule(localP, M_hingeCenterLocal(mouth), M_seamGularLocal(mouth), rPivotGular);\n    Vector3 gHalf = Vec3_Create(h * 0.74, h * 0.68, h * 0.72);\n    float gular = SDF_Ellipsoid(Vec3_Sub(localP, M_seamGularLocal(mouth)), gHalf);\n    float pivotPad = SDF_Sphere(Vec3_Sub(localP, M_hingeCenterLocal(mouth)), h * 0.30);\n    float res = SDF_SmoothUnion(left, right, k);\n    res = SDF_SmoothUnion(res, jlG, k);\n    res = SDF_SmoothUnion(res, jrG, k);\n    res = SDF_SmoothUnion(res, midG, k);\n    res = SDF_SmoothUnion(res, pivotG, k);\n    res = SDF_SmoothUnion(res, gular, k);\n    res = SDF_SmoothUnion(res, pivotPad, k);\n    return res;\n}\nfloat MonsterSDF_EvalJawCarvedDistance(int mouth, Vector3 point) {\n    float body = MonsterSDF_EvalJawBase(mouth, point);\n    \n ",
"   if(M_taperedMandible(mouth))return body;\n    Vector3 basinCenter, basinRadii; float k;\n    MonsterSDF_GetBasinParams(mouth, basinCenter, basinRadii, k);\n    float oral = SDF_Ellipsoid(Vec3_Sub(point, basinCenter), basinRadii);\n    return SDF_SmoothSubtract(body, oral, k);\n}\nfloat MonsterSDF_EvalPosedMouthDistance(int mouth,Vector3 localP) {\n    float scale=M_visualJawScale(mouth);\n    if(scale<.0001)return 1e6;\n    Vector3 pivot=M_visualJawPivot(mouth),rel=Vec3_Sub(localP,pivot);\n    float outside=Vec3_Length(rel)-M_visualJawBoundRadius(mouth);\n    if(outside>0)return Math_Max(outside,.01);\n    float angle=M_visualJawAngle(mouth),c=cosf(angle),s=sinf(angle);\n    Vector3 rest=Vec3_Add(pivot,Vec3_Scale(Vec3_Create(rel.x,c*rel.y+s*rel.z,-s*rel.y+c*rel.z),1.0/scale));\n    float jaw=MonsterSDF_EvalJawCarvedDistance(mouth,rest)*scale;\n    rest=Vec3_Add(pivot,Vec3_Scale(rel,1.0/scale));\n    float h=Math_Max(M_seamScale(mouth),.0001);\n    for(int iteration=0;iteration<6;++iteration) {\n        float skull=Math_Min(Vec3_Distance(rest,M_seamSkullLeftLocal(mouth)),Vec3_Distance(rest,M_seamSkullRightLocal(mouth)));\n        skull=Math_Min(skull,Vec3_Distance(rest,M_seamGularLocal(mouth)));\n        skull=Math_Min(skull,Vec3_Distance(rest,pivot));\n        float lower=Math_Min(Vec3_Distance(rest,M_seamJawLeftClosedLocal(mouth)),Vec3_Distance(rest,M_seamJawRightClosedLocal(mouth)));\n        lower=Math_Min(lower,Vec3_Distance(rest,M_seamJawAnchorLocal(mouth)));\n        float w=Math_Clamp01(skull/(skull+lower+h*1e-6));\n        float a=angle*w*w*(3.0-2.0*w);c=cosf(a);s=sinf(a);\n        rest=Vec3_Add(pivot,Vec3_Scale(Vec3_Create(rel.x,c*rel.y+s*rel.z,-s*rel.y+c*rel.z),1.0/scale));\n    }\n    return Math_Min(jaw,MonsterSDF_EvalSeamDistance(mouth,rest)*scale);\n}\nfloat MonsterSDF_EvalConnectorDistance(int conn, Vector3 point) {\n    if(C_length(conn)<1e-6) return SDF_Ellipsoid(Vec3_Sub(point,C_a(conn)),\n        Vec3_Create(C_widthA(conn),C_heightA(conn),C_widthA(conn)));\n    Vector3 p=Vec3",
"_Sub(point,C_a(conn));\n    float along=Vec3_Dot(p,C_forward(conn)),t=Math_Clamp01(along/C_length(conn));\n    float w=Math_Max(Math_Lerp(C_widthA(conn),C_widthB(conn),t),.0001);\n    float h=Math_Max(Math_Lerp(C_heightA(conn),C_heightB(conn),t),.0001),r=Math_Min(w,h);\n    float x=Vec3_Dot(p,C_side(conn))/w,y=Vec3_Dot(p,C_up(conn))/h;\n    float z=(along<0?along:along>C_length(conn)?along-C_length(conn):0)/r;\n    return (sqrtf(x*x+y*y+z*z)-1)*r;\n}\nfloat MonsterSDF_EvalMuzzleDistance(int mouth, Vector3 localP) {\n    return SDF_Ellipsoid(Vec3_Sub(localP, M_muzzleCenterLocal(mouth)), M_muzzleHalfExtents(mouth));\n}\nfloat MonsterSDF_EvalShallowCutter(Vector3 p,Vector3 center,Vector3 radii,\n                                           Vector3 normal,float depth) {\n    Vector3 rel=Vec3_Sub(p,center);\n    float ellipsoid=SDF_Ellipsoid(rel,radii);\n    float rearPlane=-Vec3_Dot(rel,normal)-Math_Max(depth,.001);\n    return Math_Max(ellipsoid,rearPlane);\n}\nfloat MonsterSDF_EvalOrbitCavities(int mouth,Vector3 p) {\n    if(!M_anatomicalHead(mouth))return 1e6;\n    \n    Vector3 leftCenter=Vec3_Add(M_leftOrbitCenterLocal(mouth),Vec3_Scale(M_leftOrbitNormal(mouth),M_orbitRadii(mouth).x*.18));\n    Vector3 rightCenter=Vec3_Add(M_rightOrbitCenterLocal(mouth),Vec3_Scale(M_rightOrbitNormal(mouth),M_orbitRadii(mouth).x*.18));\n    float left=MonsterSDF_EvalShallowCutter(p,leftCenter,M_orbitRadii(mouth),M_leftOrbitNormal(mouth),M_orbitSocketDepth(mouth));\n    float right=MonsterSDF_EvalShallowCutter(p,rightCenter,M_orbitRadii(mouth),M_rightOrbitNormal(mouth),M_orbitSocketDepth(mouth));\n    return Math_Min(left,right);\n}\nfloat MonsterSDF_EvalNostrilCavities(int mouth,Vector3 p) {\n    if(!M_anatomicalHead(mouth))return 1e6;\n    \n    Vector3 leftNormal=Vec3_Normalize(Vec3_Create(1.0,.78,.12));\n    Vector3 rightNormal=leftNormal;rightNormal.x*=-1.0;\n    float depth=Math_Min(M_nostrilRadii(mouth).x,M_nostrilRadii(mouth).y)*.58;\n    float left=MonsterSDF_EvalShallowCutter(p,M_leftNostrilCenterLocal(mouth",
"),M_nostrilRadii(mouth),leftNormal,depth);\n    float right=MonsterSDF_EvalShallowCutter(p,M_rightNostrilCenterLocal(mouth),M_nostrilRadii(mouth),rightNormal,depth);\n    return Math_Min(left,right);\n}\nfloat MonsterSDF_EvalTympanumCavities(int mouth,Vector3 p) {\n    if(!M_anatomicalHead(mouth)||!M_hasTympana(mouth))return 1e6;\n    float left=MonsterSDF_EvalShallowCutter(p,M_leftTympanumCenterLocal(mouth),M_tympanumRadii(mouth),Vec3_Create(1,0,0),M_tympanumDepth(mouth));\n    float right=MonsterSDF_EvalShallowCutter(p,M_rightTympanumCenterLocal(mouth),M_tympanumRadii(mouth),Vec3_Create(-1,0,0),M_tympanumDepth(mouth));\n    return Math_Min(left,right);\n}\nfloat MonsterSDF_EvalRostrumDistance(int mouth,Vector3 localP) {\n    if(!M_anatomicalHead(mouth))return MonsterSDF_EvalMuzzleDistance(mouth,localP);\n    return SDF_ThreeSectionEllipticalLoftApprox(localP,\n        M_faceRootLocal(mouth),M_faceMidLocal(mouth),M_faceTipLocal(mouth),\n        M_faceRootRadii(mouth),M_faceMidRadii(mouth),M_faceTipRadii(mouth),\n        M_faceRounding(mouth));\n}\nfloat MonsterSDF_EvalPeriorbitalDistance(int mouth,Vector3 localP) {\n    float k=Math_Max(M_headUnionSmoothness(mouth)*.24,.002);\n    float d=SDF_Ellipsoid(Vec3_Sub(localP,M_leftOrbitRimCenterLocal(mouth)),M_orbitRimRadii(mouth));\n    d=SDF_SmoothUnion(d,SDF_Ellipsoid(Vec3_Sub(localP,M_rightOrbitRimCenterLocal(mouth)),M_orbitRimRadii(mouth)),k);\n    d=SDF_SmoothUnion(d,SDF_Ellipsoid(Vec3_Sub(localP,M_leftBrowCenterLocal(mouth)),M_browRadii(mouth)),k);\n    return SDF_SmoothUnion(d,SDF_Ellipsoid(Vec3_Sub(localP,M_rightBrowCenterLocal(mouth)),M_browRadii(mouth)),k);\n}\nfloat MonsterSDF_EvalNeckCollarDistance(int mouth,Vector3 localP) {\n    return SDF_TaperedEllipticalSegmentApprox(localP,\n        M_neckCollarRootLocal(mouth),M_neckCollarTipLocal(mouth),\n        M_neckCollarRootRadii(mouth).x,M_neckCollarRootRadii(mouth).y,\n        M_neckCollarTipRadii(mouth).x,M_neckCollarTipRadii(mouth).y);\n}\nfloat MonsterSDF_EvalUpperHeadDistance(int mouth,",
" Vector3 localP) {\n    if (M_anatomicalHead(mouth)) {\n        float dev = M_cephalicDevelopment(mouth);\n        float k = Math_Max(M_headUnionSmoothness(mouth), .005);\n        float cranium = SDF_Ellipsoid(Vec3_Sub(localP, M_craniumCenterLocal(mouth)), M_craniumRadii(mouth));\n        float d = cranium;\n        if (dev > 0.02) {\n            float face = MonsterSDF_EvalRostrumDistance(mouth, localP);\n            float skull = M_sweptSkull(mouth) ? SDF_EllipticalSweepZ(localP, M_headStations(mouth), 6) : SDF_SmoothUnion(d, face, k);\n            d = Math_Lerp(cranium, skull, Math_Clamp01(dev * 1.35));\n            float featK = k * dev;\n            if (featK > 0.001) {\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_leftTemporalCenterLocal(mouth)), M_temporalRadii(mouth)), featK * .38);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_rightTemporalCenterLocal(mouth)), M_temporalRadii(mouth)), featK * .38);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_leftMaxillaryCenterLocal(mouth)), M_maxillaryRadii(mouth)), featK * .34);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_rightMaxillaryCenterLocal(mouth)), M_maxillaryRadii(mouth)), featK * .34);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_cheekCenterLocal(mouth)), M_cheekRadii(mouth)), featK * .42);\n                Vector3 rightCheek = M_cheekCenterLocal(mouth); rightCheek.x *= -1.0;\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, rightCheek), M_cheekRadii(mouth)), featK * .42);\n                d = SDF_SmoothUnion(d, MonsterSDF_EvalPeriorbitalDistance(mouth, localP), featK * .85);\n            }\n        }\n        d = SDF_SmoothUnion(d, MonsterSDF_EvalNeckCollarDistance(mouth, localP), M_headBodySmoothness(mouth));\n        if (M_hasNasalPad(mouth)) d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_noseCenterLocal(mouth)), M_noseRadii(mouth)), k * .35 * dev);\n        if (M_h",
"asEars(mouth)) {\n            d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_leftEarCenterLocal(mouth)), M_earRadii(mouth)), k * .28 * dev);\n            d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_rightEarCenterLocal(mouth)), M_earRadii(mouth)), k * .28 * dev);\n        }\n        return d;\n    }\n    float d = SDF_Ellipsoid(Vec3_Sub(localP, M_craniumCenterLocal(mouth)), M_craniumRadii(mouth));\n    d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_snoutCenterLocal(mouth)), M_snoutRadii(mouth)), 0.08);\n    d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_cheekCenterLocal(mouth)), M_cheekRadii(mouth)), 0.06);\n    d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, Vec3_Create(-M_cheekCenterLocal(mouth).x, M_cheekCenterLocal(mouth).y, M_cheekCenterLocal(mouth).z)), M_cheekRadii(mouth)), 0.06);\n    return SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_leftBrowCenterLocal(mouth)), M_browRadii(mouth)), 0.05);\n}\n// Trazado del mismo campo compilado que utiliza el mallador CPU.\nuniform vec3 cameraPosition, cameraForward, cameraRight, cameraUp;\nuniform vec3 boundsMin, boundsMax;\nuniform vec2 viewportSize;\nuniform float tanHalfFov, aspectRatio, hitTolerance;\nuniform mat4 viewProjection;\nout vec4 fragmentColor;\n\nbool containsBox(vec3 p,vec3 lo,vec3 hi) {return all(greaterThanEqual(p,lo))&&all(lessThanEqual(p,hi));}\nbool pruneBox(vec3 p,vec3 lo,vec3 hi,float scale,float cutoff) {\n    vec3 d=max(max(lo-p,p-hi),vec3(0));\n    if(cutoff<=0.0)return any(greaterThan(d,vec3(0)));\n    float safe=cutoff/max(scale,.0001);\n    return dot(d,d)>=safe*safe;\n}\nvec4 joinField(vec4 a,vec4 b,float k) {\n    float h=k<=.0001?(a.w<b.w?1.0:0.0):clamp(.5+.5*(b.w-a.w)/k,0.0,1.0);\n    return vec4(mix(b.xyz,a.xyz,h),SDF_SmoothUnion(a.w,b.w,k));\n}\nvec4 cutField(vec4 a,float d,vec3 color,float k) {\n    float h=k<=.0001?(-d>a.w?1.0:0.0):clamp(.5-.5*(a.w+d)/k,0.0,1.0);\n    return vec4(mix(a.xyz,color,h),SDF_SmoothSubtract(a.w,d,k));\n}\nuniform int tileDataBase, tileColumn",
"s, validationMode, validationPointBase;\nint tileOffset, tileCount;\nvec4 scene(vec3 p) {\n    vec4 result=vec4(1,1,1,1e6);\n    if(axialCount>1)result=vec4(connectorCount>0?C_color(connectorBase):vec3(1),SDF_EllipticalSweepZ(p,axialBase,axialCount));\n    for(int i=0;i<partCount;++i) {\n        int b=partBase+i*P_STRIDE;\n        result=joinField(result,vec4(P_color(b),SDF_Ellipsoid(p-P_center(b),P_radii(b))),bodySmoothness);\n    }\n    for(int i=0;i<tileCount;++i) {\n        int c=connectorBase+(tileOffset<0?i:int(dataAt(tileOffset+i/4)[i%4]))*C_STRIDE;\n        if(axialCount>1&&C_kind(c)==0)continue;\n        float k=C_localSmoothness(c);\n        if(pruneBox(p,C_bounds_start(c),C_bounds_end(c),C_distanceLowerBoundScale(c),result.w+k))continue;\n        result=joinField(result,vec4(C_color(c),MonsterSDF_EvalConnectorDistance(c,p)),k);\n    }\n    for(int i=0;i<mouthCount;++i) {\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        if(!M_anatomicalHead(m))result=joinField(result,vec4(M_skinColor(m),MonsterSDF_EvalMuzzleDistance(m,local)),M_muzzleSmoothness(m));\n        result=joinField(result,vec4(M_skinColor(m),MonsterSDF_EvalUpperHeadDistance(m,local)),M_anatomicalHead(m)?M_headBodySmoothness(m):M_muzzleSmoothness(m));\n    }\n    for(int i=0;i<mouthCount;++i) {\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        vec3 ext=M_entranceHalfExtents(m),r=M_hostRadii(m);\n        float entrance=SDF_RoundedSlotExtruded(local-M_entranceCenterLocal(m),ext.x,ext.y,ext.z);\n        float cavity=SDF_Ellipsoid(local-M_cavityCenterLocal(m),M_cavityRadii(m));\n        float cutter=SDF_SmoothUnion(entrance,cavity,M_entranceToCavitySmoothness(m))+(1.0-M_cephalicDevelopment(m))*max(r.x,max(r.y,r.z))*2.0;\n        result=cutField(result,cutter,M_insideColor(m),M_rimBevel(m));\n        if(M_anatomicalHead(m)) {\n            result=cutField(result,MonsterSDF_EvalOrbitCavities(m,local),vec3(24,28,19)/255.0,M_head",
"UnionSmoothness(m)*.06);\n            result=cutField(result,MonsterSDF_EvalNostrilCavities(m,local),vec3(18,20,14)/255.0,M_headUnionSmoothness(m)*.04);\n            if(M_hasTympana(m))result=cutField(result,MonsterSDF_EvalTympanumCavities(m,local),vec3(25,24,16)/255.0,M_headUnionSmoothness(m)*.04);\n        }\n    }\n    for(int i=0;i<mouthCount;++i) {\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        float d=MonsterSDF_EvalPosedMouthDistance(m,local);\n        if(d<result.w)result=vec4(M_skinColor(m),d);\n    }\n    return result;\n}\nfloat sceneDistance(vec3 p) {\n    float result=1e6;\n    if(axialCount>1)result=SDF_EllipticalSweepZ(p,axialBase,axialCount);\n    for(int i=0;i<partCount;++i) {\n        int b=partBase+i*P_STRIDE;\n        result=SDF_SmoothUnion(result,SDF_Ellipsoid(p-P_center(b),P_radii(b)),bodySmoothness);\n    }\n    for(int i=0;i<tileCount;++i) {\n        int c=connectorBase+(tileOffset<0?i:int(dataAt(tileOffset+i/4)[i%4]))*C_STRIDE;\n        if(axialCount>1&&C_kind(c)==0)continue;\n        float k=C_localSmoothness(c);\n        if(pruneBox(p,C_bounds_start(c),C_bounds_end(c),C_distanceLowerBoundScale(c),result+k))continue;\n        result=SDF_SmoothUnion(result,MonsterSDF_EvalConnectorDistance(c,p),k);\n    }\n    for(int i=0;i<mouthCount;++i) {\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        if(!M_anatomicalHead(m))result=SDF_SmoothUnion(result,MonsterSDF_EvalMuzzleDistance(m,local),M_muzzleSmoothness(m));\n        result=SDF_SmoothUnion(result,MonsterSDF_EvalUpperHeadDistance(m,local),M_anatomicalHead(m)?M_headBodySmoothness(m):M_muzzleSmoothness(m));\n    }\n    for(int i=0;i<mouthCount;++i) {\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        vec3 ext=M_entranceHalfExtents(m),r=M_hostRadii(m);\n        float entrance=SDF_RoundedSlotExtruded(local-M_entranceCenterLocal(m),ext.x,ext.y,ext.z);\n        float cavity=SDF_",
"Ellipsoid(local-M_cavityCenterLocal(m),M_cavityRadii(m));\n        float cutter=SDF_SmoothUnion(entrance,cavity,M_entranceToCavitySmoothness(m))+(1.0-M_cephalicDevelopment(m))*max(r.x,max(r.y,r.z))*2.0;\n        result=SDF_SmoothSubtract(result,cutter,M_rimBevel(m));\n        if(M_anatomicalHead(m)) {\n            result=SDF_SmoothSubtract(result,MonsterSDF_EvalOrbitCavities(m,local),M_headUnionSmoothness(m)*.06);\n            result=SDF_SmoothSubtract(result,MonsterSDF_EvalNostrilCavities(m,local),M_headUnionSmoothness(m)*.04);\n            if(M_hasTympana(m))result=SDF_SmoothSubtract(result,MonsterSDF_EvalTympanumCavities(m,local),M_headUnionSmoothness(m)*.04);\n        }\n    }\n    for(int i=0;i<mouthCount;++i) {\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        result=min(result,MonsterSDF_EvalPosedMouthDistance(m,local));\n    }\n    return result;\n}\nvoid main() {\n    if(validationMode!=0) {\n        tileOffset=-1;tileCount=connectorCount;\n        vec3 point=dataAt(validationPointBase+int(gl_FragCoord.x)).xyz;\n        fragmentColor=vec4(sceneDistance(point),0,0,1);gl_FragDepth=0;return;\n    }\n    vec2 uv=(gl_FragCoord.xy/viewportSize)*2.0-1.0;\n    vec3 rd=normalize(cameraForward+cameraRight*(uv.x*aspectRatio*tanHalfFov)+cameraUp*(uv.y*tanHalfFov));\n    vec3 t0=(boundsMin-cameraPosition)/rd,t1=(boundsMax-cameraPosition)/rd;\n    vec3 nearT=min(t0,t1),farT=max(t0,t1);\n    float t=max(max(nearT.x,nearT.y),max(nearT.z,0.0));\n    float end=min(farT.x,min(farT.y,farT.z));\n    if(t>end)discard;\n    int tile=int(gl_FragCoord.y)/16*tileColumns+int(gl_FragCoord.x)/16;\n    vec4 list=dataAt(tileDataBase+tile);tileOffset=int(list.x);tileCount=int(list.y);\n    vec3 p=vec3(0);vec4 sampleValue=vec4(0);bool hit=false;\n    for(int step=0;step<256;++step) {\n        p=cameraPosition+rd*t;sampleValue.w=sceneDistance(p);\n        if(sampleValue.w<hitTolerance){hit=true;break;}\n        t+=max(sampleValue.w*.8,hitTolerance*.35);\n        if(t>end)b",
"reak;\n    }\n    if(!hit)discard;\n    float e=hitTolerance*.65;\n    vec3 n=normalize(vec3(sceneDistance(p+vec3(e,0,0))-sceneDistance(p-vec3(e,0,0)),\n        sceneDistance(p+vec3(0,e,0))-sceneDistance(p-vec3(0,e,0)),\n        sceneDistance(p+vec3(0,0,e))-sceneDistance(p-vec3(0,0,e))));\n    sampleValue=scene(p);\n    vec3 light=normalize(vec3(10,20,15)-p);\n    fragmentColor=vec4(sampleValue.xyz*(.4+max(dot(n,light),0.0)),1);\n    vec4 clip=viewProjection*vec4(p,1);gl_FragDepth=(clip.z/clip.w)*.5+.5;\n}\n",
};
