/* Generado por tools/generate_surface_shader.py; editar shaders/. */
static const char* const surfaceVertexSource[] = {
"#version 330 compatibility\n",
"layout(location=8) in vec3 materialCoord;\n",
"layout(location=9) in vec3 materialNormal;\n",
"layout(location=10) in vec4 surfaceRegion;\n",
"layout(location=11) in float anatomicalMaterial;\n",
"uniform vec4 surfaceRecipe[28];\n",
"out vec3 restCoord, restNormal, viewPosition, viewNormal;\n",
"out vec4 vertexColor, profileA, profileB;\n",
"out float ventral, skinMask;\n",
"void main() {\n",
"    gl_Position=gl_ModelViewProjectionMatrix*gl_Vertex;\n",
"    viewPosition=(gl_ModelViewMatrix*gl_Vertex).xyz;\n",
"    viewNormal=normalize(gl_NormalMatrix*gl_Normal);\n",
"    restCoord=materialCoord; restNormal=materialNormal; vertexColor=gl_Color;\n",
"    int a=clamp(int(surfaceRegion.x+.5),0,9),b=clamp(int(surfaceRegion.y+.5),0,9);\n",
"    float blend=clamp(surfaceRegion.z,0.0,1.0);\n",
"    profileA=mix(surfaceRecipe[8+2*a],surfaceRecipe[8+2*b],blend);\n",
"    profileB=mix(surfaceRecipe[9+2*a],surfaceRecipe[9+2*b],blend);\n",
"    // La mezcla ventral es continua y se calcula en reposo, no en el mundo animado.\n",
"    float trunkA=float(a==3 || a==4),trunkB=float(b==3 || b==4);\n",
"    float belly=surfaceRegion.w*mix(trunkA,trunkB,blend);\n",
"    profileA=mix(profileA,surfaceRecipe[16],belly);\n",
"    profileB=mix(profileB,surfaceRecipe[17],belly);\n",
"    ventral=surfaceRegion.w;\n",
"    skinMask=1.0-step(.5,anatomicalMaterial);\n",
"}\n",
};
static const char* const surfaceFragmentSource[] = {
"#version 330 compatibility\n",
"uniform vec4 surfaceRecipe[28];\n",
"uniform uint pigmentSeed,scaleSeed;\n",
"uniform int surfaceDebug;\n",
"in vec3 restCoord,restNormal,viewPosition,viewNormal;\n",
"in vec4 vertexColor,profileA,profileB;\n",
"in float ventral,skinMask;\n",
"out vec4 fragColor;\n",
"// Hash entero: identidad exacta de 32 bits, sin semillas temporales ni texturas.\n",
"uint SurfaceHash(uint x) {\n",
"    x^=x>>16; x*=0x7feb352du; x^=x>>15; x*=0x846ca68bu; return x^(x>>16);\n",
"}\n",
"vec3 CellHash(ivec2 cell,uint seed) {\n",
"    uint h=SurfaceHash(uint(cell.x)*0x9e3779b9u^uint(cell.y)*0x85ebca6bu^seed);\n",
"    return vec3(h>>8,SurfaceHash(h)>>8,SurfaceHash(h+1u)>>8)*(1.0/16777216.0);\n",
"}\n",
"float PigmentNoise(vec3 p,uint seed) {\n",
"    ivec3 i=ivec3(floor(p)); vec3 f=fract(p); f=f*f*(3.0-2.0*f);\n",
"    float z[2];\n",
"    for(int k=0;k<2;++k) {\n",
"        float a=CellHash(i.xy,seed^uint(i.z+k)).x,b=CellHash(i.xy+ivec2(1,0),seed^uint(i.z+k)).x;\n",
"        float c=CellHash(i.xy+ivec2(0,1),seed^uint(i.z+k)).x,d=CellHash(i.xy+ivec2(1,1),seed^uint(i.z+k)).x;\n",
"        z[k]=mix(mix(a,b,f.x),mix(c,d,f.x),f.y);\n",
"    }\n",
"    return mix(z[0],z[1],f.z);\n",
"}\n",
"\n",
"struct ScaleSample { float height; float edge; float variation; float lod; vec3 gradient; };\n",
"float ScaleInterior(vec2 local,vec2 other,float edgeWidth,float aa) {\n",
"    float border=max(0.0,(length(other)-length(local))*.5);\n",
"    return smoothstep(0.0,edgeWidth+aa,border);\n",
"}\n",
"float ScaleProfile(vec2 local,vec2 other,vec3 rnd,vec4 shape,vec4 relief,float aa) {\n",
"    float inner=ScaleInterior(local,other,relief.z,aa);\n",
"    float angle=(rnd.z-.5)*shape.w*.5;\n",
"    local=mat2(cos(angle),-sin(angle),sin(angle),cos(angle))*local;\n",
"    float radial=clamp(1.0-dot(local*vec2(1.55,1.4),local*vec2(1.55,1.4)),0.0,1.0);\n",
"    float dome=mix(sqrt(max(radial,0.0)),radial*radial,shape.z);\n",
"    float overlap=clamp(.75+local.y*.5,.3,1.0);\n",
"    float keel=exp(-abs(local.x)*16.0)*smoothstep(-.5,0.0,local.y)*(1.0-smoothstep(.15,.55,local.y));\n",
"    return inner*(dome*overlap+relief.w*keel)-(1.0-inner)*relief.y;\n",
"}\n",
"// Celdas alternadas con jitter acotado: domos direccionales, no fisuras de roca.\n",
"ScaleSample ScalePattern(vec2 coord,vec4 shape,vec4 relief,float footprint,uint seed) {\n",
"    float detail=1.0-smoothstep(.18,.65,footprint);\n",
"    ScaleSample s=ScaleSample(0.0,0.0,.5,detail,vec3(0));\n",
"    if(footprint>=.65)return s;\n",
"    ivec2 base=ivec2(floor(coord)); float first=1e8,second=1e8;\n",
"    vec2 local=vec2(0.0),other=vec2(0.0); vec3 rnd=vec3(.5);\n",
"    for(int y=-1;y<=1;++y)for(int x=-1;x<=1;++x) {\n",
"        ivec2 id=base+ivec2(x,y); vec3 random=CellHash(id,seed);\n",
"        vec2 center=vec2(id)+vec2(.5+.25*float((id.y&1)*2-1),.5);\n",
"        center+=(random.xy-.5)*.45*shape.w;\n",
"        vec2 delta=coord-center; float dist=dot(delta,delta);\n",
"        if(dist<first) { second=first; other=local; first=dist; local=delta; rnd=random; }\n",
"        else if(dist<second) { second=dist; other=delta; }\n",
"    }\n",
"    float aa=max(.008,footprint*.5);\n",
"    s.height=ScaleProfile(local,other,rnd,shape,relief,aa)*detail;\n",
"    s.edge=(1.0-ScaleInterior(local,other,relief.z,aa))*detail;\n",
"    s.variation=mix(.5,rnd.z,detail*detail);\n",
"    // Diferencias locales de perfil: reutilizan las dos celdas, sin repetir hashes\n",
"    // ni b\u00fasqueda. Evitan escalones de normales en bloques de fragmentos 2x2.\n",
"    if(relief.x<=0.0)return s;\n",
"    vec2 ex=vec2(.008,0),ey=ex.yx;\n",
"    s.gradient.xy=vec2(\n",
"        ScaleProfile(local+ex,other+ex,rnd,shape,relief,aa)-ScaleProfile(local-ex,other-ex,rnd,shape,relief,aa),\n",
"        ScaleProfile(local+ey,other+ey,rnd,shape,relief,aa)-ScaleProfile(local-ey,other-ey,rnd,shape,relief,aa))*(detail/.016);\n",
"    return s;\n",
"}\n",
"ScaleSample TriplanarScales(vec3 p,vec3 restN,vec4 shape,vec4 relief,uint seed) {\n",
"    if(shape.x<.001)return ScaleSample(0,0,.5,0,vec3(0));\n",
"    vec3 weights=pow(abs(normalize(restN)),vec3(6.0)); weights/=max(dot(weights,vec3(1)),1e-6);\n",
"    float size=max(shape.x,.004); vec3 q=p/size;\n",
"    float aspect=clamp(shape.y,.15,6.0);\n",
"    vec2 qx=q.zy*vec2(1.0/aspect,1.0),qy=q.xz*vec2(1.0,1.0/aspect),qz=q.xy*vec2(1.0,1.0/aspect);\n",
"    float fx=max(length(dFdx(qx)),length(dFdy(qx))),fy=max(length(dFdx(qy)),length(dFdy(qy))),fz=max(length(dFdx(qz)),length(dFdy(qz)));\n",
"    float footprint=max(fx,max(fy,fz));\n",
"    if(footprint>=.65)return ScaleSample(0,0,.5,0,vec3(0));\n",
"    ScaleSample x=ScaleSample(0,0,.5,0,vec3(0)),y=x,z=x;\n",
"    vec3 selected=vec3(1);\n",
"    if(footprint>=.12) {\n",
"        float weakest=min(weights.x,min(weights.y,weights.z));\n",
"        selected=step(vec3(weakest+.00001),weights);\n",
"    }\n",
"    if(footprint>=.42) {\n",
"        float strongest=max(weights.x,max(weights.y,weights.z));\n",
"        selected=step(vec3(strongest-.00001),weights);\n",
"    }\n",
"    weights*=selected;weights/=max(dot(weights,vec3(1)),1e-6);\n",
"    if(selected.x>.5)x=ScalePattern(qx,shape,relief,fx,seed);\n",
"    if(selected.y>.5)y=ScalePattern(qy,shape,relief,fy,seed);\n",
"    if(selected.z>.5)z=ScalePattern(qz,shape,relief,fz,seed);\n",
"    vec3 gradient=weights.x*vec3(0,x.gradient.y,x.gradient.x/aspect)+\n",
"        weights.y*vec3(y.gradient.x,0,y.gradient.y/aspect)+weights.z*vec3(z.gradient.x,z.gradient.y/aspect,0);\n",
"    return ScaleSample(dot(weights,vec3(x.height,y.height,z.height)),dot(weights,vec3(x.edge,y.edge,z.edge)),\n",
"        dot(weights,vec3(x.variation,y.variation,z.variation)),footprint<.12?0.0:footprint<.42?1.0:2.0,gradient/size);\n",
"}\n",
"\n",
"vec3 EvaluatePigment(vec3 p,float underside,vec4 params,uint seed) {\n",
"    vec3 q=p*params.w;\n",
"    float footprint=max(length(dFdx(q)),length(dFdy(q)));\n",
"    float noise=PigmentNoise(q,seed);\n",
"    float bandWave=.5+.5*sin(q.z*5.0+noise*3.0);\n",
"    float bands=smoothstep(.48,.7,bandWave);\n",
"    float spots=smoothstep(.48,.7,noise);\n",
"    float pattern=mix(spots,bands,surfaceRecipe[6].w);\n",
"    pattern=mix(pattern,.35,smoothstep(.3,1.0,footprint));\n",
"    vec3 color=mix(surfaceRecipe[0].rgb,surfaceRecipe[1].rgb,pattern*params.z);\n",
"    color*=1.0-params.x*(1.0-underside);\n",
"    return mix(color,surfaceRecipe[2].rgb,underside*params.y);\n",
"}\n",
"\n",
"// Gradiente superficial en espacio de vista: no exige UV ni tangentes precalculadas.\n",
"vec3 SurfaceBump(vec3 n,vec3 p,vec3 coord,vec3 heightGradient) {\n",
"    vec3 dx=dFdx(p),dy=dFdy(p);\n",
"    vec3 rx=cross(dy,n),ry=cross(n,dx);\n",
"    float determinant=dot(dx,rx);\n",
"    float scale=sqrt((dot(dx,dx)+dot(dy,dy))/max(dot(dFdx(coord),dFdx(coord))+dot(dFdy(coord),dFdy(coord)),1e-12));\n",
"    vec3 gradient=(dot(heightGradient,dFdx(coord))*rx+dot(heightGradient,dFdy(coord))*ry)*sign(determinant)*scale/max(abs(determinant),1e-10);\n",
"    // Acota pendientes extremas en bordes de tri\u00e1ngulos casi tangentes a la c\u00e1mara.\n",
"    gradient/=max(1.0,length(gradient)/1.5);\n",
"    return normalize(n-gradient);\n",
"}\n",
"\n",
"struct SurfaceResponse { vec3 albedo; vec3 normal; float roughness; float specular; };\n",
"vec3 SurfaceLighting(SurfaceResponse s,vec3 viewPosition) {\n",
"    vec3 light=normalize(vec3(-.45,.75,.8)),view=normalize(-viewPosition);\n",
"    vec3 halfVector=normalize(light+view);\n",
"    float diffuse=max(dot(s.normal,light),0.0);\n",
"    float exponent=mix(160.0,5.0,s.roughness*s.roughness);\n",
"    float spec=pow(max(dot(s.normal,halfVector),0.0),exponent)*s.specular*diffuse;\n",
"    float fill=max(dot(s.normal,normalize(vec3(.7,.2,-.3))),0.0);\n",
"    return s.albedo*(.26+.7*diffuse+.12*fill)+vec3(spec);\n",
"}\n",
"\n",
"// Interfaz de evaluaci\u00f3n com\u00fan para mallas y futuros ray hits con dominio de reposo.\n",
"struct SurfaceInput {\n",
"    vec3 materialCoord,materialNormal,position,normal;\n",
"    vec4 baseColor,profileA,profileB;\n",
"    float ventral,skinMask;\n",
"};\n",
"SurfaceResponse Surface_Evaluate(SurfaceInput surfaceInput,bool skipDetail,out ScaleSample s,out vec3 pigment) {\n",
"    vec3 n=normalize(surfaceInput.normal);\n",
"    vec4 shape=surfaceRecipe[4]; shape.xy*=surfaceInput.profileA.xy;\n",
"    shape.zw=clamp(shape.zw*surfaceInput.profileB.zy,0.0,1.0);\n",
"    vec4 relief=surfaceRecipe[5]; relief.x*=surfaceInput.profileA.z; relief.w*=surfaceInput.profileA.w;\n",
"    float coverage=surfaceRecipe[6].z*clamp(surfaceInput.skinMask,0.0,1.0);\n",
"    // Rechazo barato antes de Voronoi: tejidos orales y piel lisa no buscan celdas.\n",
"    if(coverage<=.0001 || skipDetail)shape.x=.000001;\n",
"    s=TriplanarScales(surfaceInput.materialCoord,surfaceInput.materialNormal,shape,relief,scaleSeed);\n",
"    vec3 detailed=SurfaceBump(n,surfaceInput.position,surfaceInput.materialCoord,s.gradient*relief.x*coverage);\n",
"    pigment=EvaluatePigment(surfaceInput.materialCoord,clamp(surfaceInput.ventral,0.0,1.0),surfaceRecipe[3],pigmentSeed);\n",
"    vec3 albedo=pigment*(1.0+(s.variation*2.0-1.0)*surfaceRecipe[6].y*coverage);\n",
"    albedo*=1.0-s.edge*.12*coverage;\n",
"    albedo=mix(surfaceInput.baseColor.rgb,albedo,clamp(surfaceInput.skinMask,0.0,1.0));\n",
"    float roughness=clamp(surfaceRecipe[6].x*surfaceInput.profileB.x+(s.variation-.5)*.12*coverage,.12,1.0);\n",
"    return SurfaceResponse(albedo,detailed,roughness,.12+(1.0-roughness)*.3);\n",
"}\n",
"\n",
"void main() {\n",
"    vec3 n=normalize(viewNormal); if(!gl_FrontFacing)n=-n;\n",
"    SurfaceInput surfaceInput=SurfaceInput(restCoord,restNormal,viewPosition,n,vertexColor,profileA,profileB,ventral,skinMask);\n",
"    ScaleSample s; vec3 pigment;\n",
"    SurfaceResponse response=Surface_Evaluate(surfaceInput,surfaceDebug==6 || surfaceDebug==7,s,pigment);\n",
"    vec3 detailed=response.normal;\n",
"    vec3 color=SurfaceLighting(response,viewPosition);\n",
"    if(surfaceDebug==1)color=vec3(profileA.x*.4,profileA.y*.35,ventral);\n",
"    if(surfaceDebug==2)color=fract(restCoord);\n",
"    if(surfaceDebug==3)color=vec3(s.variation);\n",
"    if(surfaceDebug==4)color=vec3(s.height*.6+.2);\n",
"    if(surfaceDebug==5)color=vec3(s.edge);\n",
"    if(surfaceDebug==6)color=pigment;\n",
"    if(surfaceDebug==7)color=n*.5+.5;\n",
"    if(surfaceDebug==8)color=detailed*.5+.5;\n",
"    if(surfaceDebug==9)color=vec3(s.lod);\n",
"    fragColor=vec4(color,vertexColor.a);\n",
"}\n",
};
