/* Generado por tools/generate_surface_shader.py; editar shaders/. */
static const char* const surfaceVertexSource[] = {
"#version 330 compatibility\n",
"layout(location=8) in vec3 materialCoord;\n",
"layout(location=9) in vec3 materialNormal;\n",
"layout(location=10) in vec4 surfaceRegion;\n",
"layout(location=11) in float anatomicalMaterial;\n",
"layout(location=12) in vec3 restFlowDirection;\n",
"layout(location=13) in float vertexIntegumentMask;\n",
"\n",
"uniform vec4 surfaceRecipe[46];\n",
"uniform float shellFraction;\n",
"uniform int furPass;\n",
"uniform int shellCount;\n",
"uniform float shellResolution;\n",
"uniform bool regionalShellLOD;\n",
"uniform vec2 shellSamples[32];\n",
"// Hash entero: identidad exacta de 32 bits, sin semillas temporales ni texturas.\n",
"uint SurfaceHash(uint x) {\n",
"    x^=x>>16; x*=0x7feb352du; x^=x>>15; x*=0x846ca68bu; return x^(x>>16);\n",
"}\n",
"vec3 CellHash(ivec2 cell,uint seed) {\n",
"    uint h=SurfaceHash(uint(cell.x)*0x9e3779b9u^uint(cell.y)*0x85ebca6bu^seed);\n",
"    return vec3(h>>8,SurfaceHash(h)>>8,SurfaceHash(h+1u)>>8)*(1.0/16777216.0);\n",
"}\n",
"float PigmentNoise(vec3 p,uint seed) {\n",
"    ivec3 i=ivec3(floor(p)); vec3 f=fract(p); f=f*f*(3.0-2.0*f);\n",
"    float z[2];\n",
"    for(int k=0;k<2;++k) {\n",
"        float a=CellHash(i.xy,seed^uint(i.z+k)).x,b=CellHash(i.xy+ivec2(1,0),seed^uint(i.z+k)).x;\n",
"        float c=CellHash(i.xy+ivec2(0,1),seed^uint(i.z+k)).x,d=CellHash(i.xy+ivec2(1,1),seed^uint(i.z+k)).x;\n",
"        z[k]=mix(mix(a,b,f.x),mix(c,d,f.x),f.y);\n",
"    }\n",
"    return mix(z[0],z[1],f.z);\n",
"}\n",
"\n",
"// Curva com\u00fan a volumen y cintas. Su derivada define la tangente \u00f3ptica.\n",
"vec3 FurCurveOffset(vec3 n,vec3 flow,float len,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    float bend=lay*(1.0-.8*stiff);\n",
"    float side=clump*(rnd-.5)*.35, wave=irregular*(rnd-.5)*.12;\n",
"    return len*(1.0+irregular*(rnd-.5)*.6)*(n*h+flow*bend*h*h+cross(n,flow)*(side*h*h+wave*h*h*(1.0-h)));\n",
"}\n",
"vec3 FurCurveDerivative(vec3 n,vec3 flow,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    return n+flow*(2.0*lay*(1.0-.8*stiff)*h)+cross(n,flow)*(clump*(rnd-.5)*.7*h+irregular*(rnd-.5)*.12*(2.0*h-3.0*h*h));\n",
"}\n",
"\n",
"// Identidad de mech\u00f3n compartida; las representaciones consultan el mismo dominio.\n",
"float FurFieldRandom(vec3 p,vec3 n,uint seed) {\n",
"    vec3 w=pow(abs(normalize(n)),vec3(4));w/=max(dot(w,vec3(1)),.00001);\n",
"    vec3 q=p*180.0;\n",
"    vec2 a=q.yz,b=q.xz,c=q.xy;\n",
"    a+=vec2(sin(a.y*.73+float(seed&255u)),sin(a.x*.67))*.32;\n",
"    uint sb=seed^0x231u,sc=seed^0x732u;\n",
"    b+=vec2(sin(b.y*.73+float(sb&255u)),sin(b.x*.67))*.32;\n",
"    c+=vec2(sin(c.y*.73+float(sc&255u)),sin(c.x*.67))*.32;\n",
"    return dot(vec3(CellHash(ivec2(floor(a)),seed).z,CellHash(ivec2(floor(b)),sb).z,CellHash(ivec2(floor(c)),sc).z),w);\n",
"}\n",
"\n",
"\n",
"out vec3 restCoord, restNormal, viewPosition, viewNormal;\n",
"out vec4 vertexColor, profileA, profileB;\n",
"out float ventral, skinMask;\n",
"out vec3 posedFlowOut,restFlowOut;\n",
"out float shellDelta;\n",
"out float fragShellFraction;\n",
"out float fragIntegumentMask;\n",
"\n",
"vec3 RotateFromTo(vec3 fromDir, vec3 toDir, vec3 v) {\n",
"    vec3 c = cross(fromDir, toDir);\n",
"    float d = dot(fromDir, toDir);\n",
"    if (d < -0.9999) return -v;\n",
"    float k = 1.0 / (1.0 + d);\n",
"    return v + cross(c, v) + cross(c, cross(c, v)) * k;\n",
"}\n",
"\n",
"void main() {\n",
"    restCoord = materialCoord;\n",
"    restNormal = materialNormal;\n",
"    vertexColor = gl_Color;\n",
"    float height=furPass==1?shellSamples[gl_InstanceID].x:0.0;\n",
"    shellDelta=furPass==1?shellSamples[gl_InstanceID].y:0.0;\n",
"    fragShellFraction = height;\n",
"    restFlowOut=restFlowDirection;\n",
"    fragIntegumentMask = vertexIntegumentMask;\n",
"\n",
"    int a = clamp(int(surfaceRegion.x + 0.5), 0, 10);\n",
"    int b = clamp(int(surfaceRegion.y + 0.5), 0, 10);\n",
"    float blend = clamp(surfaceRegion.z, 0.0, 1.0);\n",
"\n",
"    // Filas 12..33: Perfiles regionales (12 = 8 globales + 4 pelaje)\n",
"    profileA = mix(surfaceRecipe[12 + 2 * a], surfaceRecipe[12 + 2 * b], blend);\n",
"    profileB = mix(surfaceRecipe[13 + 2 * a], surfaceRecipe[13 + 2 * b], blend);\n",
"\n",
"    float trunkA = float(a == 3 || a == 4), trunkB = float(b == 3 || b == 4);\n",
"    float belly = surfaceRegion.w * mix(trunkA, trunkB, blend);\n",
"    // Regi\u00f3n 4 (VENTRAL_TRUNK) -> fila 12 + 2*4 = 20\n",
"    profileA = mix(profileA, surfaceRecipe[20], belly);\n",
"    profileB = mix(profileB, surfaceRecipe[21], belly);\n",
"\n",
"    if(furPass==1 && regionalShellLOD) {\n",
"        float localResolution=clamp(shellResolution*profileA.x,4.0,float(shellCount));\n",
"        float low=exp2(floor(log2(localResolution))),high=min(float(shellCount),low*2.0);\n",
"        float t=clamp((localResolution-low)/low,0.0,1.0);\n",
"        float coarse=float(abs(height*low-round(height*low))<.01);\n",
"        float fine=float(abs(height*high-round(height*high))<.01);\n",
"        shellDelta=mix(coarse/low,fine/high,t)*min(1.0,shellResolution/4.0);\n",
"    }\n",
"    ventral = surfaceRegion.w;\n",
"    skinMask = 1.0 - step(0.5, anatomicalMaterial);\n",
"\n",
"    vec3 nGeom = normalize(gl_Normal);\n",
"    vec3 nRest = normalize(materialNormal);\n",
"    vec3 posedFlow = RotateFromTo(nRest, nGeom, restFlowDirection);\n",
"    posedFlow -= nGeom * dot(posedFlow, nGeom);\n",
"    float flen = length(posedFlow);\n",
"    posedFlow = flen > 1e-4 ? posedFlow / flen : vec3(0.0, 0.0, -1.0);\n",
"    posedFlowOut = normalize(gl_NormalMatrix * posedFlow);\n",
"\n",
"    if (furPass == 1 && height > 0.0) {\n",
"        float furLen = surfaceRecipe[8].x * profileA.x * surfaceRecipe[11].z;\n",
"        float lay = surfaceRecipe[8].w * profileA.w;\n",
"        float h = height;\n",
"        vec3 disp = FurCurveOffset(nGeom,posedFlow,furLen,lay,surfaceRecipe[9].x,0.0,0.0,.5,h) * vertexIntegumentMask;\n",
"        vec4 finalVertex = vec4(gl_Vertex.xyz + disp, 1.0);\n",
"        gl_Position = gl_ModelViewProjectionMatrix * finalVertex;\n",
"        viewPosition = (gl_ModelViewMatrix * finalVertex).xyz;\n",
"        viewNormal = normalize(gl_NormalMatrix * nGeom);\n",
"    } else {\n",
"        gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\n",
"        viewPosition = (gl_ModelViewMatrix * gl_Vertex).xyz;\n",
"        viewNormal = normalize(gl_NormalMatrix * gl_Normal);\n",
"    }\n",
"}\n",
};
static const char* const surfaceFragmentSource[] = {
"#version 330 compatibility\n",
"uniform vec4 surfaceRecipe[46];\n",
"uniform uint pigmentSeed,scaleSeed,furSeed;\n",
"uniform int surfaceDebug;\n",
"uniform float shellFraction;\n",
"uniform int furPass;\n",
"uniform int shellCount;\n",
"\n",
"in vec3 restCoord,restNormal,viewPosition,viewNormal;\n",
"in vec4 vertexColor,profileA,profileB;\n",
"in float ventral,skinMask;\n",
"in vec3 posedFlowOut,restFlowOut;\n",
"in float shellDelta;\n",
"uniform float guardVisibility;\n",
"in float fragShellFraction;\n",
"in float fragIntegumentMask;\n",
"\n",
"out vec4 fragColor;\n",
"\n",
"// Hash entero: identidad exacta de 32 bits, sin semillas temporales ni texturas.\n",
"uint SurfaceHash(uint x) {\n",
"    x^=x>>16; x*=0x7feb352du; x^=x>>15; x*=0x846ca68bu; return x^(x>>16);\n",
"}\n",
"vec3 CellHash(ivec2 cell,uint seed) {\n",
"    uint h=SurfaceHash(uint(cell.x)*0x9e3779b9u^uint(cell.y)*0x85ebca6bu^seed);\n",
"    return vec3(h>>8,SurfaceHash(h)>>8,SurfaceHash(h+1u)>>8)*(1.0/16777216.0);\n",
"}\n",
"float PigmentNoise(vec3 p,uint seed) {\n",
"    ivec3 i=ivec3(floor(p)); vec3 f=fract(p); f=f*f*(3.0-2.0*f);\n",
"    float z[2];\n",
"    for(int k=0;k<2;++k) {\n",
"        float a=CellHash(i.xy,seed^uint(i.z+k)).x,b=CellHash(i.xy+ivec2(1,0),seed^uint(i.z+k)).x;\n",
"        float c=CellHash(i.xy+ivec2(0,1),seed^uint(i.z+k)).x,d=CellHash(i.xy+ivec2(1,1),seed^uint(i.z+k)).x;\n",
"        z[k]=mix(mix(a,b,f.x),mix(c,d,f.x),f.y);\n",
"    }\n",
"    return mix(z[0],z[1],f.z);\n",
"}\n",
"\n",
"struct ScaleSample { float height; float edge; float variation; float lod; vec3 gradient; };\n",
"float ScaleInterior(vec2 local,vec2 other,float edgeWidth,float aa) {\n",
"    float border=max(0.0,(length(other)-length(local))*.5);\n",
"    return smoothstep(0.0,edgeWidth+aa,border);\n",
"}\n",
"float ScaleProfile(vec2 local,vec2 other,vec3 rnd,vec4 shape,vec4 relief,float aa) {\n",
"    if(surfaceRecipe[7].y > 0.5) {\n",
"        float border = max(0.0, (length(other) - length(local)) * 0.5);\n",
"        float bevelWidth = max(relief.z * 1.5, 0.04);\n",
"        float bevel = smoothstep(0.0, bevelWidth + aa, border);\n",
"        float plateau = 0.90 + 0.10 * bevel;\n",
"        return bevel * plateau - (1.0 - bevel) * relief.y * 1.8;\n",
"    }\n",
"    float inner=ScaleInterior(local,other,relief.z,aa);\n",
"    float angle=(rnd.z-.5)*shape.w*.5;\n",
"    local=mat2(cos(angle),-sin(angle),sin(angle),cos(angle))*local;\n",
"    float radial=clamp(1.0-dot(local*vec2(1.55,1.4),local*vec2(1.55,1.4)),0.0,1.0);\n",
"    float dome=mix(sqrt(max(radial,0.0)),radial*radial,shape.z);\n",
"    float overlap=clamp(.75+local.y*.5,.3,1.0);\n",
"    float keel=exp(-abs(local.x)*16.0)*smoothstep(-.5,0.0,local.y)*(1.0-smoothstep(.15,.55,local.y));\n",
"    return inner*(dome*overlap+relief.w*keel)-(1.0-inner)*relief.y;\n",
"}\n",
"// Celdas alternadas con jitter acotado: domos direccionales, no fisuras de roca.\n",
"ScaleSample ScalePattern(vec2 coord,vec4 shape,vec4 relief,float footprint,uint seed) {\n",
"    float detail=1.0-smoothstep(.18,.65,footprint);\n",
"    ScaleSample s=ScaleSample(0.0,0.0,.5,detail,vec3(0));\n",
"    if(footprint>=.65)return s;\n",
"    ivec2 base=ivec2(floor(coord)); float first=1e8,second=1e8;\n",
"    vec2 local=vec2(0.0),other=vec2(0.0); vec3 rnd=vec3(.5);\n",
"    for(int y=-1;y<=1;++y)for(int x=-1;x<=1;++x) {\n",
"        ivec2 id=base+ivec2(x,y); vec3 random=CellHash(id,seed);\n",
"        vec2 center=vec2(id)+vec2(.5+.25*float((id.y&1)*2-1),.5);\n",
"        center+=(random.xy-.5)*.45*shape.w;\n",
"        vec2 delta=coord-center; float dist=dot(delta,delta);\n",
"        if(dist<first) { second=first; other=local; first=dist; local=delta; rnd=random; }\n",
"        else if(dist<second) { second=dist; other=delta; }\n",
"    }\n",
"    float aa=max(.008,footprint*.5);\n",
"    s.height=ScaleProfile(local,other,rnd,shape,relief,aa)*detail;\n",
"    s.edge=(1.0-ScaleInterior(local,other,relief.z,aa))*detail;\n",
"    s.variation=mix(.5,rnd.z,detail*detail);\n",
"    // Diferencias locales de perfil: reutilizan las dos celdas, sin repetir hashes\n",
"    // ni b\u00fasqueda. Evitan escalones de normales en bloques de fragmentos 2x2.\n",
"    if(relief.x<=0.0)return s;\n",
"    vec2 ex=vec2(.008,0),ey=ex.yx;\n",
"    s.gradient.xy=vec2(\n",
"        ScaleProfile(local+ex,other+ex,rnd,shape,relief,aa)-ScaleProfile(local-ex,other-ex,rnd,shape,relief,aa),\n",
"        ScaleProfile(local+ey,other+ey,rnd,shape,relief,aa)-ScaleProfile(local-ey,other-ey,rnd,shape,relief,aa))*(detail/.016);\n",
"    return s;\n",
"}\n",
"ScaleSample TriplanarScales(vec3 p,vec3 restN,vec4 shape,vec4 relief,uint seed) {\n",
"    if(shape.x<.001)return ScaleSample(0,0,.5,0,vec3(0));\n",
"    vec3 weights=pow(abs(normalize(restN)),vec3(6.0)); weights/=max(dot(weights,vec3(1)),1e-6);\n",
"    float size=max(shape.x,.004); vec3 q=p/size;\n",
"    float aspect=clamp(shape.y,.15,6.0);\n",
"    vec2 qx=q.zy*vec2(1.0/aspect,1.0),qy=q.xz*vec2(1.0,1.0/aspect),qz=q.xy*vec2(1.0,1.0/aspect);\n",
"    float fx=max(length(dFdx(qx)),length(dFdy(qx))),fy=max(length(dFdx(qy)),length(dFdy(qy))),fz=max(length(dFdx(qz)),length(dFdy(qz)));\n",
"    float footprint=max(fx,max(fy,fz));\n",
"    if(footprint>=.65)return ScaleSample(0,0,.5,0,vec3(0));\n",
"    ScaleSample x=ScaleSample(0,0,.5,0,vec3(0)),y=x,z=x;\n",
"    vec3 selected=vec3(1);\n",
"    if(footprint>=.12) {\n",
"        float weakest=min(weights.x,min(weights.y,weights.z));\n",
"        selected=step(vec3(weakest+.00001),weights);\n",
"    }\n",
"    if(footprint>=.42) {\n",
"        float strongest=max(weights.x,max(weights.y,weights.z));\n",
"        selected=step(vec3(strongest-.00001),weights);\n",
"    }\n",
"    weights*=selected;weights/=max(dot(weights,vec3(1)),1e-6);\n",
"    if(selected.x>.5)x=ScalePattern(qx,shape,relief,fx,seed);\n",
"    if(selected.y>.5)y=ScalePattern(qy,shape,relief,fy,seed);\n",
"    if(selected.z>.5)z=ScalePattern(qz,shape,relief,fz,seed);\n",
"    vec3 gradient=weights.x*vec3(0,x.gradient.y,x.gradient.x/aspect)+\n",
"        weights.y*vec3(y.gradient.x,0,y.gradient.y/aspect)+weights.z*vec3(z.gradient.x,z.gradient.y/aspect,0);\n",
"    return ScaleSample(dot(weights,vec3(x.height,y.height,z.height)),dot(weights,vec3(x.edge,y.edge,z.edge)),\n",
"        dot(weights,vec3(x.variation,y.variation,z.variation)),footprint<.12?0.0:footprint<.42?1.0:2.0,gradient/size);\n",
"}\n",
"\n",
"float SamplePigmentPattern(int pat, vec3 p, float scale, float sharpness, vec3 dir, uint seed) {\n",
"    vec3 q = p * max(scale, 0.01);\n",
"    float sh = clamp(sharpness, 0.0, 1.0);\n",
"    float noise = PigmentNoise(q, seed);\n",
"    if (pat == 0) {\n",
"        return 1.0;\n",
"    } else if (pat == 1) {\n",
"        return noise;\n",
"    } else if (pat == 2) {\n",
"        float w = 0.16 * (1.0 - sh * 0.75);\n",
"        return smoothstep(0.56 - w, 0.56 + w, noise);\n",
"    } else if (pat == 3) {\n",
"        float phase = float(seed & 1023u) * (6.2831853 / 1024.0);\n",
"        float wave = 0.5 + 0.5 * sin(q.z * 4.5 + phase + noise * 2.0);\n",
"        float w = 0.18 * (1.0 - sh * 0.8);\n",
"        return smoothstep(0.50 - w, 0.50 + w, wave);\n",
"    } else if (pat == 4) {\n",
"        float phase = float(seed & 1023u) * (6.2831853 / 1024.0);\n",
"        float wave = 0.5 + 0.5 * sin(q.x * 6.5 + phase + noise * 1.8);\n",
"        float w = 0.16 * (1.0 - sh * 0.8);\n",
"        return smoothstep(0.50 - w, 0.50 + w, wave);\n",
"    } else if (pat == 5) {\n",
"        float n1 = PigmentNoise(q * 0.40, seed);\n",
"        float n2 = PigmentNoise(q * 0.85, seed + 77u);\n",
"        float combined = n1 * 0.70 + n2 * 0.30;\n",
"        float w = 0.15 * (1.0 - sh * 0.8);\n",
"        return smoothstep(0.48 - w, 0.48 + w, combined);\n",
"    } else if (pat == 6) {\n",
"        float ringDist = abs(noise - 0.54);\n",
"        float wRing = 0.10 * (1.0 - sh * 0.6);\n",
"        float ring = 1.0 - smoothstep(0.0, wRing, ringDist);\n",
"        float center = 1.0 - smoothstep(0.0, 0.06, abs(noise - 0.72));\n",
"        return max(ring, center);\n",
"    } else if (pat == 7) {\n",
"        vec3 d = length(dir) > 0.001 ? normalize(dir) : vec3(0.0, -1.0, 0.0);\n",
"        float grad = dot(p, d) * scale;\n",
"        return clamp(grad * 0.5 + 0.5, 0.0, 1.0);\n",
"    }\n",
"    return 0.0;\n",
"}\n",
"\n",
"vec3 EvaluatePigment(vec3 p, float underside, vec4 params, uint seed) {\n",
"    int layerCount = int(surfaceRecipe[7].z + 0.5);\n",
"    vec3 color;\n",
"    if (layerCount <= 0) {\n",
"        vec3 q = p * params.w;\n",
"        float footprint = max(length(dFdx(q)), length(dFdy(q)));\n",
"        float noise = PigmentNoise(q, seed);\n",
"        float bandWave = .5 + .5 * sin(q.z * 5.0 + noise * 3.0);\n",
"        float bands = smoothstep(.48, .7, bandWave);\n",
"        float spots = smoothstep(.48, .7, noise);\n",
"        float pattern = mix(spots, bands, surfaceRecipe[6].w);\n",
"        pattern = mix(pattern, .35, smoothstep(.3, 1.0, footprint));\n",
"        color = mix(surfaceRecipe[0].rgb, surfaceRecipe[1].rgb, pattern * params.z);\n",
"        color *= 1.0 - params.x * (1.0 - underside);\n",
"        return mix(color, surfaceRecipe[2].rgb, underside * params.y);\n",
"    }\n",
"\n",
"    color = surfaceRecipe[0].rgb;\n",
"    for (int i = 0; i < 4; ++i) {\n",
"        if (i >= layerCount) break;\n",
"        vec4 layerCol = surfaceRecipe[30 + 3 * i];\n",
"        vec4 layerParam = surfaceRecipe[31 + 3 * i];\n",
"        vec4 layerDir = surfaceRecipe[32 + 3 * i];\n",
"        uint layerSeed = seed ^ uint(layerParam.w) ^ uint(i * 101);\n",
"        float sampleVal = SamplePigmentPattern(int(layerParam.x + 0.5), p, layerParam.y, layerParam.z, layerDir.xyz, layerSeed);\n",
"        float blend = clamp(sampleVal * layerCol.a, 0.0, 1.0);\n",
"        color = mix(color, layerCol.rgb, blend);\n",
"    }\n",
"    color *= 1.0 - params.x * (1.0 - underside);\n",
"    return mix(color, surfaceRecipe[2].rgb, underside * params.y);\n",
"}\n",
"\n",
"// Curva com\u00fan a volumen y cintas. Su derivada define la tangente \u00f3ptica.\n",
"vec3 FurCurveOffset(vec3 n,vec3 flow,float len,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    float bend=lay*(1.0-.8*stiff);\n",
"    float side=clump*(rnd-.5)*.35, wave=irregular*(rnd-.5)*.12;\n",
"    return len*(1.0+irregular*(rnd-.5)*.6)*(n*h+flow*bend*h*h+cross(n,flow)*(side*h*h+wave*h*h*(1.0-h)));\n",
"}\n",
"vec3 FurCurveDerivative(vec3 n,vec3 flow,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    return n+flow*(2.0*lay*(1.0-.8*stiff)*h)+cross(n,flow)*(clump*(rnd-.5)*.7*h+irregular*(rnd-.5)*.12*(2.0*h-3.0*h*h));\n",
"}\n",
"\n",
"// Identidad de mech\u00f3n compartida; las representaciones consultan el mismo dominio.\n",
"float FurFieldRandom(vec3 p,vec3 n,uint seed) {\n",
"    vec3 w=pow(abs(normalize(n)),vec3(4));w/=max(dot(w,vec3(1)),.00001);\n",
"    vec3 q=p*180.0;\n",
"    vec2 a=q.yz,b=q.xz,c=q.xy;\n",
"    a+=vec2(sin(a.y*.73+float(seed&255u)),sin(a.x*.67))*.32;\n",
"    uint sb=seed^0x231u,sc=seed^0x732u;\n",
"    b+=vec2(sin(b.y*.73+float(sb&255u)),sin(b.x*.67))*.32;\n",
"    c+=vec2(sin(c.y*.73+float(sc&255u)),sin(c.x*.67))*.32;\n",
"    return dot(vec3(CellHash(ivec2(floor(a)),seed).z,CellHash(ivec2(floor(b)),sb).z,CellHash(ivec2(floor(c)),sc).z),w);\n",
"}\n",
"\n",
"struct FurSample { float coverage; float undercoat; float guard; float fiberRandom; vec3 tangent; };\n",
"// Secciones circulares de fol\u00edculos compuestos; filtro de \u00e1rea cuando son subp\u00edxel.\n",
"vec3 FurPlane(vec2 q,vec2 flow,float h,vec4 p0,vec4 p1,vec4 p2,uint seed) {\n",
"    // Una deformaci\u00f3n suave del dominio evita filas regulares sin saltos de plano.\n",
"    q+=vec2(sin(q.y*.73+float(seed&255u)),sin(q.x*.67))* .32;\n",
"    ivec2 cell=ivec2(floor(q));vec3 r=CellHash(cell,seed);\n",
"    vec2 local=fract(q)-.5-(r.xy-.5)*.50;\n",
"    float footprint=max(length(dFdx(q)),length(dFdy(q)));\n",
"    float variation=1.0+p1.z*(r.z-.5)*.6;\n",
"    vec2 lateral=vec2(-flow.y,flow.x);\n",
"    local-=lateral*(p1.y*(r.z-.5)*.35*h*h+p1.z*(r.z-.5)*.12*h*h*(1.0-h))*p0.x*180.0;\n",
"    float aa=max(.008,footprint*.5);\n",
"    float rad=.065*p0.z*max(0.0,1.0-h/variation);\n",
"    float guard=1.0-smoothstep(rad-aa,rad+aa,length(local));\n",
"    float filtered=smoothstep(.3,.9,footprint);\n",
"    guard=mix(guard,3.14159*rad*rad,filtered)*p2.y*(1.0-smoothstep(variation-.05,variation+.05,h));\n",
"    // Sector angular m\u00e1s pr\u00f3ximo: seis secundarios sin bucle ni b\u00fasquedas vecinas.\n",
"    float angle=atan(local.y,local.x)-6.283185*r.x;\n",
"    float sector=floor(angle*(6.0/6.283185)+.5);\n",
"    float theta=sector*(6.283185/6.0)+6.283185*r.x;\n",
"    vec2 center=vec2(cos(theta),sin(theta))*.23*(1.0-p1.y*h);\n",
"    float uh=h/max(.1,p2.x*variation);\n",
"    float radius=.085*p0.z*sqrt(max(0.0,1.0-uh));\n",
"    float under=1.0-smoothstep(radius-aa,radius+aa,length(local-center));\n",
"    under=mix(under,6.0*3.14159*radius*radius,filtered)*p1.w*(1.0-smoothstep(.9,1.05,uh));\n",
"    return vec3(under,guard,r.z);\n",
"}\n",
"FurSample EvaluateFurStrands(vec3 p,vec3 restN,vec3 n,vec3 flow,float h,vec4 p0,vec4 p1,vec4 p2,uint seed) {\n",
"    vec3 w=pow(abs(normalize(restN)),vec3(4));w/=max(dot(w,vec3(1)),.0001);\n",
"    // Mezcla continua: ninguna proyecci\u00f3n ganadora, identidad en reposo.\n",
"    vec3 q=p*180.0;\n",
"    vec3 a=FurPlane(q.yz,normalize(restFlowOut.yz+vec2(.00001)),h,p0,p1,p2,seed);\n",
"    vec3 b=FurPlane(q.xz,normalize(restFlowOut.xz+vec2(.00001)),h,p0,p1,p2,seed^0x231u);\n",
"    vec3 c=FurPlane(q.xy,normalize(restFlowOut.xy+vec2(.00001)),h,p0,p1,p2,seed^0x732u);\n",
"    vec3 f=a*w.x+b*w.y+c*w.z;\n",
"    vec3 tangent=normalize(FurCurveDerivative(n,flow,p0.w,p1.x,p1.y,p1.z,f.z,h));\n",
"    return FurSample(f.x+f.y,f.x,f.y,f.z,tangent);\n",
"}\n",
"vec3 FurLighting(vec3 albedo,vec3 tangent,vec3 normal,vec3 viewPos,float roughness,float sheen,float h) {\n",
"    vec3 L=normalize(vec3(10,20,15)-viewPos),V=normalize(-viewPos),T=normalize(tangent),N=normalize(normal);\n",
"    vec3 H=normalize(L+V);\n",
"    float primary=pow(sqrt(max(0.0,1.0-pow(clamp(dot(T,H)+.08,-1.0,1.0),2.0))),mix(140.0,24.0,roughness));\n",
"    float secondary=pow(sqrt(max(0.0,1.0-pow(clamp(dot(T,H)-.20,-1.0,1.0),2.0))),mix(45.0,10.0,roughness));\n",
"    float diffuse=sqrt(max(0.0,1.0-pow(dot(T,L),2.0)));\n",
"    float shadow=exp(-.28*surfaceRecipe[8].y*(1.0-h)/max(.3,abs(dot(N,L))));\n",
"    float transmission=pow(max(0.0,dot(-L,V)),4.0)*(1.0-abs(dot(T,L)))*.12;\n",
"    return albedo*(.32+.85*diffuse*shadow+transmission)+sheen*(vec3(.7)*primary+albedo*.35*secondary)*shadow;\n",
"}\n",
"\n",
"// Gradiente superficial en espacio de vista: no exige UV ni tangentes precalculadas.\n",
"vec3 SurfaceBump(vec3 n,vec3 p,vec3 coord,vec3 heightGradient) {\n",
"    vec3 dx=dFdx(p),dy=dFdy(p);\n",
"    vec3 rx=cross(dy,n),ry=cross(n,dx);\n",
"    float determinant=dot(dx,rx);\n",
"    float scale=sqrt((dot(dx,dx)+dot(dy,dy))/max(dot(dFdx(coord),dFdx(coord))+dot(dFdy(coord),dFdy(coord)),1e-12));\n",
"    vec3 gradient=(dot(heightGradient,dFdx(coord))*rx+dot(heightGradient,dFdy(coord))*ry)*sign(determinant)*scale/max(abs(determinant),1e-10);\n",
"    // Acota pendientes extremas en bordes de tri\u00e1ngulos casi tangentes a la c\u00e1mara.\n",
"    gradient/=max(1.0,length(gradient)/1.5);\n",
"    return normalize(n-gradient);\n",
"}\n",
"\n",
"struct SurfaceResponse { vec3 albedo; vec3 normal; float roughness; float specular; };\n",
"vec3 SurfaceLighting(SurfaceResponse s,vec3 viewPosition) {\n",
"    vec3 light=normalize(vec3(-.45,.75,.8)),view=normalize(-viewPosition);\n",
"    vec3 halfVector=normalize(light+view);\n",
"    float diffuse=max(dot(s.normal,light),0.0);\n",
"    float exponent=mix(160.0,5.0,s.roughness*s.roughness);\n",
"    float spec=pow(max(dot(s.normal,halfVector),0.0),exponent)*s.specular*diffuse;\n",
"    float fill=max(dot(s.normal,normalize(vec3(.7,.2,-.3))),0.0);\n",
"    return s.albedo*(.26+.7*diffuse+.12*fill)+vec3(spec);\n",
"}\n",
"\n",
"// Interfaz de evaluaci\u00f3n com\u00fan para mallas y futuros ray hits con dominio de reposo.\n",
"struct SurfaceInput {\n",
"    vec3 materialCoord,materialNormal,position,normal;\n",
"    vec4 baseColor,profileA,profileB;\n",
"    float ventral,skinMask;\n",
"};\n",
"SurfaceResponse Surface_Evaluate(SurfaceInput surfaceInput,bool skipDetail,out ScaleSample s,out vec3 pigment) {\n",
"    vec3 n=normalize(surfaceInput.normal);\n",
"    vec4 shape=surfaceRecipe[4]; shape.xy*=surfaceInput.profileA.xy;\n",
"    shape.zw=clamp(shape.zw*surfaceInput.profileB.zy,0.0,1.0);\n",
"    vec4 relief=surfaceRecipe[5]; relief.x*=surfaceInput.profileA.z; relief.w*=surfaceInput.profileA.w;\n",
"    float coverage=surfaceRecipe[6].z*clamp(surfaceInput.skinMask,0.0,1.0);\n",
"    // Rechazo barato antes de Voronoi: tejidos orales y piel lisa no buscan celdas.\n",
"    if(coverage<=.0001 || skipDetail)shape.x=.000001;\n",
"    s=TriplanarScales(surfaceInput.materialCoord,surfaceInput.materialNormal,shape,relief,scaleSeed);\n",
"    vec3 detailed=SurfaceBump(n,surfaceInput.position,surfaceInput.materialCoord,s.gradient*relief.x*coverage);\n",
"    pigment=EvaluatePigment(surfaceInput.materialCoord,clamp(surfaceInput.ventral,0.0,1.0),surfaceRecipe[3],pigmentSeed);\n",
"    vec3 albedo=pigment*(1.0+(s.variation*2.0-1.0)*surfaceRecipe[6].y*coverage);\n",
"    albedo*=1.0-s.edge*.12*coverage;\n",
"    albedo=mix(surfaceInput.baseColor.rgb,albedo,clamp(surfaceInput.skinMask,0.0,1.0));\n",
"    float roughness=clamp(surfaceRecipe[6].x*surfaceInput.profileB.x+(s.variation-.5)*.12*coverage,.12,1.0);\n",
"    return SurfaceResponse(albedo,detailed,roughness,.12+(1.0-roughness)*.3);\n",
"}\n",
"\n",
"\n",
"void main() {\n",
"    vec3 n = normalize(viewNormal);\n",
"    if (!gl_FrontFacing) n = -n;\n",
"\n",
"    int integumentType = int(surfaceRecipe[7].x + 0.5);\n",
"\n",
"    // Ruta de pelaje mam\u00edfero procedural (INTEGUMENT_FUR = 2)\n",
"    if (integumentType == 2) {\n",
"        if(furPass==1 && (shellDelta<=.000001 || fragIntegumentMask<=.001 || skinMask<.5))discard;\n",
"        vec3 pigment = EvaluatePigment(restCoord, clamp(ventral, 0.0, 1.0), surfaceRecipe[3], pigmentSeed);\n",
"\n",
"        if (furPass == 1) {\n",
"            // Pase de conchas exteriores (shell pass)\n",
"            if (fragIntegumentMask <= 0.001 || shellDelta<=.000001 || skinMask<.5) discard;\n",
"\n",
"            FurSample fur = EvaluateFurStrands(\n",
"                restCoord, restNormal, n, posedFlowOut, fragShellFraction,\n",
"                surfaceRecipe[8] * vec4(profileA.x, profileA.y, profileA.z, profileA.w),\n",
"                surfaceRecipe[9] * vec4(1.0, profileB.z, profileB.w, profileB.x),\n",
"                surfaceRecipe[10] * vec4(1.0,profileB.y,1.0,1.0), furSeed);\n",
"\n",
"            float cosine=abs(dot(n,normalize(-viewPosition)));\n",
"            float occupancy=fur.undercoat+fur.guard*(1.0-guardVisibility);\n",
"            float tau=32.0*surfaceRecipe[8].y*profileA.y*occupancy*shellDelta/max(.25,cosine);\n",
"            float furAlpha=(1.0-exp(-tau))*fragIntegumentMask*skinMask*surfaceRecipe[11].w;\n",
"            if(furAlpha<.0001)discard;\n",
"\n",
"            float rootTip = mix(1.0 - surfaceRecipe[11].x, 1.0 + surfaceRecipe[11].y, clamp(fragShellFraction*(.8+.4*fur.fiberRandom),0.0,1.0));\n",
"            float fiberVar = 0.94 + 0.12 * fur.fiberRandom;\n",
"            vec3 albedo = pigment * (rootTip * fiberVar);\n",
"\n",
"            float roughness = clamp(surfaceRecipe[10].z, 0.1, 1.0);\n",
"            float sheen = surfaceRecipe[10].w;\n",
"            vec3 color = FurLighting(albedo, fur.tangent, n, viewPosition, roughness, sheen, fragShellFraction);\n",
"\n",
"            // Modos de depuraci\u00f3n de pelaje\n",
"            if (surfaceDebug == 1) color = vec3(profileA.x * 0.4, profileA.y * 0.35, ventral);\n",
"            if (surfaceDebug == 2) color = fract(restCoord);\n",
"            if (surfaceDebug == 6) color = pigment;\n",
"            if (surfaceDebug == 7) color = n * 0.5 + 0.5;\n",
"            if (surfaceDebug == 11) color = posedFlowOut * 0.5 + 0.5;\n",
"            if (surfaceDebug == 12) color = vec3(fragIntegumentMask);\n",
"            if (surfaceDebug == 13) color = vec3(fur.coverage);\n",
"            if (surfaceDebug == 14) color = vec3(fragShellFraction);\n",
"            if (surfaceDebug == 15) color = vec3(fur.undercoat);\n",
"            if (surfaceDebug == 16) color = vec3(fur.guard);\n",
"            if (surfaceDebug == 17) color = vec3(fur.undercoat, fur.guard, 0.0);\n",
"\n",
"            if(surfaceDebug==18)color=fur.tangent*.5+.5;\n",
"            if(surfaceDebug==19)color=vec3(exp(-tau));\n",
"            if(surfaceDebug==20)color=vec3(float(shellCount)/32.0);\n",
"            if(surfaceDebug==21)color=vec3(guardVisibility);\n",
"            if(surfaceDebug==22)color=vec3(fur.fiberRandom);\n",
"            fragColor = vec4(color * furAlpha * vertexColor.a, furAlpha * vertexColor.a);\n",
"            return;\n",
"        } else {\n",
"            // Capa base de piel con micro-sombreado de pelaje\n",
"            float rootFactor = 1.0 - surfaceRecipe[11].x * 0.35;\n",
"            vec3 albedo = pigment * rootFactor;\n",
"            albedo = mix(vertexColor.rgb, albedo, clamp(skinMask, 0.0, 1.0));\n",
"            // El manto no puede depender \u00fanicamente de las conchas: a media\n",
"            // distancia las fibras son subp\u00edxel. Este grano macrosc\u00f3pico y\n",
"            // filtrado mantiene direcci\u00f3n y variaci\u00f3n sin dibujar ruido.\n",
"            float grainFootprint = max(length(dFdx(restCoord)), length(dFdy(restCoord)));\n",
"            float grain = PigmentNoise(restCoord * 8.0, furSeed ^ 0x4d4943u);\n",
"            grain = mix(grain, 0.5, smoothstep(0.18, 0.70, grainFootprint));\n",
"            albedo *= 0.94 + 0.12 * grain;\n",
"            float furRoughness = clamp(surfaceRecipe[10].z, 0.2, 1.0);\n",
"            float sheen = surfaceRecipe[10].w;\n",
"            vec3 furTangent = normalize(mix(n, posedFlowOut, 0.72));\n",
"            vec3 color = FurLighting(albedo, furTangent, n, viewPosition, furRoughness, sheen * 0.30, 0.0);\n",
"\n",
"            if (surfaceDebug == 1) color = vec3(profileA.x * 0.4, profileA.y * 0.35, ventral);\n",
"            if (surfaceDebug == 2) color = fract(restCoord);\n",
"            if (surfaceDebug == 6) color = pigment;\n",
"            if (surfaceDebug == 7) color = n * 0.5 + 0.5;\n",
"            if (surfaceDebug == 11) color = posedFlowOut * 0.5 + 0.5;\n",
"            if (surfaceDebug == 12) color = vec3(fragIntegumentMask);\n",
"\n",
"            fragColor = vec4(color, vertexColor.a);\n",
"            return;\n",
"        }\n",
"    }\n",
"\n",
"    // Ruta est\u00e1ndar para piel lisa y escamas (INTEGUMENT_SMOOTH_SKIN, INTEGUMENT_SCALES, INTEGUMENT_PLATES)\n",
"    SurfaceInput surfaceInput = SurfaceInput(restCoord, restNormal, viewPosition, n, vertexColor, profileA, profileB, ventral, skinMask);\n",
"    ScaleSample s;\n",
"    vec3 pigment;\n",
"    SurfaceResponse response = Surface_Evaluate(surfaceInput, surfaceDebug == 6 || surfaceDebug == 7, s, pigment);\n",
"    if (surfaceDebug == 10) { response.albedo = vec3(0.57); response.roughness = 0.65; response.specular = 0.12; }\n",
"    vec3 detailed = response.normal;\n",
"    vec3 color = SurfaceLighting(response, viewPosition);\n",
"    if (surfaceDebug == 1) color = vec3(profileA.x * 0.4, profileA.y * 0.35, ventral);\n",
"    if (surfaceDebug == 2) color = fract(restCoord);\n",
"    if (surfaceDebug == 3) color = vec3(s.variation);\n",
"    if (surfaceDebug == 4) color = vec3(s.height * 0.6 + 0.2);\n",
"    if (surfaceDebug == 5) color = vec3(s.edge);\n",
"    if (surfaceDebug == 6) color = pigment;\n",
"    if (surfaceDebug == 7) color = n * 0.5 + 0.5;\n",
"    if (surfaceDebug == 8) color = detailed * 0.5 + 0.5;\n",
"    if (surfaceDebug == 9) color = vec3(s.lod);\n",
"    fragColor = vec4(color, vertexColor.a);\n",
"}\n",
};
static const char* const furGuardVertexSource[] = {
"#version 330 compatibility\n",
"layout(location=0) in vec3 rootIndices;\n",
"layout(location=1) in vec3 rootBarycentric;\n",
"layout(location=2) in vec2 rootRandom;\n",
"layout(location=3) in vec3 rootCoord;\n",
"layout(location=4) in vec3 rootNormal;\n",
"layout(location=5) in vec3 rootFlow;\n",
"layout(location=6) in vec4 rootRegion;\n",
"layout(location=7) in float rootMask;\n",
"uniform samplerBuffer geometryData,surfaceData;\n",
"uniform vec4 surfaceRecipe[46];\n",
"uniform float guardVisibility;\n",
"uniform uint furSeed;\n",
"out vec3 restCoord,restNormal,viewPosition,viewNormal,posedFlowOut,restFlowOut;\n",
"out vec4 vertexColor,profileA,profileB;\n",
"out float ventral,skinMask,fragShellFraction,fragIntegumentMask,shellDelta;\n",
"out float ribbonSide,ribbonFade;\n",
"// Hash entero: identidad exacta de 32 bits, sin semillas temporales ni texturas.\n",
"uint SurfaceHash(uint x) {\n",
"    x^=x>>16; x*=0x7feb352du; x^=x>>15; x*=0x846ca68bu; return x^(x>>16);\n",
"}\n",
"vec3 CellHash(ivec2 cell,uint seed) {\n",
"    uint h=SurfaceHash(uint(cell.x)*0x9e3779b9u^uint(cell.y)*0x85ebca6bu^seed);\n",
"    return vec3(h>>8,SurfaceHash(h)>>8,SurfaceHash(h+1u)>>8)*(1.0/16777216.0);\n",
"}\n",
"float PigmentNoise(vec3 p,uint seed) {\n",
"    ivec3 i=ivec3(floor(p)); vec3 f=fract(p); f=f*f*(3.0-2.0*f);\n",
"    float z[2];\n",
"    for(int k=0;k<2;++k) {\n",
"        float a=CellHash(i.xy,seed^uint(i.z+k)).x,b=CellHash(i.xy+ivec2(1,0),seed^uint(i.z+k)).x;\n",
"        float c=CellHash(i.xy+ivec2(0,1),seed^uint(i.z+k)).x,d=CellHash(i.xy+ivec2(1,1),seed^uint(i.z+k)).x;\n",
"        z[k]=mix(mix(a,b,f.x),mix(c,d,f.x),f.y);\n",
"    }\n",
"    return mix(z[0],z[1],f.z);\n",
"}\n",
"\n",
"// Curva com\u00fan a volumen y cintas. Su derivada define la tangente \u00f3ptica.\n",
"vec3 FurCurveOffset(vec3 n,vec3 flow,float len,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    float bend=lay*(1.0-.8*stiff);\n",
"    float side=clump*(rnd-.5)*.35, wave=irregular*(rnd-.5)*.12;\n",
"    return len*(1.0+irregular*(rnd-.5)*.6)*(n*h+flow*bend*h*h+cross(n,flow)*(side*h*h+wave*h*h*(1.0-h)));\n",
"}\n",
"vec3 FurCurveDerivative(vec3 n,vec3 flow,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    return n+flow*(2.0*lay*(1.0-.8*stiff)*h)+cross(n,flow)*(clump*(rnd-.5)*.7*h+irregular*(rnd-.5)*.12*(2.0*h-3.0*h*h));\n",
"}\n",
"\n",
"// Identidad de mech\u00f3n compartida; las representaciones consultan el mismo dominio.\n",
"float FurFieldRandom(vec3 p,vec3 n,uint seed) {\n",
"    vec3 w=pow(abs(normalize(n)),vec3(4));w/=max(dot(w,vec3(1)),.00001);\n",
"    vec3 q=p*180.0;\n",
"    vec2 a=q.yz,b=q.xz,c=q.xy;\n",
"    a+=vec2(sin(a.y*.73+float(seed&255u)),sin(a.x*.67))*.32;\n",
"    uint sb=seed^0x231u,sc=seed^0x732u;\n",
"    b+=vec2(sin(b.y*.73+float(sb&255u)),sin(b.x*.67))*.32;\n",
"    c+=vec2(sin(c.y*.73+float(sc&255u)),sin(c.x*.67))*.32;\n",
"    return dot(vec3(CellHash(ivec2(floor(a)),seed).z,CellHash(ivec2(floor(b)),sb).z,CellHash(ivec2(floor(c)),sc).z),w);\n",
"}\n",
"\n",
"vec3 Rest(int i) {return vec3(texelFetch(surfaceData,i*15).r,texelFetch(surfaceData,i*15+1).r,texelFetch(surfaceData,i*15+2).r);}\n",
"void main() {\n",
"    int ia=int(rootIndices.x),ib=int(rootIndices.y),ic=int(rootIndices.z);\n",
"    restCoord=rootCoord;restNormal=normalize(rootNormal);restFlowOut=normalize(rootFlow);\n",
"    vec4 ga=texelFetch(geometryData,ia*2),gb=texelFetch(geometryData,ib*2),gc=texelFetch(geometryData,ic*2);\n",
"    vec3 pa=ga.xyz,pb=gb.xyz,pc=gc.xyz;\n",
"    vec3 na=vec3(ga.w,texelFetch(geometryData,ia*2+1).xy),nb=vec3(gb.w,texelFetch(geometryData,ib*2+1).xy),nc=vec3(gc.w,texelFetch(geometryData,ic*2+1).xy);\n",
"    vec3 pos=pa*rootBarycentric.x+pb*rootBarycentric.y+pc*rootBarycentric.z;\n",
"    vec3 n=normalize(na*rootBarycentric.x+nb*rootBarycentric.y+nc*rootBarycentric.z);\n",
"    // Jacobiano del tri\u00e1ngulo: transporta tambi\u00e9n el giro alrededor de la normal.\n",
"    vec3 e1=Rest(ib)-Rest(ia),e2=Rest(ic)-Rest(ia);\n",
"    float aa=dot(e1,e1),ab=dot(e1,e2),bb=dot(e2,e2),det=max(aa*bb-ab*ab,1e-16);\n",
"    vec2 coeff=vec2(dot(restFlowOut,e1)*bb-dot(restFlowOut,e2)*ab,dot(restFlowOut,e2)*aa-dot(restFlowOut,e1)*ab)/det;\n",
"    vec3 flow=(pb-pa)*coeff.x+(pc-pa)*coeff.y;flow=normalize(flow-n*dot(n,flow)+vec3(1e-9));\n",
"    int a=clamp(int(rootRegion.x+.5),0,10),b=clamp(int(rootRegion.y+.5),0,10);\n",
"    profileA=mix(surfaceRecipe[12+2*a],surfaceRecipe[12+2*b],rootRegion.z);\n",
"    profileB=mix(surfaceRecipe[13+2*a],surfaceRecipe[13+2*b],rootRegion.z);\n",
"    float belly=rootRegion.w*mix(float(a==3||a==4),float(b==3||b==4),rootRegion.z);\n",
"    profileA=mix(profileA,surfaceRecipe[20],belly);profileB=mix(profileB,surfaceRecipe[21],belly);\n",
"    vec4 p0=surfaceRecipe[8]*profileA;vec4 p1=surfaceRecipe[9]*vec4(1,profileB.z,profileB.w,profileB.x);\n",
"    float fieldRandom=FurFieldRandom(restCoord,restNormal,furSeed);\n",
"    float h=float(gl_VertexID/2)/4.0;\n",
"    float len=p0.x*surfaceRecipe[11].z;\n",
"    vec3 offset=FurCurveOffset(n,flow,len,p0.w,p1.x,p1.y,p1.z,fieldRandom,h);\n",
"    vec3 tangent=normalize(FurCurveDerivative(n,flow,p0.w,p1.x,p1.y,p1.z,fieldRandom,h));\n",
"    vec3 vp=(gl_ModelViewMatrix*vec4(pos+offset,1)).xyz;\n",
"    vec3 tv=normalize(gl_NormalMatrix*tangent);\n",
"    vec3 side=normalize(cross(tv,normalize(-vp))+vec3(1e-8));\n",
"    ribbonSide=float(gl_VertexID%2)*2.0-1.0;\n",
"    float width=.0015*p0.z*surfaceRecipe[11].z*(1.0-h)*(1.0-h);\n",
"    vp+=side*ribbonSide*width;\n",
"    float threshold=guardVisibility*clamp(p0.y*.25*surfaceRecipe[10].y*profileB.y,0.0,1.0);\n",
"    ribbonFade=smoothstep(rootRandom.x-.025,rootRandom.x+.025,threshold)*surfaceRecipe[11].w;\n",
"    if(threshold<=0.0)ribbonFade=0.0;\n",
"    gl_Position=gl_ProjectionMatrix*vec4(vp,1);\n",
"    viewPosition=vp;viewNormal=normalize(gl_NormalMatrix*n);posedFlowOut=tv;\n",
"    fragShellFraction=h;fragIntegumentMask=rootMask;skinMask=1;ventral=rootRegion.w;vertexColor=vec4(1);shellDelta=fieldRandom;\n",
"}\n",
};
static const char* const furGuardFragmentSource[] = {
"#version 330 compatibility\n",
"uniform vec4 surfaceRecipe[46];\n",
"uniform uint pigmentSeed,furSeed;\n",
"uniform int surfaceDebug;\n",
"uniform bool guardCoverage;\n",
"in vec3 restCoord,restNormal,viewPosition,viewNormal,posedFlowOut,restFlowOut;\n",
"in vec4 vertexColor,profileA,profileB;\n",
"in float ventral,skinMask,fragShellFraction,fragIntegumentMask,shellDelta,ribbonSide,ribbonFade;\n",
"out vec4 fragColor;\n",
"// Hash entero: identidad exacta de 32 bits, sin semillas temporales ni texturas.\n",
"uint SurfaceHash(uint x) {\n",
"    x^=x>>16; x*=0x7feb352du; x^=x>>15; x*=0x846ca68bu; return x^(x>>16);\n",
"}\n",
"vec3 CellHash(ivec2 cell,uint seed) {\n",
"    uint h=SurfaceHash(uint(cell.x)*0x9e3779b9u^uint(cell.y)*0x85ebca6bu^seed);\n",
"    return vec3(h>>8,SurfaceHash(h)>>8,SurfaceHash(h+1u)>>8)*(1.0/16777216.0);\n",
"}\n",
"float PigmentNoise(vec3 p,uint seed) {\n",
"    ivec3 i=ivec3(floor(p)); vec3 f=fract(p); f=f*f*(3.0-2.0*f);\n",
"    float z[2];\n",
"    for(int k=0;k<2;++k) {\n",
"        float a=CellHash(i.xy,seed^uint(i.z+k)).x,b=CellHash(i.xy+ivec2(1,0),seed^uint(i.z+k)).x;\n",
"        float c=CellHash(i.xy+ivec2(0,1),seed^uint(i.z+k)).x,d=CellHash(i.xy+ivec2(1,1),seed^uint(i.z+k)).x;\n",
"        z[k]=mix(mix(a,b,f.x),mix(c,d,f.x),f.y);\n",
"    }\n",
"    return mix(z[0],z[1],f.z);\n",
"}\n",
"\n",
"float SamplePigmentPattern(int pat, vec3 p, float scale, float sharpness, vec3 dir, uint seed) {\n",
"    vec3 q = p * max(scale, 0.01);\n",
"    float sh = clamp(sharpness, 0.0, 1.0);\n",
"    float noise = PigmentNoise(q, seed);\n",
"    if (pat == 0) {\n",
"        return 1.0;\n",
"    } else if (pat == 1) {\n",
"        return noise;\n",
"    } else if (pat == 2) {\n",
"        float w = 0.16 * (1.0 - sh * 0.75);\n",
"        return smoothstep(0.56 - w, 0.56 + w, noise);\n",
"    } else if (pat == 3) {\n",
"        float phase = float(seed & 1023u) * (6.2831853 / 1024.0);\n",
"        float wave = 0.5 + 0.5 * sin(q.z * 4.5 + phase + noise * 2.0);\n",
"        float w = 0.18 * (1.0 - sh * 0.8);\n",
"        return smoothstep(0.50 - w, 0.50 + w, wave);\n",
"    } else if (pat == 4) {\n",
"        float phase = float(seed & 1023u) * (6.2831853 / 1024.0);\n",
"        float wave = 0.5 + 0.5 * sin(q.x * 6.5 + phase + noise * 1.8);\n",
"        float w = 0.16 * (1.0 - sh * 0.8);\n",
"        return smoothstep(0.50 - w, 0.50 + w, wave);\n",
"    } else if (pat == 5) {\n",
"        float n1 = PigmentNoise(q * 0.40, seed);\n",
"        float n2 = PigmentNoise(q * 0.85, seed + 77u);\n",
"        float combined = n1 * 0.70 + n2 * 0.30;\n",
"        float w = 0.15 * (1.0 - sh * 0.8);\n",
"        return smoothstep(0.48 - w, 0.48 + w, combined);\n",
"    } else if (pat == 6) {\n",
"        float ringDist = abs(noise - 0.54);\n",
"        float wRing = 0.10 * (1.0 - sh * 0.6);\n",
"        float ring = 1.0 - smoothstep(0.0, wRing, ringDist);\n",
"        float center = 1.0 - smoothstep(0.0, 0.06, abs(noise - 0.72));\n",
"        return max(ring, center);\n",
"    } else if (pat == 7) {\n",
"        vec3 d = length(dir) > 0.001 ? normalize(dir) : vec3(0.0, -1.0, 0.0);\n",
"        float grad = dot(p, d) * scale;\n",
"        return clamp(grad * 0.5 + 0.5, 0.0, 1.0);\n",
"    }\n",
"    return 0.0;\n",
"}\n",
"\n",
"vec3 EvaluatePigment(vec3 p, float underside, vec4 params, uint seed) {\n",
"    int layerCount = int(surfaceRecipe[7].z + 0.5);\n",
"    vec3 color;\n",
"    if (layerCount <= 0) {\n",
"        vec3 q = p * params.w;\n",
"        float footprint = max(length(dFdx(q)), length(dFdy(q)));\n",
"        float noise = PigmentNoise(q, seed);\n",
"        float bandWave = .5 + .5 * sin(q.z * 5.0 + noise * 3.0);\n",
"        float bands = smoothstep(.48, .7, bandWave);\n",
"        float spots = smoothstep(.48, .7, noise);\n",
"        float pattern = mix(spots, bands, surfaceRecipe[6].w);\n",
"        pattern = mix(pattern, .35, smoothstep(.3, 1.0, footprint));\n",
"        color = mix(surfaceRecipe[0].rgb, surfaceRecipe[1].rgb, pattern * params.z);\n",
"        color *= 1.0 - params.x * (1.0 - underside);\n",
"        return mix(color, surfaceRecipe[2].rgb, underside * params.y);\n",
"    }\n",
"\n",
"    color = surfaceRecipe[0].rgb;\n",
"    for (int i = 0; i < 4; ++i) {\n",
"        if (i >= layerCount) break;\n",
"        vec4 layerCol = surfaceRecipe[30 + 3 * i];\n",
"        vec4 layerParam = surfaceRecipe[31 + 3 * i];\n",
"        vec4 layerDir = surfaceRecipe[32 + 3 * i];\n",
"        uint layerSeed = seed ^ uint(layerParam.w) ^ uint(i * 101);\n",
"        float sampleVal = SamplePigmentPattern(int(layerParam.x + 0.5), p, layerParam.y, layerParam.z, layerDir.xyz, layerSeed);\n",
"        float blend = clamp(sampleVal * layerCol.a, 0.0, 1.0);\n",
"        color = mix(color, layerCol.rgb, blend);\n",
"    }\n",
"    color *= 1.0 - params.x * (1.0 - underside);\n",
"    return mix(color, surfaceRecipe[2].rgb, underside * params.y);\n",
"}\n",
"\n",
"// Curva com\u00fan a volumen y cintas. Su derivada define la tangente \u00f3ptica.\n",
"vec3 FurCurveOffset(vec3 n,vec3 flow,float len,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    float bend=lay*(1.0-.8*stiff);\n",
"    float side=clump*(rnd-.5)*.35, wave=irregular*(rnd-.5)*.12;\n",
"    return len*(1.0+irregular*(rnd-.5)*.6)*(n*h+flow*bend*h*h+cross(n,flow)*(side*h*h+wave*h*h*(1.0-h)));\n",
"}\n",
"vec3 FurCurveDerivative(vec3 n,vec3 flow,float lay,float stiff,float clump,float irregular,float rnd,float h) {\n",
"    return n+flow*(2.0*lay*(1.0-.8*stiff)*h)+cross(n,flow)*(clump*(rnd-.5)*.7*h+irregular*(rnd-.5)*.12*(2.0*h-3.0*h*h));\n",
"}\n",
"\n",
"// Identidad de mech\u00f3n compartida; las representaciones consultan el mismo dominio.\n",
"float FurFieldRandom(vec3 p,vec3 n,uint seed) {\n",
"    vec3 w=pow(abs(normalize(n)),vec3(4));w/=max(dot(w,vec3(1)),.00001);\n",
"    vec3 q=p*180.0;\n",
"    vec2 a=q.yz,b=q.xz,c=q.xy;\n",
"    a+=vec2(sin(a.y*.73+float(seed&255u)),sin(a.x*.67))*.32;\n",
"    uint sb=seed^0x231u,sc=seed^0x732u;\n",
"    b+=vec2(sin(b.y*.73+float(sb&255u)),sin(b.x*.67))*.32;\n",
"    c+=vec2(sin(c.y*.73+float(sc&255u)),sin(c.x*.67))*.32;\n",
"    return dot(vec3(CellHash(ivec2(floor(a)),seed).z,CellHash(ivec2(floor(b)),sb).z,CellHash(ivec2(floor(c)),sc).z),w);\n",
"}\n",
"\n",
"struct FurSample { float coverage; float undercoat; float guard; float fiberRandom; vec3 tangent; };\n",
"// Secciones circulares de fol\u00edculos compuestos; filtro de \u00e1rea cuando son subp\u00edxel.\n",
"vec3 FurPlane(vec2 q,vec2 flow,float h,vec4 p0,vec4 p1,vec4 p2,uint seed) {\n",
"    // Una deformaci\u00f3n suave del dominio evita filas regulares sin saltos de plano.\n",
"    q+=vec2(sin(q.y*.73+float(seed&255u)),sin(q.x*.67))* .32;\n",
"    ivec2 cell=ivec2(floor(q));vec3 r=CellHash(cell,seed);\n",
"    vec2 local=fract(q)-.5-(r.xy-.5)*.50;\n",
"    float footprint=max(length(dFdx(q)),length(dFdy(q)));\n",
"    float variation=1.0+p1.z*(r.z-.5)*.6;\n",
"    vec2 lateral=vec2(-flow.y,flow.x);\n",
"    local-=lateral*(p1.y*(r.z-.5)*.35*h*h+p1.z*(r.z-.5)*.12*h*h*(1.0-h))*p0.x*180.0;\n",
"    float aa=max(.008,footprint*.5);\n",
"    float rad=.065*p0.z*max(0.0,1.0-h/variation);\n",
"    float guard=1.0-smoothstep(rad-aa,rad+aa,length(local));\n",
"    float filtered=smoothstep(.3,.9,footprint);\n",
"    guard=mix(guard,3.14159*rad*rad,filtered)*p2.y*(1.0-smoothstep(variation-.05,variation+.05,h));\n",
"    // Sector angular m\u00e1s pr\u00f3ximo: seis secundarios sin bucle ni b\u00fasquedas vecinas.\n",
"    float angle=atan(local.y,local.x)-6.283185*r.x;\n",
"    float sector=floor(angle*(6.0/6.283185)+.5);\n",
"    float theta=sector*(6.283185/6.0)+6.283185*r.x;\n",
"    vec2 center=vec2(cos(theta),sin(theta))*.23*(1.0-p1.y*h);\n",
"    float uh=h/max(.1,p2.x*variation);\n",
"    float radius=.085*p0.z*sqrt(max(0.0,1.0-uh));\n",
"    float under=1.0-smoothstep(radius-aa,radius+aa,length(local-center));\n",
"    under=mix(under,6.0*3.14159*radius*radius,filtered)*p1.w*(1.0-smoothstep(.9,1.05,uh));\n",
"    return vec3(under,guard,r.z);\n",
"}\n",
"FurSample EvaluateFurStrands(vec3 p,vec3 restN,vec3 n,vec3 flow,float h,vec4 p0,vec4 p1,vec4 p2,uint seed) {\n",
"    vec3 w=pow(abs(normalize(restN)),vec3(4));w/=max(dot(w,vec3(1)),.0001);\n",
"    // Mezcla continua: ninguna proyecci\u00f3n ganadora, identidad en reposo.\n",
"    vec3 q=p*180.0;\n",
"    vec3 a=FurPlane(q.yz,normalize(restFlowOut.yz+vec2(.00001)),h,p0,p1,p2,seed);\n",
"    vec3 b=FurPlane(q.xz,normalize(restFlowOut.xz+vec2(.00001)),h,p0,p1,p2,seed^0x231u);\n",
"    vec3 c=FurPlane(q.xy,normalize(restFlowOut.xy+vec2(.00001)),h,p0,p1,p2,seed^0x732u);\n",
"    vec3 f=a*w.x+b*w.y+c*w.z;\n",
"    vec3 tangent=normalize(FurCurveDerivative(n,flow,p0.w,p1.x,p1.y,p1.z,f.z,h));\n",
"    return FurSample(f.x+f.y,f.x,f.y,f.z,tangent);\n",
"}\n",
"vec3 FurLighting(vec3 albedo,vec3 tangent,vec3 normal,vec3 viewPos,float roughness,float sheen,float h) {\n",
"    vec3 L=normalize(vec3(10,20,15)-viewPos),V=normalize(-viewPos),T=normalize(tangent),N=normalize(normal);\n",
"    vec3 H=normalize(L+V);\n",
"    float primary=pow(sqrt(max(0.0,1.0-pow(clamp(dot(T,H)+.08,-1.0,1.0),2.0))),mix(140.0,24.0,roughness));\n",
"    float secondary=pow(sqrt(max(0.0,1.0-pow(clamp(dot(T,H)-.20,-1.0,1.0),2.0))),mix(45.0,10.0,roughness));\n",
"    float diffuse=sqrt(max(0.0,1.0-pow(dot(T,L),2.0)));\n",
"    float shadow=exp(-.28*surfaceRecipe[8].y*(1.0-h)/max(.3,abs(dot(N,L))));\n",
"    float transmission=pow(max(0.0,dot(-L,V)),4.0)*(1.0-abs(dot(T,L)))*.12;\n",
"    return albedo*(.32+.85*diffuse*shadow+transmission)+sheen*(vec3(.7)*primary+albedo*.35*secondary)*shadow;\n",
"}\n",
"\n",
"void main() {\n",
"    float edge=1.0-smoothstep(.65,1.0,abs(ribbonSide));\n",
"    float alpha=edge*ribbonFade*fragIntegumentMask;\n",
"    if(alpha<.001)discard;\n",
"    float rootTip=mix(1.0-surfaceRecipe[11].x,1.0+surfaceRecipe[11].y,clamp(fragShellFraction*(.8+.4*shellDelta),0.0,1.0));\n",
"    vec3 pigment=EvaluatePigment(restCoord,ventral,surfaceRecipe[3],pigmentSeed);\n",
"    vec3 color=FurLighting(pigment*rootTip*(.94+.12*shellDelta),posedFlowOut,viewNormal,viewPosition,surfaceRecipe[10].z,surfaceRecipe[10].w,fragShellFraction);\n",
"    if(surfaceDebug==11||surfaceDebug==18)color=posedFlowOut*.5+.5;\n",
"    if(surfaceDebug==21)color=vec3(ribbonFade);\n",
"    if(surfaceDebug==22)color=vec3(shellDelta);\n",
"    fragColor=vec4(guardCoverage?color:color*alpha,alpha);\n",
"}\n",
};
