/* Generado por tools/generate_sdf_shader.py. No editar. */
#define P_STRIDE 6
static void PackP(float (*out)[4], const MonsterSDFBodyPart* in) {
    PackVector(out[0], in->center);
    PackVector(out[1], in->radii);
    PackVector(out[2], in->invRadii);
    PackVector(out[3], in->invRadiiSquared);
    out[4][0]=(float)in->minRadius;
    PackColor(out[5], in->color);
}
#define C_STRIDE 33
static void PackC(float (*out)[4], const MonsterSDFConnector* in) {
    PackVector(out[0], in->a);
    PackVector(out[1], in->b);
    PackVector(out[2], in->ba);
    PackVector(out[3], in->forward);
    PackVector(out[4], in->side);
    PackVector(out[5], in->up);
    out[6][0]=(float)in->length;
    out[7][0]=(float)in->invBaLengthSquared;
    out[8][0]=(float)in->r1;
    out[9][0]=(float)in->r2;
    out[10][0]=(float)in->radiusDelta;
    out[11][0]=(float)in->widthA;
    out[12][0]=(float)in->heightA;
    out[13][0]=(float)in->widthB;
    out[14][0]=(float)in->heightB;
    out[15][0]=(float)in->widthBulge;
    out[16][0]=(float)in->heightBulge;
    out[17][0]=(float)in->fromId;
    out[18][0]=(float)in->toId;
    out[19][0]=(float)in->isHeadNeck;
    out[20][0]=(float)in->isAttachment;
    out[21][0]=(float)in->kind;
    PackColor(out[22], in->color);
    PackVector(out[23], in->bounds.start);
    PackVector(out[24], in->bounds.end);
    out[25][0]=(float)in->distanceLowerBoundScale;
    out[26][0]=(float)in->groupCount;
    PackVector(out[27], in->groupBounds.start);
    PackVector(out[28], in->groupBounds.end);
    out[29][0]=(float)in->groupLowerBoundScale;
    out[30][0]=(float)in->groupSmoothness;
    out[31][0]=(float)in->maxRadius;
    out[32][0]=(float)in->localSmoothness;
}
#define M_STRIDE 132
static void PackM(float (*out)[4], const MonsterSDFMouth* in) {
    PackVector(out[0], in->center);
    PackVector(out[1], in->visualBounds.start);
    PackVector(out[2], in->visualBounds.end);
    PackVector(out[3], in->visualJawPivot);
    out[4][0]=(float)in->visualJawAngle;
    out[5][0]=(float)in->visualJawScale;
    out[6][0]=(float)in->visualJawBoundRadius;
    PackVector(out[7], in->inverseRotation.row0);
    PackVector(out[8], in->inverseRotation.row1);
    PackVector(out[9], in->inverseRotation.row2);
    PackVector(out[10], in->muzzleCenterLocal);
    PackVector(out[11], in->muzzleHalfExtents);
    out[12][0]=(float)in->muzzleSmoothness;
    out[13][0]=(float)in->cephalicDevelopment;
    PackColor(out[14], in->skinColor);
    PackVector(out[15], in->entranceCenterLocal);
    PackVector(out[16], in->entranceHalfExtents);
    PackVector(out[17], in->cavityCenterLocal);
    PackVector(out[18], in->cavityRadii);
    PackColor(out[19], in->insideColor);
    out[20][0]=(float)in->entranceToCavitySmoothness;
    out[21][0]=(float)in->rimBevel;
    PackVector(out[22], in->jawCenterLocal);
    PackVector(out[23], in->jawRadii);
    PackVector(out[24], in->hingeCenterLocal);
    out[25][0]=(float)in->hingeRadius;
    out[26][0]=(float)in->throatRadius;
    out[27][0]=(float)in->jawRearMass;
    out[28][0]=(float)in->jawMuscle;
    out[29][0]=(float)in->lowerBeak;
    PackVector(out[30], in->hostCenterLocal);
    PackVector(out[31], in->hostRadii);
    PackVector(out[32], in->craniumCenterLocal);
    PackVector(out[33], in->craniumRadii);
    PackVector(out[34], in->snoutCenterLocal);
    PackVector(out[35], in->snoutRadii);
    PackVector(out[36], in->cheekCenterLocal);
    PackVector(out[37], in->cheekRadii);
    PackVector(out[38], in->leftTemporalCenterLocal);
    PackVector(out[39], in->rightTemporalCenterLocal);
    PackVector(out[40], in->temporalRadii);
    PackVector(out[41], in->leftMaxillaryCenterLocal);
    PackVector(out[42], in->rightMaxillaryCenterLocal);
    PackVector(out[43], in->maxillaryRadii);
    PackVector(out[44], in->leftBrowCenterLocal);
    PackVector(out[45], in->rightBrowCenterLocal);
    PackVector(out[46], in->browRadii);
    out[47][0]=(float)in->sweptSkull;
    PackStation(out+48, &in->headStations[0]);
    PackStation(out+50, &in->headStations[1]);
    PackStation(out+52, &in->headStations[2]);
    PackStation(out+54, &in->headStations[3]);
    PackStation(out+56, &in->headStations[4]);
    PackStation(out+58, &in->headStations[5]);
    out[60][0]=(float)in->anatomicalHead;
    PackVector(out[61], in->faceRootLocal);
    PackVector(out[62], in->faceMidLocal);
    PackVector(out[63], in->faceTipLocal);
    PackVector(out[64], in->faceRootRadii);
    PackVector(out[65], in->faceMidRadii);
    PackVector(out[66], in->faceTipRadii);
    PackVector(out[67], in->leftOrbitCenterLocal);
    PackVector(out[68], in->rightOrbitCenterLocal);
    PackVector(out[69], in->orbitRadii);
    PackVector(out[70], in->leftOrbitRimCenterLocal);
    PackVector(out[71], in->rightOrbitRimCenterLocal);
    PackVector(out[72], in->orbitRimRadii);
    PackVector(out[73], in->leftOrbitNormal);
    PackVector(out[74], in->rightOrbitNormal);
    out[75][0]=(float)in->orbitSocketDepth;
    out[76][0]=(float)in->eyelidCoverage;
    PackVector(out[77], in->noseCenterLocal);
    PackVector(out[78], in->noseRadii);
    PackVector(out[79], in->leftNostrilCenterLocal);
    PackVector(out[80], in->rightNostrilCenterLocal);
    PackVector(out[81], in->nostrilRadii);
    PackVector(out[82], in->leftTympanumCenterLocal);
    PackVector(out[83], in->rightTympanumCenterLocal);
    PackVector(out[84], in->tympanumRadii);
    out[85][0]=(float)in->tympanumDepth;
    PackVector(out[86], in->leftEarCenterLocal);
    PackVector(out[87], in->rightEarCenterLocal);
    PackVector(out[88], in->earRadii);
    PackVector(out[89], in->earShape);
    PackVector(out[90], in->earDirection);
    PackVector(out[91], in->rightEarDirection);
    PackVector(out[92], in->leftEarSide);
    PackVector(out[93], in->rightEarSide);
    PackVector(out[94], in->leftEarNormal);
    PackVector(out[95], in->rightEarNormal);
    out[96][0]=(float)in->earTipFraction;
    out[97][0]=(float)in->earConcavity;
    out[98][0]=(float)in->earLongitudinalCurve;
    out[99][0]=(float)in->earRootRoll;
    out[100][0]=(float)in->earTipRoundness;
    out[101][0]=(float)in->earFold;
    out[102][0]=(float)in->earRootFlare;
    out[103][0]=(float)in->earMarginBow;
    out[104][0]=(float)in->earMarginAsymmetry;
    out[105][0]=(float)in->headUnionSmoothness;
    out[106][0]=(float)in->headBodySmoothness;
    PackVector(out[107], in->neckCollarRootLocal);
    PackVector(out[108], in->neckCollarMidLocal);
    PackVector(out[109], in->neckCollarTipLocal);
    PackVector(out[110], in->neckCollarRootRadii);
    PackVector(out[111], in->neckCollarMidRadii);
    PackVector(out[112], in->neckCollarTipRadii);
    out[113][0]=(float)in->hasNasalPad;
    out[114][0]=(float)in->hasEars;
    out[115][0]=(float)in->tympanumDevelopment;
    out[116][0]=(float)in->hasTympana;
    out[117][0]=(float)in->taperedMandible;
    out[118][0]=(float)in->faceRounding;
    PackVector(out[119], in->influenceBounds.start);
    PackVector(out[120], in->influenceBounds.end);
    PackVector(out[121], in->headBounds.start);
    PackVector(out[122], in->headBounds.end);
    PackVector(out[123], in->seamSkullLeftLocal);
    PackVector(out[124], in->seamSkullRightLocal);
    PackVector(out[125], in->seamJawLeftClosedLocal);
    PackVector(out[126], in->seamJawRightClosedLocal);
    PackVector(out[127], in->seamGularLocal);
    PackVector(out[128], in->seamJawAnchorLocal);
    out[129][0]=(float)in->seamScale;
    PackVector(out[130], in->seamBounds.start);
    PackVector(out[131], in->seamBounds.end);
}
static const char* const sdfFragmentSource[] = {
"#version 330 compatibility\n",
"uniform samplerBuffer sceneData;\nuniform int partBase, partCount, connectorBase, connectorCount, mouthBase, mouthCount, axialBase, axialCount;\nuniform float bodySmoothness;\n#define Vector3 vec3\n#define Vec3_Create vec3\n#define Vec3_Sub(a,b) ((a)-(b))\n#define Vec3_Add(a,b) ((a)+(b))\n#define Vec3_Scale(a,b) ((a)*(b))\n#define Vec3_Lerp mix\n#define Vec3_Dot dot\n#define Vec3_Cross cross\n#define Vec3_Normalize normalize\n#define Vec3_Distance distance\n#define cosf cos\n#define sinf sin\n#define Vec3_Length length\n#define Vec3_LengthSq(a) dot(a,a)\n#define Math_Max max\n#define Math_Min min\n#define Math_Lerp mix\n#define Math_Clamp clamp\n#define Math_Clamp01(a) clamp(a,0.0,1.0)\n#define fabsf abs\n#define sqrtf sqrt\nvec4 dataAt(int index) { return texelFetch(sceneData,index); }\nvec3 P_center(int i) { return dataAt(i+0).xyz; }\nvec3 P_radii(int i) { return dataAt(i+1).xyz; }\nvec3 P_invRadii(int i) { return dataAt(i+2).xyz; }\nvec3 P_invRadiiSquared(int i) { return dataAt(i+3).xyz; }\nfloat P_minRadius(int i) { return float(dataAt(i+4).x); }\nvec3 P_color(int i) { return dataAt(i+5).xyz; }\n#define P_STRIDE 6\nvec3 C_a(int i) { return dataAt(i+0).xyz; }\nvec3 C_b(int i) { return dataAt(i+1).xyz; }\nvec3 C_ba(int i) { return dataAt(i+2).xyz; }\nvec3 C_forward(int i) { return dataAt(i+3).xyz; }\nvec3 C_side(int i) { return dataAt(i+4).xyz; }\nvec3 C_up(int i) { return dataAt(i+5).xyz; }\nfloat C_length(int i) { return float(dataAt(i+6).x); }\nfloat C_invBaLengthSquared(int i) { return float(dataAt(i+7).x); }\nfloat C_r1(int i) { return float(dataAt(i+8).x); }\nfloat C_r2(int i) { return float(dataAt(i+9).x); }\nfloat C_radiusDelta(int i) { return float(dataAt(i+10).x); }\nfloat C_widthA(int i) { return float(dataAt(i+11).x); }\nfloat C_heightA(int i) { return float(dataAt(i+12).x); }\nfloat C_widthB(int i) { return float(dataAt(i+13).x); }\nfloat C_heightB(int i) { return float(dataAt(i+14).x); }\nfloat C_widthBulge(int i) { return float(dataAt(i+15).x); }\nfloat C_heightBulge(int i) { return float(dataAt(",
"i+16).x); }\nint C_fromId(int i) { return int(dataAt(i+17).x); }\nint C_toId(int i) { return int(dataAt(i+18).x); }\nbool C_isHeadNeck(int i) { return bool(dataAt(i+19).x); }\nbool C_isAttachment(int i) { return bool(dataAt(i+20).x); }\nint C_kind(int i) { return int(dataAt(i+21).x); }\nvec3 C_color(int i) { return dataAt(i+22).xyz; }\nvec3 C_bounds_start(int i) { return dataAt(i+23).xyz; }\nvec3 C_bounds_end(int i) { return dataAt(i+24).xyz; }\nfloat C_distanceLowerBoundScale(int i) { return float(dataAt(i+25).x); }\nint C_groupCount(int i) { return int(dataAt(i+26).x); }\nvec3 C_groupBounds_start(int i) { return dataAt(i+27).xyz; }\nvec3 C_groupBounds_end(int i) { return dataAt(i+28).xyz; }\nfloat C_groupLowerBoundScale(int i) { return float(dataAt(i+29).x); }\nfloat C_groupSmoothness(int i) { return float(dataAt(i+30).x); }\nfloat C_maxRadius(int i) { return float(dataAt(i+31).x); }\nfloat C_localSmoothness(int i) { return float(dataAt(i+32).x); }\n#define C_STRIDE 33\nvec3 M_center(int i) { return dataAt(i+0).xyz; }\nvec3 M_visualBounds_start(int i) { return dataAt(i+1).xyz; }\nvec3 M_visualBounds_end(int i) { return dataAt(i+2).xyz; }\nvec3 M_visualJawPivot(int i) { return dataAt(i+3).xyz; }\nfloat M_visualJawAngle(int i) { return float(dataAt(i+4).x); }\nfloat M_visualJawScale(int i) { return float(dataAt(i+5).x); }\nfloat M_visualJawBoundRadius(int i) { return float(dataAt(i+6).x); }\nmat3 M_inverseRotation(int i) { return transpose(mat3(dataAt(i+7).xyz,dataAt(i+8).xyz,dataAt(i+9).xyz)); }\nvec3 M_muzzleCenterLocal(int i) { return dataAt(i+10).xyz; }\nvec3 M_muzzleHalfExtents(int i) { return dataAt(i+11).xyz; }\nfloat M_muzzleSmoothness(int i) { return float(dataAt(i+12).x); }\nfloat M_cephalicDevelopment(int i) { return float(dataAt(i+13).x); }\nvec3 M_skinColor(int i) { return dataAt(i+14).xyz; }\nvec3 M_entranceCenterLocal(int i) { return dataAt(i+15).xyz; }\nvec3 M_entranceHalfExtents(int i) { return dataAt(i+16).xyz; }\nvec3 M_cavityCenterLocal(int i) { return dataAt(i+17).xyz; }\nvec3 M",
"_cavityRadii(int i) { return dataAt(i+18).xyz; }\nvec3 M_insideColor(int i) { return dataAt(i+19).xyz; }\nfloat M_entranceToCavitySmoothness(int i) { return float(dataAt(i+20).x); }\nfloat M_rimBevel(int i) { return float(dataAt(i+21).x); }\nvec3 M_jawCenterLocal(int i) { return dataAt(i+22).xyz; }\nvec3 M_jawRadii(int i) { return dataAt(i+23).xyz; }\nvec3 M_hingeCenterLocal(int i) { return dataAt(i+24).xyz; }\nfloat M_hingeRadius(int i) { return float(dataAt(i+25).x); }\nfloat M_throatRadius(int i) { return float(dataAt(i+26).x); }\nfloat M_jawRearMass(int i) { return float(dataAt(i+27).x); }\nfloat M_jawMuscle(int i) { return float(dataAt(i+28).x); }\nbool M_lowerBeak(int i) { return bool(dataAt(i+29).x); }\nvec3 M_hostCenterLocal(int i) { return dataAt(i+30).xyz; }\nvec3 M_hostRadii(int i) { return dataAt(i+31).xyz; }\nvec3 M_craniumCenterLocal(int i) { return dataAt(i+32).xyz; }\nvec3 M_craniumRadii(int i) { return dataAt(i+33).xyz; }\nvec3 M_snoutCenterLocal(int i) { return dataAt(i+34).xyz; }\nvec3 M_snoutRadii(int i) { return dataAt(i+35).xyz; }\nvec3 M_cheekCenterLocal(int i) { return dataAt(i+36).xyz; }\nvec3 M_cheekRadii(int i) { return dataAt(i+37).xyz; }\nvec3 M_leftTemporalCenterLocal(int i) { return dataAt(i+38).xyz; }\nvec3 M_rightTemporalCenterLocal(int i) { return dataAt(i+39).xyz; }\nvec3 M_temporalRadii(int i) { return dataAt(i+40).xyz; }\nvec3 M_leftMaxillaryCenterLocal(int i) { return dataAt(i+41).xyz; }\nvec3 M_rightMaxillaryCenterLocal(int i) { return dataAt(i+42).xyz; }\nvec3 M_maxillaryRadii(int i) { return dataAt(i+43).xyz; }\nvec3 M_leftBrowCenterLocal(int i) { return dataAt(i+44).xyz; }\nvec3 M_rightBrowCenterLocal(int i) { return dataAt(i+45).xyz; }\nvec3 M_browRadii(int i) { return dataAt(i+46).xyz; }\nbool M_sweptSkull(int i) { return bool(dataAt(i+47).x); }\nint M_headStations(int i) { return i+48; }\nbool M_anatomicalHead(int i) { return bool(dataAt(i+60).x); }\nvec3 M_faceRootLocal(int i) { return dataAt(i+61).xyz; }\nvec3 M_faceMidLocal(int i) { return dataAt(i+62",
").xyz; }\nvec3 M_faceTipLocal(int i) { return dataAt(i+63).xyz; }\nvec3 M_faceRootRadii(int i) { return dataAt(i+64).xyz; }\nvec3 M_faceMidRadii(int i) { return dataAt(i+65).xyz; }\nvec3 M_faceTipRadii(int i) { return dataAt(i+66).xyz; }\nvec3 M_leftOrbitCenterLocal(int i) { return dataAt(i+67).xyz; }\nvec3 M_rightOrbitCenterLocal(int i) { return dataAt(i+68).xyz; }\nvec3 M_orbitRadii(int i) { return dataAt(i+69).xyz; }\nvec3 M_leftOrbitRimCenterLocal(int i) { return dataAt(i+70).xyz; }\nvec3 M_rightOrbitRimCenterLocal(int i) { return dataAt(i+71).xyz; }\nvec3 M_orbitRimRadii(int i) { return dataAt(i+72).xyz; }\nvec3 M_leftOrbitNormal(int i) { return dataAt(i+73).xyz; }\nvec3 M_rightOrbitNormal(int i) { return dataAt(i+74).xyz; }\nfloat M_orbitSocketDepth(int i) { return float(dataAt(i+75).x); }\nfloat M_eyelidCoverage(int i) { return float(dataAt(i+76).x); }\nvec3 M_noseCenterLocal(int i) { return dataAt(i+77).xyz; }\nvec3 M_noseRadii(int i) { return dataAt(i+78).xyz; }\nvec3 M_leftNostrilCenterLocal(int i) { return dataAt(i+79).xyz; }\nvec3 M_rightNostrilCenterLocal(int i) { return dataAt(i+80).xyz; }\nvec3 M_nostrilRadii(int i) { return dataAt(i+81).xyz; }\nvec3 M_leftTympanumCenterLocal(int i) { return dataAt(i+82).xyz; }\nvec3 M_rightTympanumCenterLocal(int i) { return dataAt(i+83).xyz; }\nvec3 M_tympanumRadii(int i) { return dataAt(i+84).xyz; }\nfloat M_tympanumDepth(int i) { return float(dataAt(i+85).x); }\nvec3 M_leftEarCenterLocal(int i) { return dataAt(i+86).xyz; }\nvec3 M_rightEarCenterLocal(int i) { return dataAt(i+87).xyz; }\nvec3 M_earRadii(int i) { return dataAt(i+88).xyz; }\nvec3 M_earShape(int i) { return dataAt(i+89).xyz; }\nvec3 M_earDirection(int i) { return dataAt(i+90).xyz; }\nvec3 M_rightEarDirection(int i) { return dataAt(i+91).xyz; }\nvec3 M_leftEarSide(int i) { return dataAt(i+92).xyz; }\nvec3 M_rightEarSide(int i) { return dataAt(i+93).xyz; }\nvec3 M_leftEarNormal(int i) { return dataAt(i+94).xyz; }\nvec3 M_rightEarNormal(int i) { return dataAt(i+95).xyz; }\nfloat M_earTip",
"Fraction(int i) { return float(dataAt(i+96).x); }\nfloat M_earConcavity(int i) { return float(dataAt(i+97).x); }\nfloat M_earLongitudinalCurve(int i) { return float(dataAt(i+98).x); }\nfloat M_earRootRoll(int i) { return float(dataAt(i+99).x); }\nfloat M_earTipRoundness(int i) { return float(dataAt(i+100).x); }\nfloat M_earFold(int i) { return float(dataAt(i+101).x); }\nfloat M_earRootFlare(int i) { return float(dataAt(i+102).x); }\nfloat M_earMarginBow(int i) { return float(dataAt(i+103).x); }\nfloat M_earMarginAsymmetry(int i) { return float(dataAt(i+104).x); }\nfloat M_headUnionSmoothness(int i) { return float(dataAt(i+105).x); }\nfloat M_headBodySmoothness(int i) { return float(dataAt(i+106).x); }\nvec3 M_neckCollarRootLocal(int i) { return dataAt(i+107).xyz; }\nvec3 M_neckCollarMidLocal(int i) { return dataAt(i+108).xyz; }\nvec3 M_neckCollarTipLocal(int i) { return dataAt(i+109).xyz; }\nvec3 M_neckCollarRootRadii(int i) { return dataAt(i+110).xyz; }\nvec3 M_neckCollarMidRadii(int i) { return dataAt(i+111).xyz; }\nvec3 M_neckCollarTipRadii(int i) { return dataAt(i+112).xyz; }\nbool M_hasNasalPad(int i) { return bool(dataAt(i+113).x); }\nbool M_hasEars(int i) { return bool(dataAt(i+114).x); }\nfloat M_tympanumDevelopment(int i) { return float(dataAt(i+115).x); }\nbool M_hasTympana(int i) { return bool(dataAt(i+116).x); }\nbool M_taperedMandible(int i) { return bool(dataAt(i+117).x); }\nfloat M_faceRounding(int i) { return float(dataAt(i+118).x); }\nvec3 M_influenceBounds_start(int i) { return dataAt(i+119).xyz; }\nvec3 M_influenceBounds_end(int i) { return dataAt(i+120).xyz; }\nvec3 M_headBounds_start(int i) { return dataAt(i+121).xyz; }\nvec3 M_headBounds_end(int i) { return dataAt(i+122).xyz; }\nvec3 M_seamSkullLeftLocal(int i) { return dataAt(i+123).xyz; }\nvec3 M_seamSkullRightLocal(int i) { return dataAt(i+124).xyz; }\nvec3 M_seamJawLeftClosedLocal(int i) { return dataAt(i+125).xyz; }\nvec3 M_seamJawRightClosedLocal(int i) { return dataAt(i+126).xyz; }\nvec3 M_seamGularLocal(int i) { retu",
"rn dataAt(i+127).xyz; }\nvec3 M_seamJawAnchorLocal(int i) { return dataAt(i+128).xyz; }\nfloat M_seamScale(int i) { return float(dataAt(i+129).x); }\nvec3 M_seamBounds_start(int i) { return dataAt(i+130).xyz; }\nvec3 M_seamBounds_end(int i) { return dataAt(i+131).xyz; }\n#define M_STRIDE 132\nfloat SDF_SmoothUnion(float a,float b,float k);\nfloat SDF_CurvedPinna(Vector3 p,Vector3 shape,Vector3 up,Vector3 side,Vector3 normal,\n                      float tipFraction,float concavity,float curve,float rootRoll,\n                      float tipRoundness,float fold,float rootFlare,float marginBow,float marginAsymmetry) {\n    float h=Math_Max(fabsf(shape.y),.01),w=Math_Max(fabsf(shape.x),.006),th=Math_Max(fabsf(shape.z),.003);\n    float y=Vec3_Dot(p,up),t=Math_Clamp01(y/h+.5);\n    float centerX=w*marginBow*(.45*sinf(3.14159265*t)+.24*t*t);\n    float centerZ=curve*sinf(3.14159265*t)+fold*t*t;\n    float x=Vec3_Dot(p,side)-centerX,z=Vec3_Dot(p,normal)-centerZ;\n    float tipStart=.90-.10*Math_Clamp01(tipRoundness);\n    float profileT=Math_Min(t,tipStart);\n    float distal=profileT*profileT*profileT;\n    distal*=distal;\n    float flare=rootFlare*.32*4.0*profileT*(1.0-profileT)*(1.0-profileT)*(1.0-profileT);\n    float width=w*(.76+.34*sinf(3.14159265*profileT)-\n                   (.76-Math_Clamp(tipFraction,.04,.55))*distal+flare);\n    float tipU=Math_Clamp01((t-tipStart)/(1.0-tipStart));\n    float tipArc=sqrtf(Math_Max(0.0,1.0-tipU*tipU));\n    width*=tipArc;\n    float asym=(marginAsymmetry-.5)*.32*(.3+.7*t);\n    width*=x>=0?1.0+asym:1.0-asym;\n    float lateral=x/Math_Max(width,.001);\n    float edge=Math_Clamp01((fabsf(lateral)-.70)/.25);\n    float thick=th*(.92-.64*t)+th*rootRoll*.32*(1.0-t)*(1.0-t);\n    thick+=th*(.18+.12*rootRoll)*edge*(1.0-t*t);\n    thick*=tipArc;\n    \n    float cup=th*concavity*(.65+1.25*(1.0-t))*Math_Max(0.0,1.0-lateral*lateral);\n    float transverse=th*.18*rootRoll*lateral*lateral*(1.0-t);\n    float qx=fabsf(x)-width,qz=fabsf(z+cup-transverse)-thick;\n    float sh",
"ell=sqrtf(Math_Max(qx,0.0)*Math_Max(qx,0.0)+Math_Max(qz,0.0)*Math_Max(qz,0.0))+\n        Math_Min(Math_Max(qx,qz),0.0);\n    float cap=Math_Max(-y-h*.5,y-h*.5);\n    float body=Math_Max(shell,cap)-th*.08;\n    if(concavity>.001) {\n        \n        float cx=x/Math_Max(w*.73,.002);\n        float cy=(y+h*.23)/Math_Max(h*.34,.002);\n        float cz=(z-th*.35)/Math_Max(th*(.80+.70*concavity),.002);\n        float cavity=(sqrtf(cx*cx+cy*cy+cz*cz)-1.0)*Math_Min(w*.73,h*.34);\n        body=Math_Max(body,-cavity);\n    }\n    return body;\n}\nfloat SDF_TaperedPinna(Vector3 point,Vector3 shape,Vector3 direction,float tipFraction,float concavity) {\n    Vector3 up=Vec3_Normalize(direction);\n    Vector3 reference=fabsf(up.z)<.9?Vec3_Create(0,0,1):Vec3_Create(1,0,0);\n    Vector3 side=Vec3_Normalize(Vec3_Cross(up,reference));\n    Vector3 normal=Vec3_Cross(side,up);\n    return SDF_CurvedPinna(point,shape,up,side,normal,tipFraction,concavity,\n                            shape.x*.05,.25,1.0,0.0,.35,.4,.5);\n}\nfloat SDF_Sphere(Vector3 point, float radius) {\n    if (radius <= 0.0001) return Vec3_Length(point);\n    return Vec3_Length(point) - radius;\n}\nfloat SDF_Ellipsoid(Vector3 p, Vector3 r) {\n    \n    float rx = Math_Max(r.x, 0.0001);\n    float ry = Math_Max(r.y, 0.0001);\n    float rz = Math_Max(r.z, 0.0001);\n\n    Vector3 invR = Vec3_Create(1.0 / rx, 1.0 / ry, 1.0 / rz);\n    Vector3 invR2 = Vec3_Create(invR.x * invR.x, invR.y * invR.y, invR.z * invR.z);\n\n    Vector3 scaledP = Vec3_Create(p.x * invR.x, p.y * invR.y, p.z * invR.z);\n    float k0 = Vec3_Length(scaledP);\n\n    Vector3 scaledP2 = Vec3_Create(p.x * invR2.x, p.y * invR2.y, p.z * invR2.z);\n    float k1 = Vec3_Length(scaledP2);\n\n    if (k0 < 1e-6 || k1 < 1e-6) {\n        float minR = Math_Min(rx, Math_Min(ry, rz));\n        return -minR;\n    }\n    return k0 * (k0 - 1.0) / k1;\n}\nfloat SDF_Capsule(Vector3 p, Vector3 a, Vector3 b, float radius) {\n    float r = Math_Max(radius, 0.0001);\n    Vector3 pa = Vec3_Sub(p, a);\n    Vector3 ba = Vec3_Sub",
"(b, a);\n\n    float baLengthSq = Vec3_Dot(ba, ba);\n    if (baLengthSq < 1e-8) {\n        return Vec3_Length(pa) - r;\n    }\n\n    float h = Math_Clamp01(Vec3_Dot(pa, ba) / baLengthSq);\n    Vector3 projection = Vec3_Sub(pa, Vec3_Scale(ba, h));\n    return Vec3_Length(projection) - r;\n}\nfloat SDF_TaperedCapsuleApprox(Vector3 p, Vector3 a, Vector3 b, float r1, float r2) {\n    r1 = Math_Max(r1, 0.0001);\n    r2 = Math_Max(r2, 0.0001);\n\n    Vector3 pa = Vec3_Sub(p, a);\n    Vector3 ba = Vec3_Sub(b, a);\n\n    float baLengthSq = Vec3_Dot(ba, ba);\n    if (baLengthSq < 1e-8) {\n        return Vec3_Length(pa) - r1;\n    }\n\n    float h = Math_Clamp01(Vec3_Dot(pa, ba) / baLengthSq);\n    float r = Math_Lerp(r1, r2, h);\n    Vector3 projection = Vec3_Sub(pa, Vec3_Scale(ba, h));\n    return Vec3_Length(projection) - r;\n}\nfloat SDF_TaperedEllipticalCapsuleApprox(Vector3 p, Vector3 a, Vector3 b, Vector3 ra, Vector3 rb) {\n    Vector3 ba=Vec3_Sub(b,a); float lengthSquared=Vec3_Dot(ba,ba);\n    float t=lengthSquared>1e-8?Math_Clamp01(Vec3_Dot(Vec3_Sub(p,a),ba)/lengthSquared):0.0;\n    Vector3 center=Vec3_Lerp(a,b,t);\n    Vector3 radii=Vec3_Lerp(ra,rb,t);\n    float body=SDF_Ellipsoid(Vec3_Sub(p,center),radii);\n    float capA=SDF_Ellipsoid(Vec3_Sub(p,a),ra);\n    float capB=SDF_Ellipsoid(Vec3_Sub(p,b),rb);\n    return Math_Min(body,Math_Min(capA,capB));\n}\nfloat SDF_ThreeSectionEllipticalLoftApprox(Vector3 p,\n                                           Vector3 root, Vector3 mid, Vector3 tip,\n                                           Vector3 rootRadii, Vector3 midRadii,\n                                           Vector3 tipRadii, float blend) {\n    float rear = SDF_TaperedEllipticalCapsuleApprox(p, root, mid, rootRadii, midRadii);\n    float front = SDF_TaperedEllipticalCapsuleApprox(p, mid, tip, midRadii, tipRadii);\n    float k = Math_Max(blend, 0.0);\n    if (k <= 0.0001) return Math_Min(rear, front);\n    float h = Math_Clamp01(0.5 + 0.5 * (front - rear) / k);\n    return Math_Lerp(front, rear, h) - k * h ",
"* (1.0 - h);\n}\nfloat SDF_TaperedEllipticalSegmentApprox(Vector3 p, Vector3 a, Vector3 b,\n                                         float widthA, float heightA,\n                                         float widthB, float heightB) {\n    Vector3 axis = Vec3_Sub(b, a);\n    float length = Vec3_Length(axis);\n    if (length < 1e-6) return SDF_Ellipsoid(Vec3_Sub(p, a),\n        Vec3_Create(Math_Max(widthA, .0001), Math_Max(heightA, .0001), Math_Max(widthA, .0001)));\n    Vector3 forward = Vec3_Scale(axis, 1.0 / length);\n    Vector3 referenceUp = fabsf(forward.y) > .94 ? Vec3_Create(1,0,0) : Vec3_Create(0,1,0);\n    Vector3 side = Vec3_Normalize(Vec3_Cross(referenceUp, forward));\n    Vector3 up = Vec3_Normalize(Vec3_Cross(forward, side));\n    Vector3 pa = Vec3_Sub(p, a);\n    float along = Vec3_Dot(pa, forward);\n    float t = Math_Clamp01(along / length);\n    float width = Math_Max(Math_Lerp(widthA, widthB, t), .0001);\n    float height = Math_Max(Math_Lerp(heightA, heightB, t), .0001);\n    float cap = Math_Min(width, height);\n    float outsideAxis = along < 0.0 ? along : (along > length ? along - length : 0.0);\n    Vector3 center = Vec3_Add(a, Vec3_Scale(forward, Math_Clamp(along, 0.0, length)));\n    Vector3 radial = Vec3_Sub(p, center);\n    float sx = Vec3_Dot(radial, side) / width;\n    float sy = Vec3_Dot(radial, up) / height;\n    float sz = outsideAxis / cap;\n    return (sqrtf(sx*sx + sy*sy + sz*sz) - 1.0) * Math_Min(width, height);\n}\nfloat SDF_RoundedSlotExtruded(Vector3 p, float halfWidth, float halfHeight, float halfDepth) {\n    float hw = Math_Max(halfWidth, 0.0001);\n    float hh = Math_Max(halfHeight, 0.0001);\n    float hd = Math_Max(halfDepth, 0.0001);\n\n    float radius = hh;\n    float straightHalf = Math_Max(hw - radius, 0.0);\n\n    float qx = Math_Max(fabsf(p.x) - straightHalf, 0.0);\n    float profileDist = sqrtf(qx * qx + p.y * p.y) - radius;\n    float depthDist = fabsf(p.z) - hd;\n\n    float maxP = Math_Max(profileDist, 0.0);\n    float maxD = Math_Max(depthDist, 0.0);",
"\n    float outside = sqrtf(maxP * maxP + maxD * maxD);\n    float inside = Math_Min(Math_Max(profileDist, depthDist), 0.0);\n\n    return outside + inside;\n}\nfloat SDF_Hermite(float a,float b,float da,float db,float h,float t) {\n    float t2=t*t,t3=t2*t;\n    return (2*t3-3*t2+1)*a+(t3-2*t2+t)*h*da+(-2*t3+3*t2)*b+(t3-t2)*h*db;\n}\nfloat SDF_SmoothUnion(float a, float b, float k) {\n    if (k <= 0.0001) return Math_Min(a, b);\n    float h = Math_Clamp01(0.5 + 0.5 * (b - a) / k);\n    \n    if(h>=1.0)return a;\n    if(h<=0.0)return b;\n    return Math_Lerp(b, a, h) - k * h * (1.0 - h);\n}\nfloat SDF_SmoothSubtract(float body, float cutter, float k) {\n    if (k <= 0.0001) return Math_Max(body, -cutter);\n    float h = Math_Clamp01(0.5 - 0.5 * (body + cutter) / k);\n    return Math_Lerp(body, -cutter, h) + k * h * (1.0 - h);\n}float SDF_EllipticalSweepZ(vec3 p,int base,int count) {\n    int i=0;\n    while(i<count-2 && p.z<dataAt(base+2*(i+1)).z) ++i;\n    vec4 a=dataAt(base+2*i), b=dataAt(base+2*(i+1));\n    vec4 ar=dataAt(base+2*i+1), br=dataAt(base+2*(i+1)+1);\n    float h=b.z-a.z,t=clamp((p.z-a.z)/h,0.0,1.0);\n    float w=max(SDF_Hermite(a.w,b.w,ar.y,br.y,h,t),.0001);\n    float v=max(SDF_Hermite(ar.x,br.x,ar.z,br.z,h,t),.0001);\n    float y=SDF_Hermite(a.y,b.y,ar.w,br.w,h,t),x=mix(a.x,b.x,t);\n    float first=dataAt(base).z,last=dataAt(base+2*(count-1)).z;\n    float z=p.z>first?p.z-first:p.z<last?p.z-last:0.0;\n    float r=min(w,v);\n    return (length(vec3((p.x-x)/w,(p.y-y)/v,z/r))-1.0)*r;\n}\nvoid MonsterSDF_GetBasinParams(int mouth, out Vector3 outCenter, out Vector3 outRadii, out float outK) {\n    float h = M_seamScale(mouth);\n    if (h < 1e-4) h = Math_Max(M_hingeRadius(mouth), Math_Max(M_throatRadius(mouth), M_entranceHalfExtents(mouth).y * 2.0));\n    float rx = M_jawRadii(mouth).x;\n    float ry = M_jawRadii(mouth).y;\n    float rz = M_jawRadii(mouth).z;\n    float basinHalfY = h * 0.28;\n    float jawTop = M_jawCenterLocal(mouth).y + ry;\n    float basinTop = jawTop + h * 0.30;\n    float cy ",
"= basinTop - basinHalfY;\n    Vector3 center = Vec3_Create(M_jawCenterLocal(mouth).x, cy, M_jawCenterLocal(mouth).z + rz * 0.05);\n    Vector3 radii = Vec3_Create(rx * 0.60, basinHalfY, rz * 0.68);\n    float minWallX = h * 0.22;\n    if (rx - radii.x < minWallX) radii.x = Math_Max(rx - minWallX, rx * 0.45);\n    float minWallZ = h * 0.18;\n    if (rz - radii.z < minWallZ) radii.z = Math_Max(rz - minWallZ, rz * 0.50);\n    float k = h * 0.18;\n    if (k < 0.010) k = 0.010;\n    if (k > h * 0.28) k = h * 0.28;\n    outCenter = center;\n    outRadii = radii;\n    outK = k;\n}\nfloat MonsterSDF_EvalJawBase(int mouth, Vector3 localP) {\n    if (M_sweptSkull(mouth)) {\n        \n        float lip=M_entranceCenterLocal(mouth).y-M_entranceHalfExtents(mouth).y;\n        float depthScale=Math_Clamp(M_jawRadii(mouth).y*2.0 / Math_Max(M_faceRootRadii(mouth).y,.0001),.4,1.4);\n        Vector3 jawPoint=localP;\n        jawPoint.y=lip+(localP.y-lip)/depthScale;\n        \n        float envelope=SDF_EllipticalSweepZ(jawPoint,M_headStations(mouth),6)*Math_Min(depthScale,1.0);\n        float oralPlane=localP.y-lip;\n        float rearPlane=M_hingeCenterLocal(mouth).z-localP.z;\n        return Math_Max(envelope,Math_Max(oralPlane,rearPlane));\n    }\n    if(M_lowerBeak(mouth)) {\n        Vector3 root=Vec3_Add(M_hingeCenterLocal(mouth),Vec3_Create(0,-M_jawRadii(mouth).y*.12,M_jawRadii(mouth).z*.08));\n        Vector3 tip=Vec3_Create(M_jawCenterLocal(mouth).x,M_jawCenterLocal(mouth).y,M_jawCenterLocal(mouth).z+M_jawRadii(mouth).z);\n        Vector3 rootRadii=Vec3_Create(M_jawRadii(mouth).x,M_jawRadii(mouth).y,M_jawRadii(mouth).x*.42);\n        Vector3 tipRadii=Vec3_Create(M_jawRadii(mouth).x*.20,M_jawRadii(mouth).y*.28,M_jawRadii(mouth).x*.18);\n        return SDF_TaperedEllipticalCapsuleApprox(localP,root,tip,rootRadii,tipRadii);\n    }\n    if(M_taperedMandible(mouth)) {\n        float rx=M_jawRadii(mouth).x,ry=M_jawRadii(mouth).y,rz=M_jawRadii(mouth).z;\n        Vector3 leftRear=Vec3_Add(M_hingeCenterLocal(mouth),Vec3",
"_Create(rx*.76,-ry*.18,0));\n        Vector3 rightRear=leftRear;rightRear.x*=-1;\n        Vector3 leftTip=Vec3_Create(rx*.08,M_jawCenterLocal(mouth).y+ry*.64,M_jawCenterLocal(mouth).z+rz*.96);\n        Vector3 rightTip=leftTip;rightTip.x*=-1;\n        float rearW=Math_Max(M_jawRearMass(mouth)*.62,rx*.15),tipW=Math_Max(rearW*.58,rx*.055);\n        float left=SDF_TaperedEllipticalSegmentApprox(localP,leftRear,leftTip,rearW,ry*.72,tipW,ry*.34);\n        float right=SDF_TaperedEllipticalSegmentApprox(localP,rightRear,rightTip,rearW,ry*.72,tipW,ry*.34);\n        float bridge=SDF_TaperedEllipticalSegmentApprox(localP,leftTip,rightTip,tipW,ry*.46,tipW,ry*.46);\n        Vector3 rearRadii=Vec3_Create(rearW*1.25,ry*.82,rearW*1.10);\n        float rearLeft=SDF_Ellipsoid(Vec3_Sub(localP,leftRear),rearRadii);\n        float rearRight=SDF_Ellipsoid(Vec3_Sub(localP,rightRear),rearRadii);\n        float k=Math_Max(M_seamScale(mouth)*.10,.006);\n        float result=SDF_SmoothUnion(left,right,k);result=SDF_SmoothUnion(result,bridge,k);\n        result=SDF_SmoothUnion(result,rearLeft,k);result=SDF_SmoothUnion(result,rearRight,k);\n        \n        Vector3 floorRear=Vec3_Create(0,leftRear.y-ry*.18,leftRear.z);\n        Vector3 floorTip=Vec3_Create(0,leftTip.y-ry*.10,leftTip.z);\n        float floor=SDF_TaperedEllipticalSegmentApprox(localP,floorRear,floorTip,\n            rx*.70,ry*.40,tipW,ry*.32);\n        return SDF_SmoothUnion(result,floor,k);\n    }\n    \n    Vector3 dMain = Vec3_Sub(localP, M_jawCenterLocal(mouth));\n    Vector3 radiiMain = Vec3_Create(M_jawRadii(mouth).x, M_jawRadii(mouth).y, M_jawRadii(mouth).z * 0.96);\n    float main = SDF_Ellipsoid(dMain, radiiMain);\n    Vector3 rearCenter = Vec3_Add(M_hingeCenterLocal(mouth), Vec3_Create(0.0, -M_jawRadii(mouth).y * 0.14, M_jawRadii(mouth).z * 0.22));\n    float rearR = M_jawRearMass(mouth);\n    // elipsoide posterior scale-relative\n    Vector3 rearRadii = Vec3_Create(rearR * 0.95, rearR * 0.85, rearR * 0.92);\n    float rear = SDF_Ellipsoid(Vec3_",
"Sub(localP, rearCenter), rearRadii);\n    Vector3 muscleCenter = Vec3_Add(M_jawCenterLocal(mouth), Vec3_Create(0.0, -M_jawMuscle(mouth) * 0.38, -M_jawRadii(mouth).z * 0.10));\n    Vector3 muscleRadii = Vec3_Create(M_jawRadii(mouth).x * 0.84 + M_jawMuscle(mouth) * 0.12, M_jawMuscle(mouth) * 0.52, M_jawRadii(mouth).z * 0.42);\n    float muscle = SDF_Ellipsoid(Vec3_Sub(localP, muscleCenter), muscleRadii);\n    float h = M_seamScale(mouth); if (h < 1e-4) h = M_hingeRadius(mouth);\n    float k = h * 0.18; if (k < 0.012) k = 0.012; if (k > h * 0.32) k = h * 0.32;\n    float result = SDF_SmoothUnion(main, rear, k);\n    result = SDF_SmoothUnion(result, muscle, k);\n    return result;\n}\nfloat MonsterSDF_EvalTongueDistance(int mouth, Vector3 localP) {\n    if(!M_taperedMandible(mouth)) return 1e6;\n    float tDev = Math_Clamp01((M_cephalicDevelopment(mouth) - 0.25) / 0.50);\n    if(tDev <= 0.001) return 1e6;\n    if (M_sweptSkull(mouth)) {\n        float plane=M_entranceCenterLocal(mouth).y-M_entranceHalfExtents(mouth).y;\n        float height=M_faceMidRadii(mouth).y*.08*tDev;\n        Vector3 root=M_faceRootLocal(mouth),tip=M_faceTipLocal(mouth);\n        root.y=plane-height*.3; tip.y=root.y;\n        tip.z=Math_Lerp(root.z,tip.z,.75);\n        return SDF_TaperedEllipticalSegmentApprox(localP,root,tip,\n            M_faceRootRadii(mouth).x*.32*tDev,height,\n            M_faceTipRadii(mouth).x*.30*tDev,height*.65);\n    }\n    float rx=M_jawRadii(mouth).x, ry=M_jawRadii(mouth).y, rz=M_jawRadii(mouth).z;\n    Vector3 leftRear=Vec3_Add(M_hingeCenterLocal(mouth),Vec3_Create(rx*.76,-ry*.18,0));\n    Vector3 leftTip=Vec3_Create(rx*.08,M_jawCenterLocal(mouth).y+ry*.64,M_jawCenterLocal(mouth).z+rz*.96);\n    Vector3 floorRear=Vec3_Create(0,leftRear.y-ry*.18,leftRear.z);\n    Vector3 floorTip=Vec3_Create(0,leftTip.y-ry*.10,leftTip.z);\n    float spanZ=floorTip.z-floorRear.z;\n    Vector3 tongueRoot=Vec3_Create(0,floorRear.y+ry*(0.44*tDev),floorRear.z+spanZ*.18);\n    Vector3 tongueTip=Vec3_Create(0,floorTip.y+r",
"y*(0.36*tDev),floorRear.z+spanZ*.74);\n    float rootW=rx*.32*tDev, rootH=ry*.20*tDev;\n    float tipW=rx*.14*tDev, tipH=ry*.10*tDev;\n    return SDF_TaperedEllipticalSegmentApprox(localP,tongueRoot,tongueTip,rootW,rootH,tipW,tipH);\n}\nfloat MonsterSDF_EvalSeamDistance(int mouth, Vector3 localP) {\n    float h = M_seamScale(mouth);\n    if (h < 1e-4) h = Math_Max(M_hingeRadius(mouth), Math_Max(M_throatRadius(mouth), M_entranceHalfExtents(mouth).y * 2.0));\n    float k = h * 0.26; if (k < 0.012) k = 0.012; if (k > h*0.38) k = h*0.38;\n    float rHinge = h * 0.26;\n    float rGular = h * 0.30;\n    float rPivotGular = h * 0.28;\n    float left = SDF_Capsule(localP, M_seamSkullLeftLocal(mouth), M_seamJawLeftClosedLocal(mouth), rHinge);\n    float right = SDF_Capsule(localP, M_seamSkullRightLocal(mouth), M_seamJawRightClosedLocal(mouth), rHinge);\n    if(M_taperedMandible(mouth)) {\n        \n        Vector3 gHalf=Vec3_Create(h*1.58,h*.62,h*.88);\n        float gular=SDF_Ellipsoid(Vec3_Sub(localP,M_seamGularLocal(mouth)),gHalf);\n        float pivotPad=SDF_Sphere(Vec3_Sub(localP,M_hingeCenterLocal(mouth)),h*.38);\n        float res=SDF_SmoothUnion(left,right,k);\n        res=SDF_SmoothUnion(res,gular,k);\n        return SDF_SmoothUnion(res,pivotPad,k);\n    }\n    float jlG = SDF_Capsule(localP, M_seamJawLeftClosedLocal(mouth), M_seamGularLocal(mouth), rGular);\n    float jrG = SDF_Capsule(localP, M_seamJawRightClosedLocal(mouth), M_seamGularLocal(mouth), rGular);\n    float midG = SDF_Capsule(localP, M_seamJawAnchorLocal(mouth), M_seamGularLocal(mouth), rGular);\n    float pivotG = SDF_Capsule(localP, M_hingeCenterLocal(mouth), M_seamGularLocal(mouth), rPivotGular);\n    Vector3 gHalf = Vec3_Create(h * 0.74, h * 0.68, h * 0.72);\n    float gular = SDF_Ellipsoid(Vec3_Sub(localP, M_seamGularLocal(mouth)), gHalf);\n    float pivotPad = SDF_Sphere(Vec3_Sub(localP, M_hingeCenterLocal(mouth)), h * 0.30);\n    float res = SDF_SmoothUnion(left, right, k);\n    res = SDF_SmoothUnion(res, jlG, k);\n    res = ",
"SDF_SmoothUnion(res, jrG, k);\n    res = SDF_SmoothUnion(res, midG, k);\n    res = SDF_SmoothUnion(res, pivotG, k);\n    res = SDF_SmoothUnion(res, gular, k);\n    res = SDF_SmoothUnion(res, pivotPad, k);\n    return res;\n}\nfloat MonsterSDF_EvalJawCarvedDistance(int mouth, Vector3 point) {\n    float body = MonsterSDF_EvalJawBase(mouth, point);\n    if(M_taperedMandible(mouth)) {\n        float tongue = MonsterSDF_EvalTongueDistance(mouth, point);\n        float k = Math_Max(M_seamScale(mouth) * .08, .005);\n        return SDF_SmoothUnion(body, tongue, k);\n    }\n    Vector3 basinCenter, basinRadii; float k;\n    MonsterSDF_GetBasinParams(mouth, basinCenter, basinRadii, k);\n    float oral = SDF_Ellipsoid(Vec3_Sub(point, basinCenter), basinRadii);\n    return SDF_SmoothSubtract(body, oral, k);\n}\nfloat MonsterSDF_EvalPosedMouthDistance(int mouth,Vector3 localP) {\n    float scale=M_visualJawScale(mouth);\n    if(scale<.0001)return 1e6;\n    Vector3 pivot=M_visualJawPivot(mouth),rel=Vec3_Sub(localP,pivot);\n    float outside=Vec3_Length(rel)-M_visualJawBoundRadius(mouth);\n    if(outside>0)return Math_Max(outside,.01);\n    float angle=M_visualJawAngle(mouth),c=cosf(angle),s=sinf(angle);\n    Vector3 rest=Vec3_Add(pivot,Vec3_Scale(Vec3_Create(rel.x,c*rel.y+s*rel.z,-s*rel.y+c*rel.z),1.0/scale));\n    float jaw=MonsterSDF_EvalJawCarvedDistance(mouth,rest)*scale;\n    rest=Vec3_Add(pivot,Vec3_Scale(rel,1.0/scale));\n    float h=Math_Max(M_seamScale(mouth),.0001);\n    for(int iteration=0;iteration<6;++iteration) {\n        float skull=Math_Min(Vec3_Distance(rest,M_seamSkullLeftLocal(mouth)),Vec3_Distance(rest,M_seamSkullRightLocal(mouth)));\n        skull=Math_Min(skull,Vec3_Distance(rest,M_seamGularLocal(mouth)));\n        skull=Math_Min(skull,Vec3_Distance(rest,pivot));\n        float lower=Math_Min(Vec3_Distance(rest,M_seamJawLeftClosedLocal(mouth)),Vec3_Distance(rest,M_seamJawRightClosedLocal(mouth)));\n        lower=Math_Min(lower,Vec3_Distance(rest,M_seamJawAnchorLocal(mouth)));\n        float w",
"=Math_Clamp01(skull/(skull+lower+h*1e-6));\n        float a=angle*w*w*(3.0-2.0*w);c=cosf(a);s=sinf(a);\n        rest=Vec3_Add(pivot,Vec3_Scale(Vec3_Create(rel.x,c*rel.y+s*rel.z,-s*rel.y+c*rel.z),1.0/scale));\n    }\n    return Math_Min(jaw,MonsterSDF_EvalSeamDistance(mouth,rest)*scale);\n}\nfloat MonsterSDF_EvalConnectorDistance(int conn, Vector3 point) {\n    if(C_length(conn)<1e-6) return SDF_Ellipsoid(Vec3_Sub(point,C_a(conn)),\n        Vec3_Create(C_widthA(conn),C_heightA(conn),C_widthA(conn)));\n    Vector3 p=Vec3_Sub(point,C_a(conn));\n    float along=Vec3_Dot(p,C_forward(conn)),t=Math_Clamp01(along/C_length(conn));\n    float w=Math_Max(Math_Lerp(C_widthA(conn),C_widthB(conn),t)+C_widthBulge(conn)*4*t*(1-t),.0001);\n    float h=Math_Max(Math_Lerp(C_heightA(conn),C_heightB(conn),t)+C_heightBulge(conn)*4*t*(1-t),.0001),r=Math_Min(w,h);\n    float x=Vec3_Dot(p,C_side(conn))/w,y=Vec3_Dot(p,C_up(conn))/h;\n    float z=(along<0?along:along>C_length(conn)?along-C_length(conn):0)/r;\n    return (sqrtf(x*x+y*y+z*z)-1)*r;\n}\nfloat MonsterSDF_EvalMuzzleDistance(int mouth, Vector3 localP) {\n    return SDF_Ellipsoid(Vec3_Sub(localP, M_muzzleCenterLocal(mouth)), M_muzzleHalfExtents(mouth));\n}\nfloat MonsterSDF_EvalShallowCutter(Vector3 p,Vector3 center,Vector3 radii,\n                                           Vector3 normal,float depth) {\n    Vector3 rel=Vec3_Sub(p,center);\n    float ellipsoid=SDF_Ellipsoid(rel,radii);\n    float rearPlane=-Vec3_Dot(rel,normal)-Math_Max(depth,.001);\n    return Math_Max(ellipsoid,rearPlane);\n}\nfloat MonsterSDF_EvalOrbitCavities(int mouth,Vector3 p) {\n    if(!M_anatomicalHead(mouth))return 1e6;\n    \n    Vector3 leftCenter=Vec3_Add(M_leftOrbitCenterLocal(mouth),Vec3_Scale(M_leftOrbitNormal(mouth),M_orbitRadii(mouth).x*.18));\n    Vector3 rightCenter=Vec3_Add(M_rightOrbitCenterLocal(mouth),Vec3_Scale(M_rightOrbitNormal(mouth),M_orbitRadii(mouth).x*.18));\n    float left=MonsterSDF_EvalShallowCutter(p,leftCenter,M_orbitRadii(mouth),M_leftOrbitNormal(mouth),M_orbit",
"SocketDepth(mouth));\n    float right=MonsterSDF_EvalShallowCutter(p,rightCenter,M_orbitRadii(mouth),M_rightOrbitNormal(mouth),M_orbitSocketDepth(mouth));\n    float development=Math_Clamp01(M_cephalicDevelopment(mouth));\n    float weight=development*development*(3.0-2.0*development);\n    return Math_Min(left,right)+(1.0-weight)*M_orbitRadii(mouth).x*2.0;\n}\nfloat MonsterSDF_EvalNostrilCavities(int mouth,Vector3 p) {\n    if(!M_anatomicalHead(mouth))return 1e6;\n    \n    Vector3 leftNormal=Vec3_Normalize(Vec3_Create(1.0,.78,.12));\n    Vector3 rightNormal=leftNormal;rightNormal.x*=-1.0;\n    float depth=Math_Min(M_nostrilRadii(mouth).x,M_nostrilRadii(mouth).y)*.58;\n    float left=MonsterSDF_EvalShallowCutter(p,M_leftNostrilCenterLocal(mouth),M_nostrilRadii(mouth),leftNormal,depth);\n    float right=MonsterSDF_EvalShallowCutter(p,M_rightNostrilCenterLocal(mouth),M_nostrilRadii(mouth),rightNormal,depth);\n    float development=Math_Clamp01(M_cephalicDevelopment(mouth));\n    float weight=development*development*(3.0-2.0*development);\n    return Math_Min(left,right)+(1.0-weight)*M_nostrilRadii(mouth).x*2.0;\n}\nfloat MonsterSDF_EvalTympanumCavities(int mouth,Vector3 p) {\n    if(!M_anatomicalHead(mouth)||!M_hasTympana(mouth))return 1e6;\n    float left=MonsterSDF_EvalShallowCutter(p,M_leftTympanumCenterLocal(mouth),M_tympanumRadii(mouth),Vec3_Create(1,0,0),M_tympanumDepth(mouth));\n    float right=MonsterSDF_EvalShallowCutter(p,M_rightTympanumCenterLocal(mouth),M_tympanumRadii(mouth),Vec3_Create(-1,0,0),M_tympanumDepth(mouth));\n    return Math_Min(left,right)+(1.0-M_tympanumDevelopment(mouth))*M_tympanumRadii(mouth).y*2.0;\n}\nfloat MonsterSDF_EvalRostrumDistance(int mouth,Vector3 localP) {\n    if(!M_anatomicalHead(mouth))return MonsterSDF_EvalMuzzleDistance(mouth,localP);\n    return SDF_ThreeSectionEllipticalLoftApprox(localP,\n        M_faceRootLocal(mouth),M_faceMidLocal(mouth),M_faceTipLocal(mouth),\n        M_faceRootRadii(mouth),M_faceMidRadii(mouth),M_faceTipRadii(mouth),\n        ",
"M_faceRounding(mouth));\n}\nfloat MonsterSDF_EvalPeriorbitalDistance(int mouth,Vector3 localP) {\n    float k=Math_Max(M_headUnionSmoothness(mouth)*.24,.002);\n    float d=SDF_Ellipsoid(Vec3_Sub(localP,M_leftOrbitRimCenterLocal(mouth)),M_orbitRimRadii(mouth));\n    d=SDF_SmoothUnion(d,SDF_Ellipsoid(Vec3_Sub(localP,M_rightOrbitRimCenterLocal(mouth)),M_orbitRimRadii(mouth)),k);\n    d=SDF_SmoothUnion(d,SDF_Ellipsoid(Vec3_Sub(localP,M_leftBrowCenterLocal(mouth)),M_browRadii(mouth)),k);\n    d=SDF_SmoothUnion(d,SDF_Ellipsoid(Vec3_Sub(localP,M_rightBrowCenterLocal(mouth)),M_browRadii(mouth)),k);\n    if(M_eyelidCoverage(mouth)<=.001)return d;\n    \n    for(int eye=0;eye<2;++eye){\n        Vector3 c=eye!=0?M_rightOrbitCenterLocal(mouth):M_leftOrbitCenterLocal(mouth);\n        Vector3 n=eye!=0?M_rightOrbitNormal(mouth):M_leftOrbitNormal(mouth);\n        Vector3 right=Vec3_Normalize(Vec3_Cross(Vec3_Create(0,1,0),n));\n        Vector3 up=Vec3_Normalize(Vec3_Cross(n,right));\n        float rx=M_orbitRadii(mouth).x*.84,ry=M_orbitRadii(mouth).y*.86;\n        float lidR=Math_Max(ry*.105,.012),front=M_orbitRadii(mouth).x*.44;\n        for(int lid=0;lid<2;++lid){\n            Vector3 prev=Vec3_Add(c,Vec3_Scale(n,front));\n            for(int s=1;s<=4;++s){\n                float t=s==1?.25:s==2?.50:s==3?.75:1.0,x=(t*2.0-1.0)*rx;\n                float arcScale=-.19;\n                if(lid==0)arcScale=.33;\n                float arc=sinf(3.14159265*t)*arcScale*ry;\n                Vector3 q=Vec3_Add(c,Vec3_Add(Vec3_Scale(right,x),Vec3_Add(Vec3_Scale(up,arc),Vec3_Scale(n,front))));\n                float band=SDF_Capsule(localP,prev,q,lidR);\n                d=SDF_SmoothUnion(d,band,k*.45);prev=q;\n            }\n        }\n    }\n    return d;\n}\nfloat MonsterSDF_EvalNeckCollarDistance(int mouth,Vector3 localP) {\n    float seg1=SDF_TaperedEllipticalSegmentApprox(localP,\n        M_neckCollarRootLocal(mouth),M_neckCollarMidLocal(mouth),\n        M_neckCollarRootRadii(mouth).x,M_neckCollarRootRadii(mouth).y,\n     ",
"   M_neckCollarMidRadii(mouth).x,M_neckCollarMidRadii(mouth).y);\n    float seg2=SDF_TaperedEllipticalSegmentApprox(localP,\n        M_neckCollarMidLocal(mouth),M_neckCollarTipLocal(mouth),\n        M_neckCollarMidRadii(mouth).x,M_neckCollarMidRadii(mouth).y,\n        M_neckCollarTipRadii(mouth).x,M_neckCollarTipRadii(mouth).y);\n    float blend=Math_Max(M_headBodySmoothness(mouth)*.8,.02);\n    return SDF_SmoothUnion(seg1,seg2,blend);\n}\nfloat MonsterSDF_EvalUpperHeadDistance(int mouth, Vector3 localP) {\n    if (M_anatomicalHead(mouth)) {\n        float dev = M_cephalicDevelopment(mouth);\n        float k = Math_Max(M_headUnionSmoothness(mouth), .005);\n        float cranium = SDF_Ellipsoid(Vec3_Sub(localP, M_craniumCenterLocal(mouth)), M_craniumRadii(mouth));\n        float d = cranium;\n        {\n            float face = MonsterSDF_EvalRostrumDistance(mouth, localP);\n            float skull = M_sweptSkull(mouth) ? SDF_EllipticalSweepZ(localP, M_headStations(mouth), 6) : SDF_SmoothUnion(d, face, k);\n            \n            d = skull;\n            float featK = k;\n            {\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_leftTemporalCenterLocal(mouth)), M_temporalRadii(mouth)), featK * .38);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_rightTemporalCenterLocal(mouth)), M_temporalRadii(mouth)), featK * .38);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_leftMaxillaryCenterLocal(mouth)), M_maxillaryRadii(mouth)), featK * .34);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_rightMaxillaryCenterLocal(mouth)), M_maxillaryRadii(mouth)), featK * .34);\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_cheekCenterLocal(mouth)), M_cheekRadii(mouth)), featK * .42);\n                Vector3 rightCheek = M_cheekCenterLocal(mouth); rightCheek.x *= -1.0;\n                d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, rightCheek), M_cheekRadii(mouth)), featK * .",
"42);\n                d = SDF_SmoothUnion(d, MonsterSDF_EvalPeriorbitalDistance(mouth, localP), featK * .85);\n            }\n        }\n        d = SDF_SmoothUnion(d, MonsterSDF_EvalNeckCollarDistance(mouth, localP), M_headBodySmoothness(mouth));\n        if (M_hasNasalPad(mouth)) d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_noseCenterLocal(mouth)), M_noseRadii(mouth)), k * .35 * dev);\n        if (M_hasEars(mouth)) {\n            d = SDF_SmoothUnion(d, SDF_CurvedPinna(Vec3_Sub(localP, M_leftEarCenterLocal(mouth)), M_earShape(mouth), M_earDirection(mouth),M_leftEarSide(mouth),M_leftEarNormal(mouth), M_earTipFraction(mouth), M_earConcavity(mouth),M_earLongitudinalCurve(mouth),M_earRootRoll(mouth),M_earTipRoundness(mouth),M_earFold(mouth),M_earRootFlare(mouth),M_earMarginBow(mouth),M_earMarginAsymmetry(mouth)), k * .42 * dev);\n            d = SDF_SmoothUnion(d, SDF_CurvedPinna(Vec3_Sub(localP, M_rightEarCenterLocal(mouth)), M_earShape(mouth), M_rightEarDirection(mouth),M_rightEarSide(mouth),M_rightEarNormal(mouth), M_earTipFraction(mouth), M_earConcavity(mouth),M_earLongitudinalCurve(mouth),M_earRootRoll(mouth),M_earTipRoundness(mouth),M_earFold(mouth),M_earRootFlare(mouth),-M_earMarginBow(mouth),1.0-M_earMarginAsymmetry(mouth)), k * .42 * dev);\n        }\n        if (M_sweptSkull(mouth)) {\n            float oralPlane = M_entranceCenterLocal(mouth).y + M_entranceHalfExtents(mouth).y - localP.y;\n            float rearPlane = localP.z - (M_entranceCenterLocal(mouth).z-M_entranceHalfExtents(mouth).z);\n            float sidePlane = M_entranceHalfExtents(mouth).x + M_rimBevel(mouth) - fabsf(localP.x);\n            d = Math_Max(d, Math_Min(oralPlane, Math_Min(rearPlane, sidePlane)));\n        }\n        return d;\n    }\n    float d = SDF_Ellipsoid(Vec3_Sub(localP, M_craniumCenterLocal(mouth)), M_craniumRadii(mouth));\n    d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_snoutCenterLocal(mouth)), M_snoutRadii(mouth)), 0.08);\n    d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec",
"3_Sub(localP, M_cheekCenterLocal(mouth)), M_cheekRadii(mouth)), 0.06);\n    d = SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, Vec3_Create(-M_cheekCenterLocal(mouth).x, M_cheekCenterLocal(mouth).y, M_cheekCenterLocal(mouth).z)), M_cheekRadii(mouth)), 0.06);\n    return SDF_SmoothUnion(d, SDF_Ellipsoid(Vec3_Sub(localP, M_leftBrowCenterLocal(mouth)), M_browRadii(mouth)), 0.05);\n}\n// Trazado del mismo campo compilado que utiliza el mallador CPU.\nuniform vec3 cameraPosition, cameraForward, cameraRight, cameraUp;\nuniform vec3 boundsMin, boundsMax;\nuniform vec2 viewportSize;\nuniform float tanHalfFov, aspectRatio, hitTolerance;\nuniform mat4 viewProjection;\nout vec4 fragmentColor;\n\n// Intervalo cerrado; para direcciones casi paralelas se conserva todo el\n// desplazamiento del segmento, sin dividir por cero ni descartar incertidumbre.\nbool rayBox(vec3 ro,vec3 rd,vec3 lo,vec3 hi,inout float start,inout float end) {\n    for(int axis=0;axis<3;++axis) {\n        if(abs(rd[axis])<1e-8) {\n            float a=ro[axis]+rd[axis]*start,b=ro[axis]+rd[axis]*end;\n            if(max(a,b)<lo[axis]||min(a,b)>hi[axis])return false;\n        } else {\n            float a=(lo[axis]-ro[axis])/rd[axis],b=(hi[axis]-ro[axis])/rd[axis];\n            start=max(start,min(a,b));end=min(end,max(a,b));\n            if(start>end)return false;\n        }\n    }\n    return true;\n}\nbool rayIntersectsAABB(vec3 ro,vec3 rd,vec3 lo,vec3 hi,float start,float end) {\n    if(any(isnan(lo))||any(isnan(hi))||any(isinf(lo))||any(isinf(hi))||any(greaterThan(lo,hi)))return true;\n    return rayBox(ro,rd,lo,hi,start,end);\n}\n// Casos degenerados ejecutados por --validate-gpu con la misma funci\u00f3n GLSL.\nbool validateRayBoxes() {\n    vec3 lo=vec3(-1),hi=vec3(1);\n    if(!rayIntersectsAABB(vec3(2,0,0),vec3(-1,0,0),lo,hi,0.0,4.0))return false;\n    if(!rayIntersectsAABB(vec3(0),vec3(0,1,0),lo,hi,0.0,4.0))return false;\n    if(!rayIntersectsAABB(vec3(1,0,0),vec3(0,1,0),lo,hi,0.0,1.0))return false;\n    if(rayIntersectsAABB(vec3(2,0,0),vec",
"3(0,1,0),lo,hi,0.0,4.0))return false;\n    if(rayIntersectsAABB(vec3(2,0,0),vec3(-1,0,0),lo,hi,0.0,.5))return false;\n    if(!rayIntersectsAABB(vec3(2,0,0),vec3(-1e-9,0,0),lo,hi,0.0,2e9))return false;\n    return true;\n}\n// Agregados sin l\u00edmite de bocas: una intersecci\u00f3n activa toda la fase.\n// Las normales reutilizan estos indicadores, nunca clasifican puntos vecinos.\nbool rayHeadActive=true,rayMouthActive=true,rayJawActive=true;\nvoid classifyRay(vec3 rd,float start,float end) {\n    rayHeadActive=false;rayMouthActive=false;rayJawActive=false;\n    for(int i=0;i<mouthCount;++i) {\n        int m=mouthBase+i*M_STRIDE;\n        // La ruta heredada carece de una caja cef\u00e1lica certificada.\n        if(!M_anatomicalHead(m)||M_cephalicDevelopment(m)<0.0||M_cephalicDevelopment(m)>1.0){rayHeadActive=true;rayMouthActive=true;rayJawActive=true;continue;}\n        vec3 lo=M_headBounds_start(m),hi=M_headBounds_end(m);\n        rayHeadActive=rayHeadActive||rayIntersectsAABB(cameraPosition,rd,lo,hi,start,end);\n        rayMouthActive=rayMouthActive||rayIntersectsAABB(cameraPosition,rd,\n            M_influenceBounds_start(m),M_influenceBounds_end(m),start,end);\n        rayJawActive=rayJawActive||rayIntersectsAABB(cameraPosition,rd,\n            M_visualBounds_start(m),M_visualBounds_end(m),start,end);\n    }\n}\nbool pruneBox(vec3 p,vec3 lo,vec3 hi,float scale,float cutoff) {\n    vec3 d=max(max(lo-p,p-hi),vec3(0));\n    if(cutoff<=0.0)return any(greaterThan(d,vec3(0)));\n    float safe=cutoff/max(scale,.0001);\n    return dot(d,d)>=safe*safe;\n}\nvec4 joinField(vec4 a,vec4 b,float k) {\n    float h=k<=.0001?(a.w<b.w?1.0:0.0):clamp(.5+.5*(b.w-a.w)/k,0.0,1.0);\n    return vec4(mix(b.xyz,a.xyz,h),SDF_SmoothUnion(a.w,b.w,k));\n}\nvec4 cutField(vec4 a,float d,vec3 color,float k) {\n    float h=k<=.0001?(-d>a.w?1.0:0.0):clamp(.5-.5*(a.w+d)/k,0.0,1.0);\n    return vec4(mix(a.xyz,color,h),SDF_SmoothSubtract(a.w,d,k));\n}\nuniform int tileDataBase, tileColumns, validationMode, validationPointBase;\nint tileOffset, til",
"eCount;\nvec4 scene(vec3 p) {\n    vec4 result=vec4(1,1,1,1e6);\n    if(axialCount>1)result=vec4(connectorCount>0?C_color(connectorBase):vec3(1),SDF_EllipticalSweepZ(p,axialBase,axialCount));\n    for(int i=0;i<partCount;++i) {\n        int b=partBase+i*P_STRIDE;\n        result=joinField(result,vec4(P_color(b),SDF_Ellipsoid(p-P_center(b),P_radii(b))),bodySmoothness);\n    }\n    for(int i=0;i<tileCount;++i) {\n        int c=connectorBase+(tileOffset<0?i:int(dataAt(tileOffset+i/4)[i%4]))*C_STRIDE;\n        if(C_isHeadNeck(c)||(axialCount>1&&C_kind(c)==0))continue;\n        float k=C_localSmoothness(c);\n        if(pruneBox(p,C_bounds_start(c),C_bounds_end(c),C_distanceLowerBoundScale(c),result.w+k))continue;\n        result=joinField(result,vec4(C_color(c),MonsterSDF_EvalConnectorDistance(c,p)),k);\n    }\n    for(int i=0;i<mouthCount;++i) {\n        if(!rayHeadActive)continue;\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        if(!M_anatomicalHead(m))result=joinField(result,vec4(M_skinColor(m),MonsterSDF_EvalMuzzleDistance(m,local)),M_muzzleSmoothness(m));\n        vec3 headColor=M_skinColor(m);\n        if(M_hasNasalPad(m) && SDF_Ellipsoid(local-M_noseCenterLocal(m),M_noseRadii(m))<M_headUnionSmoothness(m)*.5) headColor=vec3(30,27,24)/255.0;\n        result=joinField(result,vec4(headColor,MonsterSDF_EvalUpperHeadDistance(m,local)),M_anatomicalHead(m)?M_headBodySmoothness(m):M_muzzleSmoothness(m));\n    }\n    for(int i=0;i<mouthCount;++i) {\n        if(!(rayHeadActive||rayMouthActive))continue;\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        if(rayMouthActive) {\n            vec3 ext=M_entranceHalfExtents(m),r=M_hostRadii(m);\n            float entrance=SDF_RoundedSlotExtruded(local-M_entranceCenterLocal(m),ext.x,ext.y,ext.z);\n            float cavity=SDF_Ellipsoid(local-M_cavityCenterLocal(m),M_cavityRadii(m));\n            if(M_sweptSkull(m)) {\n                float wall=max(ext.y*2.0,",
"M_faceMidRadii(m).x*.12);\n                cavity=max(cavity,SDF_EllipticalSweepZ(local,M_headStations(m),6)+wall);\n            }\n            float devMouth=clamp((M_cephalicDevelopment(m)-0.05)/0.25,0.0,1.0);\n            float cutter=SDF_SmoothUnion(entrance,cavity,M_entranceToCavitySmoothness(m))+(1.0-devMouth)*max(r.x,max(r.y,r.z))*2.0;\n            result=cutField(result,cutter,M_insideColor(m),M_rimBevel(m));\n        }\n        if(rayHeadActive&&M_anatomicalHead(m)) {\n            result=cutField(result,MonsterSDF_EvalOrbitCavities(m,local),vec3(24,28,19)/255.0,M_headUnionSmoothness(m)*.06);\n            result=cutField(result,MonsterSDF_EvalNostrilCavities(m,local),vec3(18,20,14)/255.0,M_headUnionSmoothness(m)*.04);\n            if(M_hasTympana(m))result=cutField(result,MonsterSDF_EvalTympanumCavities(m,local),vec3(25,24,16)/255.0,M_headUnionSmoothness(m)*.04);\n        }\n    }\n    for(int i=0;i<mouthCount;++i) {\n        if(!rayJawActive)continue;\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        float d=MonsterSDF_EvalPosedMouthDistance(m,local);\n        if(d<result.w) {\n            vec3 col=M_skinColor(m);\n            if(M_taperedMandible(m)) {\n                float scale=M_visualJawScale(m);\n                vec3 pivot=M_visualJawPivot(m),rel=local-pivot;\n                float angle=M_visualJawAngle(m),c=cos(angle),s=sin(angle);\n                vec3 rest=pivot+vec3(rel.x,c*rel.y+s*rel.z,-s*rel.y+c*rel.z)/max(scale,0.0001);\n                float tongueD=MonsterSDF_EvalTongueDistance(m,rest)*scale;\n                if(tongueD<=d+0.005)col=M_insideColor(m);\n            }\n            result=vec4(col,d);\n        }\n    }\n    return result;\n}\nfloat sceneDistance(vec3 p) {\n    float result=1e6;\n    if(axialCount>1)result=SDF_EllipticalSweepZ(p,axialBase,axialCount);\n    for(int i=0;i<partCount;++i) {\n        int b=partBase+i*P_STRIDE;\n        result=SDF_SmoothUnion(result,SDF_Ellipsoid(p-P_center(b),P_radii(b)),bodySmoothne",
"ss);\n    }\n    for(int i=0;i<tileCount;++i) {\n        int c=connectorBase+(tileOffset<0?i:int(dataAt(tileOffset+i/4)[i%4]))*C_STRIDE;\n        if(C_isHeadNeck(c)||(axialCount>1&&C_kind(c)==0))continue;\n        float k=C_localSmoothness(c);\n        if(pruneBox(p,C_bounds_start(c),C_bounds_end(c),C_distanceLowerBoundScale(c),result+k))continue;\n        result=SDF_SmoothUnion(result,MonsterSDF_EvalConnectorDistance(c,p),k);\n    }\n    for(int i=0;i<mouthCount;++i) {\n        if(!rayHeadActive)continue;\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        if(!M_anatomicalHead(m))result=SDF_SmoothUnion(result,MonsterSDF_EvalMuzzleDistance(m,local),M_muzzleSmoothness(m));\n        result=SDF_SmoothUnion(result,MonsterSDF_EvalUpperHeadDistance(m,local),M_anatomicalHead(m)?M_headBodySmoothness(m):M_muzzleSmoothness(m));\n    }\n    for(int i=0;i<mouthCount;++i) {\n        if(!(rayHeadActive||rayMouthActive))continue;\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        if(rayMouthActive) {\n            vec3 ext=M_entranceHalfExtents(m),r=M_hostRadii(m);\n            float entrance=SDF_RoundedSlotExtruded(local-M_entranceCenterLocal(m),ext.x,ext.y,ext.z);\n            float cavity=SDF_Ellipsoid(local-M_cavityCenterLocal(m),M_cavityRadii(m));\n            if(M_sweptSkull(m)) {\n                float wall=max(ext.y*2.0,M_faceMidRadii(m).x*.12);\n                cavity=max(cavity,SDF_EllipticalSweepZ(local,M_headStations(m),6)+wall);\n            }\n            float devMouth=clamp((M_cephalicDevelopment(m)-0.05)/0.25,0.0,1.0);\n            float cutter=SDF_SmoothUnion(entrance,cavity,M_entranceToCavitySmoothness(m))+(1.0-devMouth)*max(r.x,max(r.y,r.z))*2.0;\n            result=SDF_SmoothSubtract(result,cutter,M_rimBevel(m));\n        }\n        if(rayHeadActive&&M_anatomicalHead(m)) {\n            result=SDF_SmoothSubtract(result,MonsterSDF_EvalOrbitCavities(m,local),M_headUnionSmoothness(m)*.06);\n    ",
"        result=SDF_SmoothSubtract(result,MonsterSDF_EvalNostrilCavities(m,local),M_headUnionSmoothness(m)*.04);\n            if(M_hasTympana(m))result=SDF_SmoothSubtract(result,MonsterSDF_EvalTympanumCavities(m,local),M_headUnionSmoothness(m)*.04);\n        }\n    }\n    for(int i=0;i<mouthCount;++i) {\n        if(!rayJawActive)continue;\n        int m=mouthBase+i*M_STRIDE;\n        vec3 local=M_inverseRotation(m)*(p-M_center(m));\n        result=min(result,MonsterSDF_EvalPosedMouthDistance(m,local));\n    }\n    return result;\n}\nvoid main() {\n    if(validationMode!=0) {\n        if(!validateRayBoxes()){fragmentColor=vec4(1e6);return;}\n        tileOffset=-1;tileCount=connectorCount;\n        vec3 point=dataAt(validationPointBase+int(gl_FragCoord.x)).xyz;\n        float full=sceneDistance(point);\n        vec3 delta=point-cameraPosition;\n        if(dot(delta,delta)>1e-20) {\n            vec3 direction=normalize(delta);float start=0.0,end=1e30;\n            if(rayBox(cameraPosition,direction,boundsMin,boundsMax,start,end))classifyRay(direction,start,end);\n        }\n        fragmentColor=vec4(full,sceneDistance(point),0,1);gl_FragDepth=0;return;\n    }\n    vec2 uv=(gl_FragCoord.xy/viewportSize)*2.0-1.0;\n    vec3 rd=normalize(cameraForward+cameraRight*(uv.x*aspectRatio*tanHalfFov)+cameraUp*(uv.y*tanHalfFov));\n    float t=0.0,end=1e30;\n    if(!rayBox(cameraPosition,rd,boundsMin,boundsMax,t,end))discard;\n    classifyRay(rd,t,end);\n    int tile=int(gl_FragCoord.y)/16*tileColumns+int(gl_FragCoord.x)/16;\n    vec4 list=dataAt(tileDataBase+tile);tileOffset=int(list.x);tileCount=int(list.y);\n    vec3 p=vec3(0);vec4 sampleValue=vec4(0);bool hit=false;\n    for(int step=0;step<256;++step) {\n        p=cameraPosition+rd*t;sampleValue.w=sceneDistance(p);\n        if(sampleValue.w<hitTolerance){hit=true;break;}\n        float stepFactor=sampleValue.w>0.04?1.0:0.8;\n        t+=max(sampleValue.w*stepFactor,hitTolerance*.35);\n        if(t>end)break;\n    }\n    if(!hit)discard;\n    float e=hitTolerance*.65;\n ",
"   // Tetraedro sim\u00e9trico: cuatro muestras con radio comparable a las seis originales.\n    const vec3 k0=vec3(1,-1,-1),k1=vec3(-1,-1,1),k2=vec3(-1,1,-1),k3=vec3(1,1,1);\n    e*=0.57735026919;\n    vec3 gradient=k0*sceneDistance(p+k0*e)+k1*sceneDistance(p+k1*e)\n        +k2*sceneDistance(p+k2*e)+k3*sceneDistance(p+k3*e);\n    float norm2=dot(gradient,gradient);\n    vec3 n=norm2>1e-20?gradient*inversesqrt(norm2):-rd;\n    sampleValue=scene(p);\n    vec3 light=normalize(vec3(10,20,15)-p);\n    fragmentColor=vec4(sampleValue.xyz*(.4+max(dot(n,light),0.0)),1);\n    vec4 clip=viewProjection*vec4(p,1);gl_FragDepth=(clip.z/clip.w)*.5+.5;\n}\n",
};
